### ISSUE TITLE
ruibringer warband slaves to darkness battalion error

### ISSUE THREAD

**Issue by archaron9** [BSData/warhammer-age-of-sigmar#1002]
I think there is an error in the battalion ruinbringer warband from slaves to darkness. In the chaos book alliance and in the app WH AoS it says you need 1 chaos lord daemonic mount and 5+ units to choose from the following units:
chaos Knights, chaos Chariots, chaos Gorebeast, chaos marauder horsemen.

In battle scribe it says, 1 chaos lord daemonic mount and the same units but 3-8. Here I think that is the error, minimum has to be 5 or more. 

![Screenshot_20190719-140630__01](https://user-images.githubusercontent.com/53084579/61534042-c8777400-aa2e-11e9-8299-ce3651b70a7c.jpg)
![Screenshot_20190719-132925__01](https://user-images.githubusercontent.com/53084579/61534043-c8777400-aa2e-11e9-8927-eb0fe69f583f.jpg)

**Comment by archaron9** [comment]
Android BattleScribe v2.02.03.299

**Comment by cartag** [comment]
Updated in latest version.
