### ISSUE TITLE
Skaven pestilens

### ISSUE THREAD

**Issue by RedBishop777** [BSData/warhammer-age-of-sigmar#1014]
Skaven pestilens units (nurgle keyword) inside nurgle armies have to be added through skaven force roster and thus cannot have the nurgle allegiance and use command, artefacts or lore from the nurgle faction.

**Comment by cartag** [comment]
Corrected in latest release.

**Comment by RedBishop777** [comment]
@cartag : Forgive me for asking but this was closed as resolved and it really isn't (I may be wrong here, but hear me out): 

Slaves to darkness and Skaven units with the NURGLE keyword on their warscroll should show up in the nurgle roster when entered as main force. 

see: ![nurgleKword](https://user-images.githubusercontent.com/51464822/67256008-ea7bfa80-f452-11e9-8554-fcbf75a14cb8.jpg)

At the moment, you can select skaven or StD units only by adding these forces as allies or separate force in the root (and that means they cannot be set with a nurgle alliegeance.  Am I misunderstaning how this works or am I right in thinking ALL units with the nurgle keyword should go natively in the nurgle force roster?

Cheers!

**Comment by cartag** [comment]
Archaon is the defining model in Everchosen, he is not going to be linked in every individual god library. 

As for Skaven units, they are being implemented at a base level. The HQ units will not have access to the Nurgle god powers without significant reworking of the Skaven file, which will have to wait until somebody other than me is working on stuff.

**Comment by RedBishop777** [comment]
Saw you added most markable chaos dudes and skaven to the nurgle cat. Thank you! makes it so much better to use. You rock!
