### ISSUE TITLE
Disciples of Tzeentch bugs

### ISSUE THREAD

**Issue by nottsknight** [BSData/warhammer-age-of-sigmar#1027]
- [x] Curesling doesn't show rules for Glean Magic spell
- [x] Curseling doesn't allow to select an extra Lore of Fate
- [x] Heralds of Tzeentch don't allow to select an extra Lore of Change spell

**Comment by cartag** [comment]
Set your allegiance to Tzeentch for the last two, adding Glean Magic for the first.
