### ISSUE TITLE
Blessed Host not available.

### ISSUE THREAD

**Issue by TonyPeterLong** [BSData/warhammer-age-of-sigmar#1042]
The _Blessed Host Warscroll Battalion_ doesn't appear to be available as an option for _Order - Stormcast Eternals v44_.

**Comment by cartag** [comment]
Can you provide the warscroll?

**Comment by Ginjitzu** [comment]
![20191102_000101](https://user-images.githubusercontent.com/47611062/68041925-44f34180-fd04-11e9-9929-62f07bbf86e9.jpg)

**Comment by UrsinePatriarch** [comment]
This is a Battalion with no points value assigned and is thus not legal for matched play by GW's rules.

This is a non-issue because Battlescribe does not generally support illegal battalions in its catalogs due to their nature as Narrative/Open Play only.

Requesting closure of this issue.

**Comment by Ginjitzu** [comment]
Ah! I wasn't aware of the caveat that BattleScribe is for use in matched play only. I actually thought BattleScribe was entirely rules agnostic. In fact, I was of the Impression that BattleScribe didn't even care what *game* you play! Is there a link or something somewhere where I can see this policy?

**Comment by alphalas** [comment]
@UrsinePatriarch technically @Ginjitzu is correct (at least according to the 40k guidelines). 

@Ginjitzu the app itself is data agnostic, but each game system’s individual policies are set by their maintainers (see also the HH dukes having unofficial fan rules published right alongside legit). As such the snark isn’t super helpful. :)

**Comment by Ginjitzu** [comment]
@alphalas I was genuinely curious. I had no idea the maintainers set their own policies. I assumed they just followed the rules exactly. I was wrong. Your accusation of snark is pretty unwelcome.

**Comment by alphalas** [comment]
@Ginjitzu then allow me to be the first to apologize; I apparently tend to read in snark when I’ve not had enough coffee yet.

But yes, each individual repo sets their own policies and is free to do as they feel fit. What you’re familiar with is what the 40k repo does and what other repos are *encouraged* to do.

**Comment by alphalas** [comment]
Honestly this discussion probably is actually better served if taken to the discord server and discussed in #aos-data https://discord.gg/az9Cmu4

**Comment by cartag** [comment]
@UrsinePatriarch things that are legal for Open Play still have a place in AoS for BS. Add the battalion but just label it as Open Play for zero points.

**Comment by UrsinePatriarch** [comment]
Battalion: Blessed Host has been added to the data as "Open-Play Only" and will be available after the next update.

"Issue" is now resolved.
