### ISSUE TITLE
Uncategorized Items in Cities of Sigmar.cat v1

### ISSUE THREAD

**Issue by Veziik** [BSData/warhammer-age-of-sigmar#1064]
* Allegiance ability is classified under 'Uncategorised' as opposed to 'Allegiance', which causes Battlescribe to throw error "Order - Cities of Sigmar V1 (**Pitched Battke** 2,000) must have one more selections from Allegiance (Minimum 1)"
* "Sisters of the watch" are "Uncategorised" as opposed to classified as "Other"

**Comment by cartag** [comment]
Fixed in file 2, release pending.
