### ISSUE TITLE
Cities of Sigmar bugs and feature requests

### ISSUE THREAD

**Issue by nottsknight** [BSData/warhammer-age-of-sigmar#1067]
- [x] [Feature] Ability to mark hero as General's Adjutant
- [x] [Feature] Ability to mark unit as Honoured Retinue
- [x] [Feature] Hide artefacts, weapons, command abilities, spell lores that do not belong to the selected Stronghold or Realm
- [x] [Feature] Show Steam Tank with Commander in the Leader category
- [x] [Bug] Steam Tanks should not count as Behemoths if they are taken as Battleline
- [x] [Bug] Freeguild Greatswords should be 160pts per 10, not 120 (or 420pts at max strength)
- [x] [Bug] Demigryph Knights and Freeguild Greatswords should be Battleline if the general is Freeguild
- [x] [Bug] Freeguild Pistoliers and Outriders should be Battleline in a Tempest's Eye army

**Comment by cartag** [comment]
What platform are you on? The two bugs you list are showing properly on PC. The last feature request you list is also set up to do just that, but there was a bug in a recent update that has been affecting show/hides. It's performing properly on latest desktop release.

**Comment by nottsknight** [comment]
[Here's a screenshot.](https://imgur.com/a/rvbao1j) I'm on the latest desktop client, and data files are all up to date. I can always try deleting and redownloading the CoS file to see if that fixes things.

**Comment by cartag** [comment]
There's a v2.03.03 out for Battlescribe. It's showing properly for me in v2 of the file. 

![image](https://user-images.githubusercontent.com/4388344/67127966-acaf7580-f1b7-11e9-9b0f-9c22f6f2a508.png)

**Comment by nottsknight** [comment]
> There's a v2.03.03 out for Battlescribe

Ah interesting, that wasn't showing in the update channel when I checked earlier, but now it is. Updated and the two bugs are indeed resolved. Sorry for wasting time!

**Comment by cartag** [comment]
I've gotten General's Adjunct and Heroic Retinue implemented, but they're not showing/hiding like they should. After I get that bug worked out it'll be released.

**Comment by nottsknight** [comment]
Sorry to add some more! The recent FAQ has made it so that Steam Tanks stop counting as Behemoths if you're taking them as Battleline.

**Comment by Faitfull** [comment]
First of. You Guys are awesome. 
Regarding cities of sigmar. Can see the phoenix guards are still missing in the battlescribe roaster

**Comment by Faitfull** [comment]
any plans to add the missing units? like phoenix guards?

**Comment by cartag** [comment]
They should be in there with the latest release.

**Comment by Faitfull** [comment]
cannot help to think that perhaps there lacking place here might be the case?
not currently showing

<categoryEntries> 
|  <categoryEntry id="2e31-b1a1-10c7-22d4" name="GRIFFON" hidden="false"/> |
|


|  <categoryEntry id="f04c-3520-c73d-898e" name="FREEGUILD GENERAL" hidden="false"/> |
|


|  <categoryEntry id="2308-7db2-829e-94b3" name="HUMAN" hidden="false"/> |
|


|  <categoryEntry id="33e5-4f6f-37f4-c882" name="FREEGUILD" hidden="false"/> |
|


|  <categoryEntry id="0770-8b87-2d6f-7fe2" name="DEMIGRYPH KNIGHTS" hidden="false"/> |
|


|  <categoryEntry id="7c84-ab7a-23cb-d864" name="FREEGUILD ARCHERS" hidden="false"/> |
|


|  <categoryEntry id="dc80-e1f3-633d-985b" name="FREEGUILD CROSSBOWMEN" hidden="false"/> |
|


|  <categoryEntry id="97d4-f901-8df1-5206" name="FREEGUILD GREATSWORDS" hidden="false"/> |
|


|  <categoryEntry id="4771-57fd-9f7e-9cba" name="FREEGUILD GUARD" hidden="false"/> |
|


|  <categoryEntry id="864b-0972-2569-4b7b" name="FREEGUILD HANDGUNNERS" hidden="false"/> |
|


|  <categoryEntry id="9f0f-eb6f-1310-de2a" name="FREEGUILD OUTRIDERS" hidden="false"/> |
|


|  <categoryEntry id="2953-7f90-6414-ed94" name="FREEGUILD PISTOLIERS" hidden="false"/> |
|


|  <categoryEntry id="2fa3-7192-5ce2-10a5" name="CELESTIAL" hidden="false"/> |
|


|  <categoryEntry id="eb4c-f7bc-8966-0247" name="DEVOTED OF SIGMAR" hidden="false"/> |
|


|  <categoryEntry id="68ca-8042-65e4-e6d8" name="EXCELSIOR WARPRIEST" hidden="false"/> |
|


|  <categoryEntry id="9304-00ac-b0eb-8741" name="FLAGELLANTS" hidden="false"/> |
|


|  <categoryEntry id="d2e0-123f-1dd2-7992" name="COLLEGIATE ARCANE" hidden="false"/> |
|


|  <categoryEntry id="18e1-27b1-33f8-2955" name="BATTLEMAGE" hidden="false"/> |
|


|  <categoryEntry id="0cda-4c8e-b048-9cfe" name="LUMINARK OF HYSH" hidden="false"/> |
|


|  <categoryEntry id="0160-a43b-3ac7-570d" name="CELESTIAL HURRICANUM" hidden="false"/> |
|


|  <categoryEntry id="cccb-89cd-393f-5839" name="CITIES OF SIGMAR" hidden="false"/> |
|


|  <categoryEntry id="7fe9-bc03-2c82-0a00" name="AELF" hidden="false"/> |
|


|  <categoryEntry id="fd81-217d-c605-518a" name="SORCERESS" hidden="false"/> |
|


|  <categoryEntry id="2b62-a20b-c306-8582" name="BLACK GUARD" hidden="false"/> |
|


|  <categoryEntry id="f6cc-5806-08f4-da01" name="BLEAKSWORDS" hidden="false"/> |
|


|  <categoryEntry id="596b-531e-d061-efe8" name="EXECUTIONERS" hidden="false"/> |
|


|  <categoryEntry id="1989-50a2-b786-6dd8" name="DREADSPEARS" hidden="false"/> |
|


|  <categoryEntry id="09b5-40ff-3401-9d42" name="DARKSHARDS" hidden="false"/> |
|


|  <categoryEntry id="945b-2f5e-58f0-75e2" name="DUARDIN" hidden="false"/> |
|


|  <categoryEntry id="1907-88f7-307b-fbf9" name="WARDEN KING" hidden="false"/> |
|


|  <categoryEntry id="8e87-284f-3210-b8d7" name="LONGBEARDS" hidden="false"/> |
|


|  <categoryEntry id="04b0-28bd-0eac-d481" name="IRONDRAKES" hidden="false"/> |
|


|  <categoryEntry id="e5be-882b-f509-c6e9" name="IRONBREAKERS" hidden="false"/> |
|


|  <categoryEntry id="3b69-2bdd-499a-64e0" name="HAMMERERS" hidden="false"/> |
|


|  <categoryEntry id="0cb1-8b30-c44d-2b7a" name="RUNELORD" hidden="false"/> |
|


|  <categoryEntry id="e81b-95b7-4866-db4b" name="HAMMERERS" hidden="false"/> |
|


|  <categoryEntry id="920f-7600-9c65-a179" name="COGSMITH" hidden="false"/> |
|


|  <categoryEntry id="b825-7b2f-9a1e-7c32" name="ENGINEER" hidden="false"/> |
|


|  <categoryEntry id="75be-5b58-c14b-0395" name="GYROCOPTERS" hidden="false"/> |
|


|  <categoryEntry id="c0c3-8fb0-b48a-596f" name="GYROBOMBERS" hidden="false"/> |
|


|  <categoryEntry id="fb7a-5518-128d-c331" name="HELBLASTER VOLLEY GUN" hidden="false"/> |
|


|  <categoryEntry id="55c7-9a88-fb09-583e" name="CANNON" hidden="false"/> |
|


|  <categoryEntry id="eb9d-026c-8282-15ef" name="GUNMASTER" hidden="false"/> |
|


|  <categoryEntry id="3dfb-ff02-f0e1-6cb1" name="HELSTORM ROCKET BATTERY" hidden="false"/> |
|


|  <categoryEntry id="4807-239b-4c1d-3211" name="IRONWELD ARSENAL" hidden="false"/> |
|


|  <categoryEntry id="db6e-b4df-35e6-1658" name="ORGAN GUN" hidden="false"/> |
|


|  <categoryEntry id="3805-83b3-bdf5-6342" name="STEAM TANK" hidden="false"/> |
|


|  <categoryEntry id="9713-6dce-4061-3e7f" name="PHOENIX TEMPLE" hidden="false"/> |
|


|  <categoryEntry id="d0a0-7cc4-50c4-28cf" name="DRAKESPAWN CHARIOTS" hidden="false"/> |
|


|  <categoryEntry id="fc32-6d3b-edb5-5c13" name="DRAKESPAWN KNIGHTS" hidden="false"/> |
|


|  <categoryEntry id="35e2-6e38-34ac-dbe5" name="DREADLORD" hidden="false"/> |
|


|  <categoryEntry id="487f-1015-0923-3ee0" name="ORDER SERPENTIS" hidden="false"/> |
|


|  <categoryEntry id="7d80-7a90-95b6-2095" name="WAR HYDRA" hidden="false"/> |
|


|  <categoryEntry id="63db-10c5-e70d-a003" name="ASSASSIN" hidden="false"/> |
|


|  <categoryEntry id="a553-42c9-fdda-4a86" name="SHADOWBLADES" hidden="false"/> |
|


|  <categoryEntry id="1864-84db-ccc1-544b" name="DARK RIDERS" hidden="false"/> |
|


|  <categoryEntry id="b20e-4d1b-aa96-53af" name="ETERNAL GUARD" hidden="false"/> |
|


|  <categoryEntry id="156b-d02a-8c8e-4401" name="GLADE GUARD" hidden="false"/> |
|


|  <categoryEntry id="cf1c-4287-f2ed-ceec" name="NOMAD PRINCE" hidden="false"/> |
|


|  <categoryEntry id="3573-2883-8447-2a1d" name="SISTERS OF THE THORN" hidden="false"/> |
|


|  <categoryEntry id="9bf4-4067-f587-a008" name="SISTERS OF THE WATCH" hidden="false"/> |
|


|  <categoryEntry id="f78e-3730-9323-b832" name="SPELLWEAVER" hidden="false"/> |
|


|  <categoryEntry id="a83c-f6d2-31f5-765c" name="WILDWOOD RANGERS" hidden="false"/> |
|


|  <categoryEntry id="f12b-14b1-eff9-c3cc" name="WILD RIDERS" hidden="false"/> |
|


|  </categoryEntries> |
|


|  <entryLinks> |
|


|  <entryLink id="d1b4-4124-e5f1-ddf5" name="Luminark of Hysh" hidden="false" collective="false" import="true" targetId="c2cb-f59d-ec38-10c8" type="selectionEntry"/> |
|


|  <entryLink id="48f8-0cd0-c224-e202" name="Freeguild General" hidden="false" collective="false" import="true" targetId="aada-2a08-7231-2d0e" type="selectionEntry"/> |
|


|  <entryLink id="e1ec-efa7-67c0-03bc" name="Freeguild General on Griffon" hidden="false" collective="false" import="true" targetId="f97b-a868-659a-a9e5" type="selectionEntry"/> |
|


|  <entryLink id="fda5-33e1-17e6-3b70" name="Celestial Hurricanum" hidden="false" collective="false" import="true" targetId="9329-90d0-1c0a-eb4b" type="selectionEntry"/> |
|


|  <entryLink id="aa5e-44f7-bed0-8d70" name="Demigryph Knights" hidden="false" collective="false" import="true" targetId="997f-3956-6049-cc04" type="selectionEntry"/> |
|


|  <entryLink id="5261-f6e9-39cd-854b" name="Freeguild Greatswords" hidden="false" collective="false" import="true" targetId="2285-8b6d-cc95-1dac" type="selectionEntry"/> |
|


|  <entryLink id="6d30-660e-b258-674c" name="Freeguild Guard" hidden="false" collective="false" import="true" targetId="ce08-26df-f117-e698" type="selectionEntry"/> |
|


|  <entryLink id="0787-3575-914a-5d5c" name="Freeguild Outriders" hidden="false" collective="false" import="true" targetId="032e-7267-915b-61e8" type="selectionEntry"/> |
|


|  <entryLink id="b88f-329e-f9ab-44a0" name="Irondrakes" hidden="false" collective="false" import="true" targetId="c002-5bdd-6570-318c" type="selectionEntry"/> |
|


|  <entryLink id="48ca-3230-4764-e585" name="Freeguild Handgunners" hidden="false" collective="false" import="true" targetId="74b7-10a4-e9c7-8035" type="selectionEntry"/> |
|


|  <entryLink id="6dee-69e4-8940-e6d7" name="Freeguild Crossbowmen" hidden="false" collective="false" import="true" targetId="731e-cbfa-70d8-28eb" type="selectionEntry"/> |
|


|  <entryLink id="166d-212e-323a-5373" name="Flagellants" hidden="false" collective="false" import="true" targetId="6c57-67c3-945c-aaa9" type="selectionEntry"/> |
|


|  <entryLink id="36a3-909d-6d66-488b" name="Assassin" hidden="false" collective="false" import="true" targetId="bec5-213e-eccf-17e0" type="selectionEntry"/> |
|


|  <entryLink id="9a80-45f2-d7a6-f86c" name="Allegiance" hidden="false" collective="false" import="true" targetId="87f8-d0f2-e2c7-0668" type="selectionEntry"> |
|

 <categoryLinks>

    On Tuesday, October 29, 2019, 8:59:49 PM GMT+1, cartag <notifications@github.com> wrote:  
 
 
They should be in there with the latest release.

**Comment by cartag** [comment]
Finalized in v7.
