### ISSUE TITLE
Bug report: Death - Legions of Nagash and Nighthaunt.catz ! Soulblight Varghiest battleline

### ISSUE THREAD

**Issue by Cylogenesis** [BSData/warhammer-age-of-sigmar#1068]
BattleScribe v2.03.05.311

Hi, AoS team! In the most recent few updates to the data for AoS, under Soulblight subfaction for LoN, varghiests should be able to be taken as Battleline as of GHB2019.

**Comment by cartag** [comment]
Corrected in latest release
