### ISSUE TITLE
A large chunk of the units have NO STATS

### ISSUE THREAD

**Issue by tw6464** [BSData/warhammer-age-of-sigmar#107]

**Comment by flakpanda** [comment]
We are aware of the issue. All the initial data entry is still in progress.

**Comment by tw6464** [comment]
ah. is there an ETA when it will be done?

**Comment by flakpanda** [comment]
Unfortunately no. This is all volunteer work to help maintain the data.

**Comment by tw6464** [comment]
Well, I'd help do it. I have all the battletomes, warscrolls and warscroll battalions so I can easily get it done.

**Comment by flakpanda** [comment]
I am at work. I will have to get you up to speed later today.

**Comment by tw6464** [comment]
alright then, just tell me what to do to start working

**Comment by vicanic** [comment]
I am also willing to help. With stat entry

**Comment by impclaw** [comment]
I've been working on Tzeentch units, and would like confirmation that what I've done so far is correct. I can merge all the small commits into a large one later. I have not increased the revision number of the data files: 

Here is the fork: https://github.com/impclaw/warhammer-age-of-sigmar

If there is interest, and I got it right, I will finish at least the remaining Tzeentch entries.

**Comment by flakpanda** [comment]
Please use a merge request when completed
