### ISSUE TITLE
Death - Legions of Nagash and Nighthaunt.catz

### ISSUE THREAD

**Issue by marktemba** [BSData/warhammer-age-of-sigmar#1085]
Choosing the Lords of Sacrament battalion in Legions of Sacrament, BS wants Arkhan to be selected again despite being included in the battalion and made general.

2ndly, how may I join the LoN/NH crew to help update warscroll details etc?

![image](https://user-images.githubusercontent.com/23230996/67672275-e3d01480-f977-11e9-97d7-340eadcedda3.png)

**Comment by cartag** [comment]
The LoN/Nighthaunt file is currently being reworked so it's no longer combined. If you'd rather be the one to work on it, I can summon @amis92 for an invite

**Comment by cartag** [comment]
Corrected (I think) in next release. Changed from needing 1 min in parent when Legion of Sacrament to needing 1 in roster.
