### ISSUE TITLE
Bug Report - Gloomspite Gitz - Troggherd Battalion

### ISSUE THREAD

**Issue by cgordon13** [BSData/warhammer-age-of-sigmar#1088]
Summary - after creating a valid Troggherd Battalion based list, I still see a validation error: "Battalion: Troggherd must have 3 more selections from 2. Troggoths (3-9) (minimum 3)"

Steps to reproduce:
1. Create a new list - Gloomspite Gitz - **Pitched Battle*
2. Add Battalion Troggherd
3. Add Leader - Dankhold Troggboss - make General
4. Add 3 Battleline units of Fellwater Troggoths
5. Check validation to see the above error

Expected result: no errors in validation.

**Comment by cartag** [comment]
Set up Gitz to use similar logic as others. Battleline will be set correctly now. Corrected in v17.
