### ISSUE TITLE
Missing Unit - Naighthaunt Black Coach

### ISSUE THREAD

**Issue by Xemit64** [BSData/warhammer-age-of-sigmar#1090]
As of the latest entry which split Nighthaunt out, the Black Coach has disappeared.

Some units got moved around, but the entire Behemoth group seems to have disappeared.

Also noted a bug in the Battleline group. Create a Nighhaunt roster, Set allegiance to Death, and save roster. Note the units in Battleline.

Change Allegiance to Nighthaunt and note the extra units in Battleline, OK. Now  hit save roster and watch all the doubled units show in the list.

**Comment by cartag** [comment]
Readded Black Coach, Thorns of Briar Queen. Behemoth group back with Black Coach. Resolved in v2.

Duplication of units is an app problem instead of data problem and app dev is aware of it.
