### ISSUE TITLE
Missing Ogor Mawtribes content

### ISSUE THREAD

**Issue by ZeGerman1** [BSData/warhammer-age-of-sigmar#1093]
Ogor Mawtribes content needed, Many OGOR Destruction armies combined into one new book, Rules updated etc. Putting this up as i cant find anything mentioning it to be included / updated.
would love to help but coding knowledge = 0%

**Comment by cartag** [comment]
It's only been out for 48 hours, give us some time. This is a volunteer effort.

**Comment by ZeGerman1** [comment]
Sorry didn't mean to sound rude/pushy.
keep up the good work though :) would love to lend a helping hand. I'll see tonight if i can contribute anything / learn coding.. or at least data input? will see

**Comment by cartag** [comment]
Posted initial copy, will push release tonight.
