### ISSUE TITLE
Disciples of Tzeench, two issues

### ISSUE THREAD

**Issue by simakover** [BSData/warhammer-age-of-sigmar#1097]
1. Curseling, eye of tzeentch does not have passive ability from warscroll: cast spell that he unbind
2. if you choose an Changehost battalion and Gaunt summoner and give LoC an artifact and artifact for Gaunt this cause error that you have too many artifacts, but batallion give an aditional artifact so you can take two without errors

**Comment by cartag** [comment]
1) Fixed in v38
2) Unable to duplicate
