### ISSUE TITLE
[Join Request] Warhammer: Age of Sigmar

### ISSUE THREAD

**Issue by flakpanda** [BSData/warhammer-age-of-sigmar#11]
I am currently working on a AoS data file set and would like to host it here. I currently only have 3 faction from Order completed, but working most days on adding more. If you have any questions, please let me know. Thank you.

**Comment by cartag** [comment]
Flakpanda, you can upload to this group, it will help us keep one main resource. I expect we'll see a huge uptick once the book with the points comes out.

Paging @amis92 since I have no idea how to invite people

**Comment by amis92** [comment]
Hello, @flakpanda. Please accept the invitation in the email or on the [BSData organization webpage](https://github.com/BSData). Welcome aboard!

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

Cheers!
