### ISSUE TITLE
Ogor Mawtribes issues

### ISSUE THREAD

**Issue by StuxAlpha** [BSData/warhammer-age-of-sigmar#1107]
Units of more than 4 Leadbelchers stop counting as Battleline - should be units of 2 are not Battleline, any size larger are battleline.

Tyrants are missing Tyrant's Plunder (artefacts). These were present in the previous version.

Battalion "Kin-Eater’s Bully Boys" missing.

Priests across the army should be able to pick a prayer (including Frostlords with the Touched By The Everwinter trait).

Butchers shouldn't be able to take Lore of the Sun-Eater

Firebellies shouldn't be able to take Lore of Gutmagic.

**Comment by cartag** [comment]
1. Fixed in next version

2) Fixed in next version

3) Where is that battalion from? 

4) In progress

5) Fixed in next version

6) Fixed in next version

**Comment by StuxAlpha** [comment]
The Battalion is from the Feast of Bones box set.

**Comment by cartag** [comment]
Do you have a copy of it or can you link to it? I need something I can go off of to enter it.

**Comment by StuxAlpha** [comment]
Sure thing, image here:

Feast of Bones battalions https://imgur.com/a/F72wKSa

120pts

**Comment by StuxAlpha** [comment]
Kin Eater battalion is showing as uncategorised instead of the Battalion section.

Tyranids plunder have returned, but the wrong names are displaying when viewing the list. The ability itself is correct though, as are the names when building the list.

**Comment by UrsinePatriarch** [comment]
All concerns listed have been fixed in next version.
