### ISSUE TITLE
Ogor mawtribes bugs

### ISSUE THREAD

**Issue by ranzani1** [BSData/warhammer-age-of-sigmar#1110]
Ironguts should  not have the iron fist weapon option

Mournfang Pack should only have the option for banner bearer and horn blower at 4 man units or more

Gluttons should have two options available for banner bearers, the great beast skull and the tribal banner both of which can be used at the same time and only be able to have banners and bellowers at 6 man units or more

**Comment by StuxAlpha** [comment]
I'm not convinced on Mournfang. 1 in 4 in that context just says to me that you can't have a 2nd one until you're over 4 models. Unless there's an FAQ setting precedent the other way.

**Comment by StuxAlpha** [comment]
Same for Gluttons and 1 in 6.

**Comment by ranzani1** [comment]
The rules for allies work this way where 1 in every 4 units can be an ally and you have to have 3 units from the original alliance, and every player I know uses the rules the way I sent at first. The orruk warclans tome has units with the same wording and the FAQ did not state anything about it.

**Comment by StuxAlpha** [comment]
You may well be right, but it wasn't how I had read it.

It's not normally an issue as most units don't have a minimum size below the number noted for musicians/banner bearers.

**Comment by ranzani1** [comment]
The clarification is on core rules design commentary page 2
![Screenshot_2019-11-11-13-02-00](https://user-images.githubusercontent.com/57612399/68601914-156ed280-0484-11ea-947e-10411c130e3e.png)

**Comment by cartag** [comment]
@ranzani1 is correct on this. I'm implementing now.

**Comment by cartag** [comment]
Resolved in next release.
