### ISSUE TITLE
Ogor Mawtribes validation issues and Ironguts issue

### ISSUE THREAD

**Issue by Rautia** [BSData/warhammer-age-of-sigmar#1121]
File: Mawtribes v2

Issues:

- Some Mawtribe specific command traits and artefacts aren't counting as equipped on a hero and give out several validation errors (example pic with Meatfist tribe)
![validationerror](https://user-images.githubusercontent.com/25813380/69099150-b9e3ac80-0a62-11ea-9df3-e66c914c8562.png)

-Ironguts unit is forced to choose between Paired Weapons and an Ironfist, even though this option is only supposed to be on the Gluttons (Ironguts don't have weapon options).

**Comment by cartag** [comment]
Referred to BS app developer. Ironguts issue already resolved.
