### ISSUE TITLE
[NURGLE] Blessed sons batallion doesn't seem to add up CPs and artefacts correctly

### ISSUE THREAD

**Issue by RedBishop777** [BSData/warhammer-age-of-sigmar#1123]
When using the blessed sons super batallion (which includes other batallions as requirements) it doesn't seem to tally up the extra artefacts and command points from the included batallions. 

Same seems to be tru of the tallyband of nurgle (even tho nobody cares about that one) :)

**Comment by cartag** [comment]
Fixed in v39
