### ISSUE TITLE
Nurgle Plague Drones Wrong Points

### ISSUE THREAD

**Issue by MarkB053** [BSData/warhammer-age-of-sigmar#1127]
The points for Plague Drones is incorrect. You have it at 400 pts for a unit and it is 200 pts. It is listed correctly listed at 200 pts when you mouse over the unit entry in the unit selection window

**Comment by MarkB053** [comment]
![Plague Drones](https://user-images.githubusercontent.com/57118055/69482165-70fe7000-0e35-11ea-870d-4f63dfd93a2e.png)
Here is a screen shot showing the issue. The points are also wrong on the iPad version

**Comment by Drakhalan** [comment]
Have you updated? the problem was solved for me with the newest release.

![Screenshot_1](https://user-images.githubusercontent.com/57844834/69682436-57e8ff80-107f-11ea-9aff-5625ed45f64a.png)

**Comment by MarkB053** [comment]
Yep, tried that. Even tried uninstalling and reinstalling both the AoS repository and the Battlescribe client but the issue is still there. However I did uninstall and reinstall it on my iPad and the issue is fixed so absolutely no idea what is going on.

**Comment by MarkB053** [comment]
Sorted. Had to uninstall then delete %appdat% folder and folders in my user profile then reinstall.
