### ISSUE TITLE
Cities of Sigmar: 2 Bugs, 2 Requests

### ISSUE THREAD

**Issue by Veziik** [BSData/warhammer-age-of-sigmar#1129]
- bug: Whitefire retinue battalion requires 3-6 selections of HERO WIZARDS but current implementation allows for the selection of only one
- bug: Honoured Retinue must contain between 5 and 20 models, implementation currently does not throw an error when a unit with x>20 models is selected 
- Request: current battalion display organizes information for multiple units as if it were one unit, request that unit profiles be either nested within the battalion selection, or for a battalion selection to count as it's own selection without nested profiles and change the requirements of the overall list to add the requirements of the battalion
- Request: When a wizard selects a trait or relic that gives them all the spells of a certain city, all the spell profiles should either be added to that wizard or they should be eligible to select all of the spells for that city

**Comment by cartag** [comment]
1) Resolved in next release
2) Working on implementation
3) Battlescribe issue, one that has already been raised with the dev. 
4) Working on implementation

**Comment by cartag** [comment]
Honored Retinue is implemented
