### ISSUE TITLE
Ossiarch Bonereapers

### ISSUE THREAD

**Issue by UrsinePatriarch** [BSData/warhammer-age-of-sigmar#1138]
Vokmortian's Retinue is not included in the Battalions section.

**Comment by Tigerwraith** [comment]
@UrsinePatriarch what Battalion are you talking about?

**Comment by StuxAlpha** [comment]
![Screenshot_20191109-235035](https://user-images.githubusercontent.com/57574942/71215432-9d2fd400-22af-11ea-90d6-9dc2e474268b.jpg)

Included in the Feast of Bones box
