### ISSUE TITLE
Cities of Sigmar 

### ISSUE THREAD

**Issue by crownedzoidberg** [BSData/warhammer-age-of-sigmar#1141]
Describing this Case for Tempest Eye(1) Allegiance, but the same is true for Living City(2) and Free Cities(3). Source: Cities of Sigmar Battletome pg 63, 66, 76

Rules mentioned above are named Stormkeeps, The City Wargroves, Standing Contracts

Issue: 1 in every 4 units in your army (given they belong to the above mentioned allegiance) are allowed to be Kharadron Overlords (1), Sylvaneth (2) or Stormcast Eternals (3) - however, additional units don't become available after having 4 "original" Cities of Sigmar units in your roster. Those "1 in 4 - units" should also get the Cities of Sigmar and Allegiance Keyword.

Recommendation: Add (1), (2) or (3) through Allies Force Org. and make the new Allegiances selectable.

Furthermore, those chosen "1 in 4 - units" should also be available to become General or Adjunct, receive Warlord Traits and Relics of their Allegiance and count towards Battleline; if they were before. 

(My understanding of ruling is probably not 100% correct here, but afaik you could run a Tempest Eye Allegiance Army with AEther Khemist Warlord and a unit of Arkanaut Company - there's just no possibility to select this in Battlescribe to this current day.)

**Comment by cartag** [comment]
Implementing the 1 in 4 units is not going to be easily possible. There are so many different options it could get close to bogging down BS to where it won't run easily. Your best bet is to just add a second root level force and use them that way. This will have to be a wishlist feature.

**Comment by cartag** [comment]
1 in 4 validation should be working in next release.
