### ISSUE TITLE
Legions of Nagash - should not have Nighthaunt battalions

### ISSUE THREAD

**Issue by StuxAlpha** [BSData/warhammer-age-of-sigmar#1145]
As per the designer's commentary on the Legions of Nagash book, Legions (including all sub allegiences) may not use Nighthaunt Battalions.

The only way to access them is to count the Nighthaunt as allies, and that should be handled by adding a Nighthaunt allied force to the roster.

**Comment by cartag** [comment]
And from what I'm seeing they don't in the current file. Is there a specific one you're seeing they have access to?

**Comment by StuxAlpha** [comment]
All of them I'm afraid. This is with Legion of Blood selected as allegiance. Only the first 5 are Legions of Nagash battalions, the others should all be Nighthaunt allegiance only.

![20191216_075254](https://user-images.githubusercontent.com/57574942/70888828-19d56080-1fd9-11ea-8e09-89db9bf3bed1.jpg)

**Comment by cartag** [comment]
Update your data, and tell it to delete existing data when you do. This isn't how the current files are set up and you should not be seeing this.

**Comment by StuxAlpha** [comment]
@cartag I have deleted the files and reloaded data. It's now removed all Battalions, except for the one Legion specific Battalion. It should be possible to use the Battalions across Legions (just not Nighthaunt). If there is a way to do it, I cant find it sorry.

FAQ:

Q: Can the warscroll battalions for specific Legions be taken 
outside of the Legion named on their warscrolls?
A: The First Cohort can only be taken as part of the 
Grand Host of Nagash (because the other Legions 
cannot include Nagash). Any other battalions for 
specific Legions can be included as part of a different 
Legion as long as that Legion also includes the Mortarch 
that must lead it. For example, to include the Court of 
Nulahmia in a Legion of Sacrament army, the army 
would also have to include Arkhan the Black (because if 
the Legion of the Sacrament has any Mortarchs, one 
must be Arkhan).

**Comment by UrsinePatriarch** [comment]
Concerns have been addressed; Legion-specific battalions will be available to all Legions with restrictions (excepting Legion of Grief) and generic Death battalions will be available to all Death allegiances (excepting Legion of Grief).

These updates will be available within the next few days.
