### ISSUE TITLE
Troggoths - issues

### ISSUE THREAD

**Issue by StuxAlpha** [BSData/warhammer-age-of-sigmar#1152]
Troggoths missing statlines. This applies to Rockgut, Sourbreath and Fellwater varieties. None have their main statline.

Rockgut Troggoths missing Throwin' Boulders ability.

Also, should the catalogue have Dankhold Troggoth, Danhold Troggboss and Mollog? They are in the Gloomspite Gitz Catalogue, but it seems it would make sense for them to be in the Troggoth catalogue too - unless there's a policy reason otherwise.

**Comment by UrsinePatriarch** [comment]
1) They are indeed missing their profiles for some reason; however, this is a largely deprecated catalog, so it likely won't be fixed anytime soon
2) Same as above, old profile, deprecated catalog
3) This is incorrect; Troggoths as a force are a holdover from GA: Destruction and have thus not been updated at all with any of the newer units.

Truthfully, seeing as Sourbreaths are the only unit not included and they also aren't even supported by GW anymore, it's almost literally no difference from just playing all Troggoths in Gloomspite.

**Comment by StuxAlpha** [comment]
Actually checking the Rockgut Warscroll available online from GW and it is very different in several ways to what is currently in the catalogue, so I'm a bit a confused about that.

**Comment by StuxAlpha** [comment]
Thank you for that info. Does that mean these warscrolls should be in the Gloomspite catalogue then?

**Comment by UrsinePatriarch** [comment]
Yes, all currently supported Troggoth warscrolls are part of Gloomspite now, as per their Battletome; this includes the Troggoth Hag, the Rockguts, the Fellwaters, the Dankhold Troggoth and Troggboss, and Mollog.
Unfortunately, Sourbreaths were not given new warscrolls nor points to use, so they have been sorta dropped from the Battletome.

**Comment by StuxAlpha** [comment]
Right. But as far as I can see Rockguts and Fellwaters are not currently in the Gloomspite catalogue either. Which is why I started using the Troggoth catalogue.

**Comment by StuxAlpha** [comment]
Ok, so I started using the Troggoth catalogue because I couldn't find Rockguts (or Fellwaters) in the Gloomspite catalogue, for use as Allies for Ogors. Ogors have Troggoths as allies, but not Gloomspite Gitz too.

Now if I create a new roster for Gloomspite Gitz I see Rockguts and Fellwaters as battleline. However when I add Gloomspite as an allied allegiance to my Ogor roster those warscrolls dont seem to appear anywhere. They should be under Other right?

**Comment by UrsinePatriarch** [comment]
Alright, here's where the fun begins.

1) Ogors get Gargants and Troggoths as Allies; these are both in the GsG catalog now because of the Battletome, but they can't use any other GsG units, so there's no easy way to implement that.
2) Yes, the GsG catalog is currently bugged; Rockguts and Fellwaters are only Battleline with a Troggboss General, but the logic for it in the data is currently incorrect; there's an new update coming down the line right now that'll be available soon.

**Comment by StuxAlpha** [comment]
@UrsinePatriarch great, thank you very much for the clarification. 

If the fix for Rockguts and Fellwaters no appearing properly in GsG is incoming then I think this issue can be closed.
