### ISSUE TITLE
Slaves to Darkness missing info and incorrect point values

### ISSUE THREAD

**Issue by Brassclaw** [BSData/warhammer-age-of-sigmar#1153]
Hey there, I know that the new book came out but there is some missing information and some incorrect point values, I will give a list below on what needs fixing. 

MISSING: Lore of the Damned
MISSING: Slaves of the Damned Endless Spells
Chaos Sorcerer Lord is now only 110 points, warscroll needs to be updated 
MISSING: Gaunt Summoner on Disc of Tzeentch
Soul Grinder is now 210
MISSING: Curs’d Ettin
Bloodmarked Warband is posted twice 

That's what I have found so far.

**Comment by cartag** [comment]
Linked Lore of the Damned now
Added proper primary category for Endless Spells
Already updated Chaos Sorcerer Lord
Linked Gaunt Summoner on Disc of Tzeentch
Corrected Soul Grinder points
Curs'd Ettin is not part of the Slaves to Darkness battletome and will not be included
Removed second link to Bloodmarked Warband
