### ISSUE TITLE
Ogor Issues

### ISSUE THREAD

**Issue by StuxAlpha** [BSData/warhammer-age-of-sigmar#1173]
Gluttons
- should be able to have 2 Bellowers at 12 models.
- should be able to have 2 of each banner at 12 models. 

Butchers
- In Bloodgullet, should be able to pick 2 spells.

**Comment by cartag** [comment]
No catalogs to my knowledge are set up to bring X number of musicians or bannermen, it's just a check box showing that you are bringing some. I updated the text to be plural instead.

Butcher updated in v7.
