### ISSUE TITLE
Gloomspite Gitz - can't add orruk-gore-gruntas allies 

### ISSUE THREAD

**Issue by bliink123** [BSData/warhammer-age-of-sigmar#1180]
Can't add Ironjawz - Gore Grunters as allies to a pitched battle Gloomspite Gitz list.
Tried adding from - Ironjawz.cat & Orruk warclans.cat

Can add ardboys as 'other' fine, gore gruntas not showing under 'other'

**Comment by cartag** [comment]
Fixed in v8.
