### ISSUE TITLE
Database has no model data

### ISSUE THREAD

**Issue by Arkevorkhat** [BSData/warhammer-age-of-sigmar#119]
I cannot get this data file to display any models or units. I open a class page,  say order battlelines, and nothing shows up.

**Comment by DimarypEvans** [comment]
I'm having the same issue. iPhone 6s Plus fully updated. I don't see any entries anywhere for anything Age of Sigmar. Tried refreshing/data and even uninstalled/reinstalled app. Still nothing.

**Comment by StealthKnightSteg** [comment]
@Arkevorkhat @DimarypEvans can you give a step by step process on what you do until you can not see anything? Because if I open up a new roster and do all the selecting it works fine

**Comment by DimarypEvans** [comment]
I see what i did wrong. I wasn't selecting an allegiance.
