### ISSUE TITLE
[Anon] Bug report: Order - Fyreslayers - Data.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#1205]
**File:** Order - Fyreslayers - Data.catz

**BattleScribe version:** 2.03.09

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Vulkite Berzerkers are displaying as 20 points more expensive than as shown on the most recent update to the AoS app. Hearthguard Bezerkers are now capped at 20 for 400 points according to the AoS app, not the old 30 for 600.

**Comment by UrsinePatriarch** [comment]
Issue resolved as of v37, 1/27/20.
