### ISSUE TITLE
[Anon] Bug report: Chaos - Slave of Darknes

### ISSUE THREAD

**Issue by berny80** [BSData/warhammer-age-of-sigmar#1224]
Hi, I noticed that for Age of Sigmar in the Salve of Darkness list, there is an error in the Chaos Lord on Karkadrak statistics regarding the various weapons. Both the number of attacks of the various weapons and the To Hits and To Wounds compared to the official GW codex. Can you fix it?

**Comment by berny80** [comment]
EDIT: The Chaos Knights also have an error, Trampling Hooves the number of attacks from codex are 2 on the battlescrib are 4.

**Comment by berny80** [comment]
EDIT 2: Chaos Warriors have an error, Bravery from codex value 7 on battle scribe value 6.

**Comment by cartag** [comment]
All resolved in v12 of data file. Will be in next release.
