### ISSUE TITLE
Report Bug Beasts of Chaos 

### ISSUE THREAD

**Issue by axiummolecule** [BSData/warhammer-age-of-sigmar#1234]
The Batallion Points a way of 
Also the Cockatrice are missing as well as Grashrak Fellhoof and his Boys 

Would be great if this might be sorted out
thanks in Advance

**Comment by cartag** [comment]
1) Battalion points are all exactly where they should be

2) Added in next release

3) Already added in next release.

**Comment by axiummolecule** [comment]
580 Points for the Marauding Brayherd
or 670 for the Hungering one compared to 180 and 150 points. Doesn't seem to be exactly where they are supposed to be

well mayby I will sort it out

thx for the Next Update preview though

**Comment by cartag** [comment]
Try adding one of those to your list. You'll see they auto include units that are mandatory, increasing the points total that shows. The points for the battalions themselves are accurate. Marauding Brayherd includes a Beastlord, 1 great bray shaman, and 3 units of Gors as mandatory, and those are all included.

**Comment by axiummolecule** [comment]
thx.
Also I did find a minor flaw. 
In the Batallion Phantasmagoria of fate I'm not able to put my Tzaangor Enlightened on Discs. In there warscroll it is an option. If you might be so kind to ad these in the next Update?

Thanks

**Comment by cartag** [comment]
Phantasmagoria of Fate is not able to have Tzaangor Enlightened on Discs, it is spelled out plainly in the battletome. If it had listed TZAANGOR ENLIGHTENED instead of Tzaangor Enlightened it would be keywords, and the disced version would be valid.
