### ISSUE TITLE
Blades of Khorne addition

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#124]
**File:** Age of Sigmar.gstz

**BattleScribe version:** 2.01.00

**Platform:** Windows

**Dropbox:** No

**Description:** The new Battalions from the Blades of Khorne tome don't exist. These should be added. Examples are Gore Pilgrims and Murderhost.

**Comment by Mad-Spy** [comment]
Closing in anticipation of re-release
