### ISSUE TITLE
Stormcast Eternals - Castigator Battleline

### ISSUE THREAD

**Issue by StuxAlpha** [BSData/warhammer-age-of-sigmar#1242]
Castigators are never Battleline. 

Currently in the app they are made Battleline with a Lord Arcanum General, but this is incorrect. There is no way to make them Battleline - this should only apply to Sequitors.

![Screenshot_20200207-192541_Drive](https://user-images.githubusercontent.com/57574942/74059283-a734a000-49df-11ea-87ef-d86a92789af1.jpg)

**Comment by cartag** [comment]
Corrected in next release
