### ISSUE TITLE
Order - Cities of Sigmar.catz : Dreadlord on Black Dragon has outdated ability: "Exile Blades" still on profile

### ISSUE THREAD

**Issue by Veziik** [BSData/warhammer-age-of-sigmar#1245]
The Profile for a Dreadlord on a Black Dragon still has the old "Exile Blades" ability for rerolling hit rolls of 1 when using 2 Exile blades, and this ability appears even when the unit has no exile blades equipped. 

As an aside, the newer "Pair of Exile Blades" ability is working as intended, only the outdated rule needs to be removed.

**Comment by cartag** [comment]
Corrected in next release.
