### ISSUE TITLE
Artefact selection is missing from all Heroes

### ISSUE THREAD

**Issue by RedBishop777** [BSData/warhammer-age-of-sigmar#1263]
Heroes with the DAEMON and those with ROTBRINGER keyword should have access to "Daemonic Boons" and "Artefacts of Contagion" selections respectively from the Nurgle Allegiance. It's seems to be currently missing and applies to *all* heroes.

See with Harbinger of Decay for a good example (He should have access to all 3 selections but only has one). 

Cheers!

**Comment by cartag** [comment]
Corrected in next release
