### ISSUE TITLE
Skaeth's Wild Hunt not appearing

### ISSUE THREAD

**Issue by nczempin** [BSData/warhammer-age-of-sigmar#1289]
https://www.games-workshop.com/resources/PDF/AoS_Warscrolls//aos_skaeths_wild_hunt_en.pdf

I can see that there is some data in the files, but the unit is not showing up as a selectable choice.

![image](https://user-images.githubusercontent.com/1781405/75598233-7efa0780-5a9a-11ea-90b0-2c6bebc60cad.png)

![image](https://user-images.githubusercontent.com/1781405/75598259-a650d480-5a9a-11ea-8609-6017355070a3.png)

**Comment by nczempin** [comment]
This is what it looks like in the Roster editor:

![image](https://user-images.githubusercontent.com/1781405/75598298-f92a8c00-5a9a-11ea-9907-eae02bbce387.png)

**Comment by nczempin** [comment]
From what I've gathered, it looks like something like this is missing from Order - Sylvaneth - Data.cat:

  `<entryLink id="dca9-5428-8f3e-e656" name="Skaeth&apos;s Wild Hunt" hidden="false" collective="false" import="true" targetId="02f2-388c-b66b-5159" type="selectionEntry"/>
`

**Comment by nczempin** [comment]
Seems to have done the trick:

![image](https://user-images.githubusercontent.com/1781405/75598795-d306eb00-5a9e-11ea-9ea0-a5d9acd47770.png)

**Comment by cartag** [comment]
It's not missing from the data file, it's missing from the Sylvaneth file (non-data). Looks like it didn't get updated when the unit was added.

**Comment by UrsinePatriarch** [comment]
Yeah, that was my mistake; forgot Sylvaneth had a separate file that I needed to add an entry to.

On it now.

**Comment by nczempin** [comment]
yes, the reference is missing from the main file, the actual content is in the referenced data file

**Comment by cartag** [comment]
Corrected in next release
