### ISSUE TITLE
Gloomspite Gitz - Rippa's Snarlfangs: Missing?

### ISSUE THREAD

**Issue by nczempin** [BSData/warhammer-age-of-sigmar#1292]
https://www.games-workshop.com/resources/PDF/AoS_Warscrolls//aos_rippas_snarlfangs_en.pdf

I assume it's not in the General's Handbook 2019 because the Snarlfangs came out after the print deadline?

And judging by the keywords, DESTRUCTION, GROT, GLOOMSPITE GITZ, RIPPA’S SNARLFANGS, it should be playable out of the box in a Gloomspite Gitz army?

**Comment by UrsinePatriarch** [comment]
These'll be added in the next release.
