### ISSUE TITLE
Orruk Warclans: Ardboyz should be Battleline for Ironjawz

### ISSUE THREAD

**Issue by nczempin** [BSData/warhammer-age-of-sigmar#1293]
![image](https://user-images.githubusercontent.com/1781405/75627097-a00f4500-5bcd-11ea-9133-9bf4a33b6bf9.png)
Orruk Ardboys are not set to Battleline despite Ironjawz Allegiance.

**Comment by nczempin** [comment]
Another strange thing:

When I then add a unit of Ardboys, the Battleline unit options duplicate.

This phenomenon doesn't go away when removing the ardboys, but it does go away when changing the allegiance.

Not sure if it's okay to report it in here or if I should create a separate issue.

**Comment by UrsinePatriarch** [comment]
The duplication issue is actually a Battlescribe (the program) issue that we, the data maintainers, have no control over, unfortunately.

As for the Battleline problem, I'll look into it.

**Comment by nczempin** [comment]
why does the duplication only manifest in this particular army?

**Comment by cartag** [comment]
It's not only that particular army, you can rest assured. Anything that causes some units to switch to Battleline is subject to it.

**Comment by DrTobogganMD** [comment]
The logic on the unit is also incorrect. I've fixed this so that the unit shows properly as battleline and other. When in battleline it requires 10 models per battletome.
