### ISSUE TITLE
[Disciples of Tzeentch] Slave to Darkness endless spells

### ISSUE THREAD

**Issue by simakover** [BSData/warhammer-age-of-sigmar#1299]
Hello, may be add Slave to Darkness Endless spells for Tzeentch faction? Gaunt summoner have a slave to darkness keyword so he can cast this endlesses

**Comment by cartag** [comment]
Added to next release.

**Comment by cartag** [comment]
It's set up so they only appear if you have a Gaunt Summoner in your list.  Otherwise I'd get loads of bug reports on it.
