### ISSUE TITLE
Kharadron Overlords Data

### ISSUE THREAD

**Issue by classic4u** [BSData/warhammer-age-of-sigmar#130]
I noticed the Kharadron Overlords are not in the current data set. 

Is this being worked on?  If not, I'd be happy to take a stab at adding their warscrolls myself.

Cheers!

**Comment by StealthKnightSteg** [comment]
It's not yet (I think) see also #124

**Comment by alphalas** [comment]
Hasn't been added because the cats all need to be refactored for BS2.01 to take advantage of categories

**Comment by alphalas** [comment]
Talk to @flakpanda on gitter

**Comment by alphalas** [comment]
@stealthknightsteg before you commit anything else please get on gitter https://gitter.im/BSData/warhammer-age-of-sigmar
