### ISSUE TITLE
Missing:  Nurgle Warscroll Battalions

### ISSUE THREAD

**Issue by MadCatCarter** [BSData/warhammer-age-of-sigmar#1300]
I can't find any of the warscroll battalions when building a nurgle deamons list.  The new stuff from WotEverchosen are there, but the old WBs are gone

**Comment by cartag** [comment]
They're all still there... are you bringing them as Nurgle or as the newer all daemon faction? They won't appear under the latter.
![image](https://user-images.githubusercontent.com/4388344/76260543-a2048400-621d-11ea-8a1d-0fc6b36289f7.png)

**Comment by MadCatCarter** [comment]
Hi Cartag,

I’ve figured out what I was doing wrong was choosing a meeting engagement in the roster selection, which provided me the options you can see in my screenshot.  Switching to pitched battle fixed it.  Thanks!

[cid:image002.png@01D5F662.BE700D20]



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by cartag** [comment]
Glad you found a resolution!
