### ISSUE TITLE
Seraphon Release

### ISSUE THREAD

**Issue by CausesChaos** [BSData/warhammer-age-of-sigmar#1305]
New seraphon release.
Data requires updating.

**Comment by cartag** [comment]
Thank you for the heads up, we had NO IDEA it had come out! So sorry to have not had it updated and released the direct second the book dropped. There will be a release today. Thank you for disproving my point that AoS gamers aren't as impatient as 40k players.

**Comment by CausesChaos** [comment]
Hahaha,

No problem at all. :D

**Comment by cartag** [comment]
A release was just pushed. It should be live within 8 hours, depending on how quickly appspot updates.

**Comment by cartag** [comment]
Sorry for being a dick. We're all volunteers here but we keep up on GW releases, as in we know when things come out. Getting what appears as a command instead of a request in inquiry when it will be done kinda grates on the nerves, if you can see where I'm coming from.

**Comment by CausesChaos** [comment]
I appreciate that. I didnt take into account you may get impatient assholes commenting making demands.

Wasnt my intention and perhaps I could have worded it better.

Wasn't my intention to come across as a demand.
