### ISSUE TITLE
Bug: Cities of Sigmar - Stormcaste Eternal Heroes

### ISSUE THREAD

**Issue by tatoren** [BSData/warhammer-age-of-sigmar#1311]
Currently only Cities of Sigmar units can be the General's Adjutant instead of any Hero in the army with less than 5 wounds.

**Comment by cartag** [comment]
This is an unfortunate side effect of how difficult it has been to add SCE, Sylvaneth, and KO to the CoS file. I'm trying to think of a way to make this work, but for the time being it's likely not going to be implemented fully.

**Comment by cartag** [comment]
Implemented in latest release.
