### ISSUE TITLE
Missing data: Neferata and Direwolves

### ISSUE THREAD

**Issue by Nezkrul** [BSData/warhammer-age-of-sigmar#1313]
Neferata’s data doesnt list her mount’s weapons, attacks, rend, or damage.

Direwolf units aren’t getting the max unit discount on their points

**Comment by UrsinePatriarch** [comment]
Far as I can tell, Dire Wolves don't get any discount, my dude; if you can prove otherwise, I'll update it, though.

Neferata's actually borked, though, haha, so you're 100% right there and I'll fix it with the next release.

**Comment by DrTobogganMD** [comment]
Legions of Nagash updated Dire Wolves to get a discount at max. Fixing now along with Nef.
