### ISSUE TITLE
Seraphon Battalion for sunclaw templehost/starhost and Saurus Oldblood on Carnosaur

### ISSUE THREAD

**Issue by Garvlok** [BSData/warhammer-age-of-sigmar#1314]
Theres a discussion going on i lustria and a point has been brought up which is vaild.

the saurus old blood on carnosaur is able to be a part of the battalion because of this stipulation of the rules in making a battalion on page 240 of the core rules.

![Battalion Stipulation](https://user-images.githubusercontent.com/28663956/77918848-726bf900-726a-11ea-96da-41a3a3ef171f.jpg)

Its the same reason why kurnoth hunters are able to be a part of the free spirits battalion as there is no kurnoth hunters warscroll. there is the kurnoth hunter with their weapons warscrolls.

**Comment by DrTobogganMD** [comment]
Makes sense to me. I’ll fix tonight.

**Comment by Garvlok** [comment]
> Makes sense to me. I’ll fix tonight.

Awesome. One more thing i saw, saurus knights currently in battlescribe have 4 attacks with warspears when they should only have 2. 

Also they hit on 4+ not 3+ with warspears
