### ISSUE TITLE
Seraphon : Skinks : Unit weapons : Boltspitter, Celestite Dagger and Star-buckler

### ISSUE THREAD

**Issue by trashmoutarde** [BSData/warhammer-age-of-sigmar#1315]
Seraphon : Skinks : Unit weapons : the "Boltspitter, Celestite Dagger and Star-buckler" weapon option contains the specs for the "moonstone club" instead of the specs for the "Boltspitter"

**Comment by DrTobogganMD** [comment]
Got it :D I have a PR in to fix it now.
