### ISSUE TITLE
Behemoth issue - Seraphon

### ISSUE THREAD

**Issue by perplexiti** [BSData/warhammer-age-of-sigmar#132]
When doing a vanguard list it's showing invalid if you pick any behemoth models, should be 0-2. 

![image](https://user-images.githubusercontent.com/29674091/27507878-6838e7e4-592d-11e7-8743-c6abd0152fb8.png)

**Comment by perplexiti** [comment]
Sorry, this is on Android and Windows PC.

**Comment by Mad-Spy** [comment]
Closing in anticipation of re-release
