### ISSUE TITLE
Stabbas and Shootas as Allies

### ISSUE THREAD

**Issue by crownedzoidberg** [BSData/warhammer-age-of-sigmar#1332]
Problem occuring on Android and Windows Client under the newest and previous versions.

Army Chosen: Orruk Warclans
Allies: Gloomspite Gitz

If I chose Gloomspite Gitz as allies, the troop choice of Stabbas and Shootas are not listed. I haven't found any rulings of those units not being allowed - they are simply missing in the list.

**Comment by rweyrauch** [comment]
Stabbas and shootas should be listed under 'Other' when allied into another force.   These units are indeed missing.
