### ISSUE TITLE
Seraphon as Allies, Battline units not available

### ISSUE THREAD

**Issue by StuxAlpha** [BSData/warhammer-age-of-sigmar#1334]
I'm aware this is a common issue across several catalogues, though some have been fixed.

When using Seraphon as allies, normal Seraphon Battleline units should be available in the Other category. Currently they are not available at all.

**Comment by DrTobogganMD** [comment]
Correct me if i'm wrong, but that's just Saurus Warriors, right?

**Comment by StuxAlpha** [comment]
Just checked and you're quite right, just Saurus Warriors not appearing. Skinks are present and correct.

Apologies, should have checked more thoroughly.

**Comment by DrTobogganMD** [comment]
No you're fine - it's still something I am fixing, I just want to be sure!

**Comment by DrTobogganMD** [comment]
We also haven't done a release in like a month ... so I just pushed one. Fixed data should be on appspot by tomorrow (or today, we'll see if Appspot forgets how to exist again)

**Comment by StuxAlpha** [comment]
Fantastic, thanks!
