### ISSUE TITLE
Forgeworld Troggoth Hag No Artefact

### ISSUE THREAD

**Issue by Baxford91** [BSData/warhammer-age-of-sigmar#1347]
Hi there,
Just leaving a little issue that the Troggoth Hag in BattleScribe app, can not take/pick an Artefact for some reason. Hope this helps! Thank you very much for your time and this awesome script for us to play more simply!

**Comment by DrTobogganMD** [comment]
You can only take artefacts on a troggoth hag in a Destruction Allegiance. The unit does not have the required keywords for Gloomspite Gitz artefacts.
