### ISSUE TITLE
Beasts of Chaos - Old points values 

### ISSUE THREAD

**Issue by Oak7603** [BSData/warhammer-age-of-sigmar#1352]
Hi, quite a few BoC points are out of date and don't use the GHB 2019 ones:

Ghorgon should be 200
Cygor should be 180
Bullgors should be 160
Razorgors should be 50
Tzaangor enlightened on discs should be 160
Doombull should be 120
Tzaangor Shamen should be 160
Chimera should be 240
Jabberslythe should be 160

**Comment by cartag** [comment]
Points are correct as of Dec 19 FAQ. Check errata on GW community page.

**Comment by Oak7603** [comment]
Ah I see. That explains the Ghorgon, Cygor, Bullgors, Doombull and Razorgors but the others still seem to be wrong according to that FAQ and I can't see the Tzeentch points changes in their errata either.

**Comment by cartag** [comment]
Tzeentchian units were updated with the new Tzeentch book that came out Dec19/Jan20 timeframe
