### ISSUE TITLE
Beasts of Chaos : Wrong Costs

### ISSUE THREAD

**Issue by Fastad** [BSData/warhammer-age-of-sigmar#1364]
Hi.

Some of the BOC creatures costs are not up to date.

(Doombull, Bullgors, Gorghon, Cygor, etc..)

Thanks for tout good work !

**Comment by cartag** [comment]
Check the December FAQ, it updated points costs.

**Comment by cartag** [comment]
Unless you can point to ones that are definitely outdated given the Dec errata. I've recently checked and know all the ones you mentioned were updated.
