### ISSUE TITLE
Incorrect unit sizes for Grimghast Reapers

### ISSUE THREAD

**Issue by monyarm** [BSData/warhammer-age-of-sigmar#1370]
The Grimghast Reapers (Death - Nighthaunt) are 10 units by default yes, but i've got the warscroll infront of me, and it say that "A unit of Grimghast Reapers can have any number of models"

However, in Battlescribe i can only add them in multiples of 10.

**Comment by DrTobogganMD** [comment]
Battlescribe supports Matched Play for restrictions. You'll want to consult the GHB for the minimum models in a unit.

**Comment by cartag** [comment]
For further info, most (if not all) warscrolls of multiple model units say the same thing (can have any number of models).

**Comment by OftKilted** [comment]
You can have any number, but you pay in blocks of 10. So, if you have 11 models. You pay for 20 models.
