### ISSUE TITLE
Bug report : Points cost

### ISSUE THREAD

**Issue by Volkyrias** [BSData/warhammer-age-of-sigmar#1372]
Hello, 
Lady Olinder is not worth 200 points but rather 240 points in my death battletome and Grimghast Reapers x10 == 140 points not 160 points 
I'm sorry about the translation, i'm french. 🙃
Thanks !
![15936557310437873374695014810593](https://user-images.githubusercontent.com/67720556/86308522-c72c6080-bc19-11ea-846f-d59b0db73f50.jpg)

**Comment by cartag** [comment]
Points were updated in the Dec 2019 FAQ/Errata.

**Comment by cartag** [comment]
https://www.warhammer-community.com/wp-content/uploads/2019/07/e2513c4c.pdf
