### ISSUE TITLE
Disciples of Tzeentch Changeling artefacts

### ISSUE THREAD

**Issue by Anggul** [BSData/warhammer-age-of-sigmar#1374]
Hi there,

The Changeling in Disciples of Tzeentch doesn't have access to artefacts, could this be fixed please?

Thanks much

**Comment by cartag** [comment]
The Changeling is a unique/named character and as such does not receive artefacts or command traits.

**Comment by Anggul** [comment]
Oops, I meant Curseling! Too many -lings!

It's Curselings that don't have artefact selection when they should.

**Comment by cartag** [comment]
Fixed in next release.
