### ISSUE TITLE
[Anon] Bug report: Order - Lethisian Army.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#1380]
**File:** Order - Lethisian Army.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Army file cannot be used. I possible to create New army. This is also the case in Windows version 
Keep up the good work, u Guys and Girls are awesome

**Comment by cartag** [comment]
Corrected in next release.
