### ISSUE TITLE
Ossiarch bonereapers weapons and abilities of the same name but in different warscrolls

### ISSUE THREAD

**Issue by LoudLoveTaps** [BSData/warhammer-age-of-sigmar#1397]
Katakros
deadly combination - if the unmodified hit roll for an attack made with the shield immortis is 6, that attack inflicts 2 mortal wounds on the target in addition to any normal damage.

Immortis Guard
Nadarite battleshields have 2 attacks.

Kavalos deathriders
nadarite blades and shields/spears have 3 attacks. Nadarite weapons ability after the last sentence add - For attacks made with Nadarite Spears, 2 hits are scored on a 5+ instead of 6 if this unit made a charge move in the same turn.

**Comment by cartag** [comment]
Corrected in next release
