### ISSUE TITLE
Join Request

### ISSUE THREAD

**Issue by Kohato** [BSData/warhammer-age-of-sigmar#14]
Hi! I'm the Space Marines and Space Wolves maintainer on the 40k data repo and would love to join here too. With BS2 coming out I think I have some good ideas on how to properly implement the 3 point levels of matched play as well as their battlefield roles (being dual).  I'd also be glad to maintain Seraphon if nobody else is (Go go Lizardmen!)

**Comment by amis92** [comment]
Okay so I think you should actually already have write access to this repo. Unless, of course, what you're asking is rather some consent from guys over here. I guess though there is not much activity here... (last commit September 2015 :/ )

**Comment by Kohato** [comment]
Huh, so I do - No idea why I asked for access then. Hah. Thanks Amis.
