### ISSUE TITLE
[Anon] Bug report: Destruction - Greenskinz.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#1416]
**File:** Destruction - Greenskinz.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Destruction - Bonesplitterz has disappeared from Age of Sigmar, are you the right person to fix this?

**Comment by rweyrauch** [comment]
Bonesplitterz have been merged into the Orruk Warclans catalog.   The Bonesplitterz allegiance is available for selection.

**Comment by rweyrauch** [comment]
Working as expected.
