### ISSUE TITLE
Cities of sigmar Anvilguard

### ISSUE THREAD

**Issue by SamTheJ** [BSData/warhammer-age-of-sigmar#1422]
Unless I'm missing something I don't see any ability to select illicit dealings.

**Comment by rweyrauch** [comment]
The Illicit Dealings is shown as Battalion Abilities.   The ability to select one of the dealings and the logic to adjust artefacts, etc has not been implemented.

**Comment by asbcoder** [comment]
Hi. Do you know when this feature will be implemented?

**Comment by rweyrauch** [comment]
I will re-evaluate the effort.
