### ISSUE TITLE
 Age of Sigmar General's Handbook 2017

### ISSUE THREAD

**Issue by Horotius** [BSData/warhammer-age-of-sigmar#143]
Hey there, I was wondering if the AoS file could be updated to the new point costs of everything from the generals handbook 2017. I also noticed that a new army (Kharadron Overlords) is not within the order list as well.

Also if there was anyway to add the new command traits/artifacts for the factions that would be cool as well (due to some got new allegiance abilities, command traits, and artifacts.

Thanks!

**Comment by Mad-Spy** [comment]
Closing in anticipation of re-release
