### ISSUE TITLE
Bug report: skaven allegiances missing 

### ISSUE THREAD

**Issue by Spudmonk3y** [BSData/warhammer-age-of-sigmar#1432]
Skaven appear to be missing their allegiance abilities, the only options are skaventide and chaos.

**Comment by cartag** [comment]
Skaven doesn't have sub factions that you choose like other factions do.

**Comment by Spudmonk3y** [comment]
What? Yes they do, the clans on page 67 and 68 of the battletome.

**Comment by Spudmonk3y** [comment]
Not only do they have allegiance abilities but what clan you choose affects your battleline options

**Comment by cartag** [comment]
Those are ALL available to anybody who chooses the Skaventide allegiance. Those are not subfactions that you must choose between. Skaven is fundamentally set up differently than other factions by GW. If you want those units to be Battleline you have to abide by the rules as they are set forth in the battletome; having a General of a certain clan and if your units are all of the same keyword.

**Comment by OftKilted** [comment]
The battle traits on p.67/68 are for the Skaventide Allegiance as referenced on p.66. They are just specific to the particular clan heroes.
