### ISSUE TITLE
Units in a battalion don't count for allegiance

### ISSUE THREAD

**Issue by ereinion** [BSData/warhammer-age-of-sigmar#1442]
Tested with Cities of Sigmar with an Allegiance of 'Tempest's Eye'. Add 4 Phoenix guard in the other category and then add 1 Arkanaut Company.. Should not have an error about too many Kharadon Overlord units.
Then add a battalion of aetherguard windrunners and fill it with 1 leader and 3 pistoliers. 
Go back to main army and add another Arkanaut Company unit and it will have error of '1 too many units of Kharadon Overlords, maximum of 1' when the maximum should be 2 (the battalion units should be of the type 'Tempests Eye'.

**Comment by rweyrauch** [comment]
Unable to reproduce using v26 of the Cities of Sigmar catalog.

**Comment by cartag** [comment]
This is actually a technical limitation with Battlescribe. I've not come up with a work around other than to say ignore those particular validation errors.
