### ISSUE TITLE
Ogor Mawtribe Meatfist Mawtribe

### ISSUE THREAD

**Issue by dNAUTILUS** [BSData/warhammer-age-of-sigmar#1445]
The artefact for Meatfist Mawtribe(Gut-plate of Ghur) appears in the command trait after you select your general while the command trait( Food for thought) appears as an artefact. Please make amendments! Thank you!!

**Comment by dNAUTILUS** [comment]
It still isnt solved thou

**Comment by rweyrauch** [comment]
It will be available when the next release of the catalogs is tagged and made public.

**Comment by dNAUTILUS** [comment]
Okay! Thank you so much!
