### ISSUE TITLE
Bug Report: Seraphon Battalion Options Missing

### ISSUE THREAD

**Issue by TacoAmerican** [BSData/warhammer-age-of-sigmar#1461]
Currently Using BS Ver: 2.03.21
AOS Ver: 61
Order-Seraphon v50

Warscrolls/Warscroll battalions Completely missing from the selection.

Troubleshooting:
Deleted all data files and renewed, reinstalled BS just to be sure. Even went into CATZ file to make sure rules were present (it is).

Thanks in advance!

**Comment by rweyrauch** [comment]
Seraphon battalions are only visible after selecting Seraphon Army Type (Coalesced or Starbourne) from Allegiance: Seraphon.

**Comment by TacoAmerican** [comment]
Swear to god that didnt work yesterday but thank you!

**Comment by rweyrauch** [comment]
No worries.
