### ISSUE TITLE
White Dwarf - Tome Celestial Battalions

### ISSUE THREAD

**Issue by rweyrauch** [BSData/warhammer-age-of-sigmar#1473]
Per the GHB2020 October 2020 Designers' Commentary battalion defined in the White Dwarf Tome Celestial articles are valid for matched play.

- [x] The Hammerhands (WD Feb 2019)
- [x] Steel Souls (WD Apr 2019)
- [x] The Vostarg Lodge (WD Jun 2019)
- [x] The Sempiternals (WD Aug 2019)
- [x] The Host of Syll'Esske (WD Oct 2019)
- [x] The Emerald Host (WD Dec 2019)
- [x] Ironsunz (WD Feb 2020)
- [x] Vokmortian's Tithe Legion (WD Apr 2020)
- [x] The Jaws of Mork (WD #455)

**Comment by cartag** [comment]
Ironsunz is already done

**Comment by rweyrauch** [comment]
Merged #1475 and #1474.
