### ISSUE TITLE
[Anon] Bug report: Chaos - Skaven - Data.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#1487]
**File:** Chaos - Skaven - Data.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Hey guys, while editing a Moulder-Army, I couldn't get the Stormfiends into the "other units" without kicking out the rat ogres from the battleline. I think this is because the stormfiends are missing the "clans moulder" category in the roster editor. Could you guys update that so the Stormfiends have both the "clans scryre" and "clans moulder" category and are able to be in a Moulder-Army?

**Comment by cartag** [comment]
Corrected in next release.
