### ISSUE TITLE
Legions of Grief 

### ISSUE THREAD

**Issue by bbermanbates** [BSData/warhammer-age-of-sigmar#1499]
BattleScribe Version 2.03.15 on iPhone
Age of Sigmar v2.2.9
Death: Legions of Nagash and Nighthaunt v47 
*pitched battle*

Allegiance: Legion of Grief is not shown as selectable under allegiance choices. See image for selectable choices. 

![B8140BBF-D3D2-4554-A20E-EBEEBD7F5AF5](https://user-images.githubusercontent.com/34081362/97661799-b5ce5600-1a4b-11eb-9450-3c55d18fb4f8.jpeg)

**Comment by cartag** [comment]
Update your data, it's in there. 
![image](https://user-images.githubusercontent.com/4388344/97729660-8bef5080-1a98-11eb-88eb-d24daaa64307.png)

**Comment by bbermanbates** [comment]
@cartag tha is for following up. Wasn’t offered on update thought I had done that by removing the data. Selected the delete all data under settings, then re acquired everything. And poof it’s working. 

Again thank you for following up. You made my day by being helpful!
