### ISSUE TITLE
Kharadron Overlords: Endrinmaster heals

### ISSUE THREAD

**Issue by srjek** [BSData/warhammer-age-of-sigmar#1508]
I've noticed the "Endrinmaster" ability on "Endrinmaster with Endrinharness" as listed in battlescribe heals for 3 points, but I can't find any source that agree. It appears that the guaranteed 3 heal is limited to "Endrinmaster with Dirigible Suit", with Endrinharness getting a 1d3 heal.

Since both units share the same ability in the catalogue file, and the ability appears to have been [last updated for 2E](https://github.com/BSData/warhammer-age-of-sigmar/blame/2e2cb0b55025a3297f62c215dd7e64d35adcd38a/Order%20-%20Kharadron%20Overlords%20-%20Data.cat#L4732), I suspect it was updated for both by accident.

**Comment by cartag** [comment]
Resolved in next release.
