### ISSUE TITLE
Join Request

### ISSUE THREAD

**Issue by bfleeson** [BSData/warhammer-age-of-sigmar#151]
Have time and good knowledge of XML and AoS. 
Let me know if you want help.

**Comment by amis92** [comment]
I can add you, but it seems the repo is rather dead so you'll be on your own. Are you sure?

**Comment by flakpanda** [comment]
@OftKilted has been working on this, to what capacity i am not sure, and i am here in limited help and can answer questions.

**Comment by rweyrauch** [comment]
I would also like to contribute to this project.

**Comment by Mad-Spy** [comment]
Are you still interested in helping out? We've managed to get a few people together to try and get the data files up-to-date and any assistance you can give would be a big help.

**Comment by rweyrauch** [comment]
Yes.  I am interested in helping to update the AoS database.

-rick

**Comment by Mad-Spy** [comment]
@rweyrauch, please come and join us on Gitter, https://gitter.im/BSData/warhammer-age-of-sigmar.
