### ISSUE TITLE
Bug report: Leaders in Spearhead/Rearguard Meeting Engagements cannot be given upgrades

### ISSUE THREAD

**Issue by plavski** [BSData/warhammer-age-of-sigmar#1518]
BattleScribe Version 2.03.21 on Desktop
Age of Sigmar v2.2.11
Order: Seraphon: v55

When assigning Lord Kroak to a leader role in a Spearhead or Rearguard in a Meeting Engagements list, you are unable to select a spell for him.

![image](https://user-images.githubusercontent.com/15157275/98463817-2dbc1f00-21b6-11eb-864d-901c1580bbd6.png)

When assigned in the Main Body, you can select from the SERAPHON Spell Lore.

![image](https://user-images.githubusercontent.com/15157275/98463844-58a67300-21b6-11eb-8356-5062019f0cf8.png)

Similarly, when assigning a General in a Spearhead/Rearguard, you cannot apply upgrades:

![image](https://user-images.githubusercontent.com/15157275/98463825-39a7e100-21b6-11eb-8e12-f215fc3a6d51.png)

When selected in the Main Body, you can apply upgrades:

![image](https://user-images.githubusercontent.com/15157275/98463833-475d6680-21b6-11eb-9687-d44499a6a006.png)

**Comment by cartag** [comment]
1) Lord Kroak given artefacts and command trait choices
2) Corrected artefacts and traits showing in non-main body ME lists. 

Corrected in next release.

**Comment by plavski** [comment]
The problem with leaders not having artefacts when put in rearguard/spearhead also happens in at least KO and Fyreslayers. Seems to be fine in Sylvaneth though.
