### ISSUE TITLE
seraphon

### ISSUE THREAD

**Issue by Glklas** [BSData/warhammer-age-of-sigmar#1522]
the seraphon don't have the subfactors of dracothion's tail, fangs of sotek, Koatl's Claw, and The Thunder Lizard

**Comment by cartag** [comment]
You need to pick if your roster is Coalesced or Starborne first. 
![image](https://user-images.githubusercontent.com/4388344/98567136-d2009d00-226c-11eb-99f8-68e7054a0ec1.png)
