### ISSUE TITLE
Faultless Blades Command Trait Issue

### ISSUE THREAD

**Issue by acovarru91** [BSData/warhammer-age-of-sigmar#1540]
If selecting two command traits for your general and using the Faultless Blades host, Battlescribe will tell you there is an error and two command traits must be selected

**Comment by acovarru91** [comment]
Also Slaanesh Invaders hosts are not able to be given artifacts and selecting them to be a general removes their eligibility to be given command traits

**Comment by cartag** [comment]
Both issues resolved.
