### ISSUE TITLE
Order: Update Sylvaneth points

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#155]
**File:** Order.catz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:** Sylvaneth points are not correct with the General's Handbook 2017. Battlescribe shows me the old points (ex. Dryads are 100 now, where Battlescribe shows me them at the old 120 value). All the points are old.

**Comment by Cupropituvanso** [comment]
I will correct it during the 2017er update

**Comment by OftKilted** [comment]
Currently the aos Battlescribe data files are out of date and being reworked. This will be addressed as part of the current rebuild.

**Comment by OftKilted** [comment]
Flagging for issue review as Sylvaneth have been submitted to the 2.0 branch

**Comment by OftKilted** [comment]
Closing as this was resolved by #184
