### ISSUE TITLE
Allies fix among all factions

### ISSUE THREAD

**Issue by cartag** [BSData/warhammer-age-of-sigmar#1551]
The following needs added to every faction's file to make sure they don't give errors when adding Allies to your army. I'll start with Chaos if anybody else wants to start with another GA. 
![image](https://user-images.githubusercontent.com/4388344/99613846-9173f280-29d5-11eb-803f-446ba690af8d.png)

**Comment by rweyrauch** [comment]
I'll take care of order.

**Comment by cartag** [comment]
Working on Death now

**Comment by rweyrauch** [comment]
Working on Destruction now.
