### ISSUE TITLE
Bug Report: Slaves to Darkness - Chaos Chariots are grouped and apply a discount

### ISSUE THREAD

**Issue by plavski** [BSData/warhammer-age-of-sigmar#1557]
Battlescribe: v2.03.21
Slaves to Darkness: v33
Age of Sigmar: 2.2.14

Adding a Chaos Chariots unit allows you to add sub units to the group. When three are added, the 120 point value decreases to 70.

![image](https://user-images.githubusercontent.com/15157275/99733813-a9bd3d80-2ab9-11eb-91bc-7b8d5c329e38.png)

**Comment by cartag** [comment]
Price reduction solved. Will be in next release.
