### ISSUE TITLE
Stormcast Feedback

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/warhammer-age-of-sigmar#156]
- Lots of units need weapon Shared Entries created for their weapons and the weapon and weapon-related profiles moved to these SEs. 
- You can lose the "Description" rule on all the units. It's often incorrect anyway because the Pitched battle unit sizes aren't necessarily the same as the book description.
- Drakesworn Templar needs weapon choice implemented and hidden switch removed.
- Knight-Azyros is missing his Starblade.
- Knight-Venator will need a suffix  (melee/missile) on the Star-Eagle's claws or BS will only display one of them.
- Knight-Vexillor standard profiles should be moved to the relevant standard SE.

**Comment by rweyrauch** [comment]
Issues resolved in Order - Stormcast Eternals catalog.
