### ISSUE TITLE
Legion of Chaos Ascendant List Issues

### ISSUE THREAD

**Issue by acovarru91** [BSData/warhammer-age-of-sigmar#1568]
You're not able to currently add in Tzeentch Endless Spells. Also, when selecting the Legion of the First Prince subfaction, you're not able to give your casters the spell "the masters command". This is only an issue because it gives you an alert that a spell needs to be chosen.

**Comment by cartag** [comment]
Which caster are you trying to give the spell "The Masters Command" to? There shouldn't ever be an alert that it is needed because the spell itself is added at the subfaction level; if you select Legion of the First Prince, it auto adds it to your roster.

**Comment by acovarru91** [comment]
It's Be'lakor specifically. It says he requires a selection from "Lore of the Damned' now that i play around with it some more, it seems like this is only an issue with Be'lakor

**Comment by cartag** [comment]
Added Tzeentch Endless spells
Corrected StD spell lores to not show when not StD allegiance

**Comment by cartag** [comment]
Fixed in next release.
