### ISSUE TITLE
Knight-Incantor Spell Lore Issue

### ISSUE THREAD

**Issue by acovarru91** [BSData/warhammer-age-of-sigmar#1571]
If selecting a Stormkeep and allying in your Cities units, the Knight Incantor is being flagged as requiring a selection from Lore of the Deepwood.

**Comment by cartag** [comment]
Unable to replicate. Can you list the steps to recreate the problem?

**Comment by acovarru91** [comment]
Create SCE Army, add in CoS under allied forces, add Knight Incantor as leader. Alert to select Lore of Deepwood appears. Also Sisters of the Thorn do not have a spell lore choice.

**Comment by cartag** [comment]
That is really strange. If I add in the CoS allies it gives the error, but if I don't add the allies it doesn't. I'll get it updated.
