### ISSUE TITLE
Tzaangor Shaman Command Trait Issue

### ISSUE THREAD

**Issue by acovarru91** [BSData/warhammer-age-of-sigmar#1577]
If selecting a Tzaangor Shaman as your general in a Tzeentch allegiance army, artefacts come up instead of command traits. This issue does not come up for other generals (not tested with every leader option)

**Comment by cartag** [comment]
Issue affected only units in Beasts of Chaos file who were trying to access either Tzeentch or Slaanesh command traits, linked to artefacts instead. Resolved in next release.
