### ISSUE TITLE
Battleline Issue in Stormkeeps

### ISSUE THREAD

**Issue by acovarru91** [BSData/warhammer-age-of-sigmar#1586]
Unsure if this is possible to fix, but when adding in CoS units as part of a Stormkeep list, Battleline units are put under "other" not battleline. Minor issue, as not having enough battleline is not happening.

**Comment by rweyrauch** [comment]
Are you allying in the CoS into a Stormcast army?   Allied units are never battleline.

**Comment by acovarru91** [comment]
Well this is for a Stormkeep, where you can take CoS units and they do count as Battleline

**Comment by cartag** [comment]
Because the other option was to link everything from CoS into SCE which would make their lists even bigger than they already are. I'm trying to come up with a good solution to this.

**Comment by acovarru91** [comment]
Yeah it's a minor issue that i know is difficult to find an elegant solution to. I'm not sure this was even worth mentioning but I've tried to report every issue I've encountered.

**Comment by cartag** [comment]
I think the inevitable resolution will be breaking CoS units into a library like SCE has been and link absolutely everything into SCE that only show if Stormkeep is checked.

**Comment by rweyrauch** [comment]
> I think the inevitable resolution will be breaking CoS units into a library like SCE has been and link absolutely everything into SCE that only show if Stormkeep is checked.

Yuck.  But I think you are right.

**Comment by rweyrauch** [comment]
Has this issue been addressed by the Coalition work for AoS3?

**Comment by cartag** [comment]
No, it will need set up the same way the other factions are for the Cities coalition options. Basically the reverse of how the SCE are set up.

**Comment by cartag** [comment]
No longer applicable with new SCE book.
