### ISSUE TITLE
Bretonnia data missing? 

### ISSUE THREAD

**Issue by jawsofhana** [BSData/warhammer-age-of-sigmar#159]
The data from the compendium lists in the General's Handbook are all missing from the files.

**Comment by OftKilted** [comment]
There is no Bretonian data in the GHB 2017.

Are you referencing the limited support in the current Compendium pdf release from GW?

https://www.games-workshop.com/resources/PDF/AoS_Compendiums/warhammer-aos-bretonnia-en.pdf

Please be aware that current AoS files are being rebuilt.

**Comment by jawsofhana** [comment]
Yes. As with all GW codexes, and indexes, the old stuff is not outdated unless replaced? So anything in the 2016 book, that did not get points updates in the 2017 version should still be legal in matched play with those rules? Definitely in open play. Alternately, there could be an option to enable compendium lists as a choice? Like the 40k Forgeworld stuff.

**Comment by jawsofhana** [comment]
If you need page/image references, I am happy to provide. :)

**Comment by OftKilted** [comment]
The original release of the Bretonnia compendium was replaced by the 2017 Bretonnia Compendium release. There are points available in the updated release. But there are no Battalions, and all named characters were removed, and the Bretonnia warscrolls were updated with new keywords.  Some units were removed and many abilities redone.

In short, anything that didn't get points in the 2017 GHB (or the updated compendiums) is no longer valid for matched play, unless it was updated after the 2017 GHB. Per the GHB _"...This means that the profiles printed here take precedence over any profiles with an earlier publication date, and also take precedence over profiles that have no publication date at all."_ (See p. 86 of the 2017 GHB 
"Updated Profiles August 2017")

**Comment by jawsofhana** [comment]
I am afraid my knowledge is very limited. If I could help, I definitely would.
