### ISSUE TITLE
Ossiarch Bonereaper Trait "Dark Acolyte" Issue

### ISSUE THREAD

**Issue by acovarru91** [BSData/warhammer-age-of-sigmar#1610]
The trait Dark Acolyte provides a Liege Kavalos the ability to learn a spell and cast it. There is no option to select a spell after giving the trait to the leader.

**Comment by rweyrauch** [comment]
Lore of the Mortisans is available to the Liege Kavalos when the Dark Acolyte is selected.   To reach the selection screen for the Lore of the Mortisans, See attached screen captures.

Steps.  Select the Dark Acolyte command trait.  After Dark Acolyte is select press on the "Traits: Kavalos: 3. Dark Acolyte" text, not the selection button.   Pressing on the trait name, the Lore of Mortisans selection screen is shown.

![Screenshot_20201214-200042](https://user-images.githubusercontent.com/7072852/102169703-a1052080-3e47-11eb-987b-60692d4857e4.png)
![Screenshot_20201214-200023](https://user-images.githubusercontent.com/7072852/102169722-b0846980-3e47-11eb-9dfb-557d05a7d798.png)
![Screenshot_20201214-200031](https://user-images.githubusercontent.com/7072852/102169734-b5491d80-3e47-11eb-9710-c5f7abf4a6cc.png)
