### ISSUE TITLE
[Anon] Bug report: Chaos - Slaves to Darkness Data.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#1614]
**File:** Chaos - Slaves to Darkness Data.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Archaon is missing the option to choose an Aura of Chaos.
Archaon is missing the option to choose a spell from the Lore of the Damned.

**Comment by cartag** [comment]
Added Aura of Chaos SSEG for Archaon
Added Auras of Chaos to Mark of Chaos selection for Heroes

Added Spell Lores SSEG to Archaon

Corrected in next release.
