### ISSUE TITLE
Issues with Tzeentch Allegiance 

### ISSUE THREAD

**Issue by acovarru91** [BSData/warhammer-age-of-sigmar#1615]
Tzaangor Shamans cannot be given Fated Artifacts for being an Arcanite Hero. They also cannot be given the command trait "Tzeentch is pleased" in a Cult of a Thousand Eyes coven.

The Fatesworn Warband is not an option to include in the army.

**Comment by cartag** [comment]
Fated Artefacts are for Tzeentch Mortal Heroes, not Arcanite. 

Adding Wrath of the Everchosen Command Traits to options in BoC data. 

Added Fatesworn Warband to Tzeentch. 

Will be updated in next release.
