### ISSUE TITLE
Daughters of Khaine Blood Sisters

### ISSUE THREAD

**Issue by kitsune523** [BSData/warhammer-age-of-sigmar#1620]
As of shadow and pain the blood sisters crystal touch attack has been changed to an ability called "turned to crystal: at the end of the combat phase you can pick one enemy unit within 1" of this unit and roll one dice for each model in this unit, for each 3+ that enemy unit suffers one mortal wound."

**Comment by rweyrauch** [comment]
Fix in #1622.
