### ISSUE TITLE
Cities of Sigmar, Har Kuron

### ISSUE THREAD

**Issue by Ejaycee** [BSData/warhammer-age-of-sigmar#1621]
The city has a spelling mistake it is called Har Kuron - not Hal Kuron. 
The Shadow Queen is missing from the leaders tab.
The incitement to murder prayer is missing from the priests prayers (hag queen and slaughter queen and if you take murderous zeal, the general needs that option as well)
Keep up the good work :-)

**Comment by cartag** [comment]
Corrected to Har Kuron
Added Shadow Queen RSE
Added Incitement to Murder to relevant priests and to Command Trait of Murderous Zeal
Corrected in next release.
