### ISSUE TITLE
Battalion points for Ossiarch Bonereapers

### ISSUE THREAD

**Issue by leahmangray** [BSData/warhammer-age-of-sigmar#1624]
OBR battalion points are incorrect. Here are the correct points from the battletome and checked with Warscroll Builder:

Aegis Immortal is 630. Should be 80
Katakrosian Deathglaive is 630. Should be 80
Kavalos Lance is 480. Should be 120
Mortek Ballistari is 760. Should be 100
Mortek Shield-corps is 510. Should be 120
Mortisan Trident is 700. Should be 110
Ossiarch Cohort is 3810. Should be 100

Warscroll Builder also adds these battalions:

From Feast of Bones army box:
Vokmortian's Retinue 120

From White Dwarf 453:
Harvester Scythe Corps 100
Vokmortian's Dread Retinue 130
Vokmortian's Tithe Legion 110

**Comment by cartag** [comment]
Those battalions are correct in points. Try adding one to your roster. They add all mandatory options automatically. If there is a choice of unit, it doesn't add anything, but for ones that are like 1+ of unit X, it adds 1 of unit X automatically. 

Vokmortian's Retinue from Feast of Bones is added but not linked and will be added in the next update. 

For The White Dwarf battalions, set your legion to Mortis Praetorians, following the rules in WD 453.

**Comment by leahmangray** [comment]
Well don't I feel silly! I was adding the battalion after adding all the units. Sorry for my newbie mistake.
