### ISSUE TITLE
Starter Box Battalions Missing 

### ISSUE THREAD

**Issue by DerekBacon** [BSData/warhammer-age-of-sigmar#1641]
Hi I have just noticed that in the Sylvaneth battalion list the Heartwood Host battalion from the starter box is missing. I also check the Maggotkin of Nurgle roster and found the Glugurous' Plagueband missing as well. I was wondering if you could add them please. I haven't checked the other armies but most have a unique starter box battalion as well.

Thank you.

**Comment by rweyrauch** [comment]
I can add the Sylvaneth start collecting battalion as I have the box.  I'll see if I can track down the other start collecting battalions.

**Comment by DerekBacon** [comment]
I have the box sets for Maggotkin of Nurgle and Ironjaws if you would like me to comment the warscrolls for them although they don't have point costs and thank you for doing that.

**Comment by DerekBacon** [comment]
There the Ironjawz Smasha Boyz and Glugurous' Plagueband

**Comment by cartag** [comment]
An important thing to note for these battalions is that they are not legal for matched play if they do not have a point value. For open play or narrative they're fine to use.

**Comment by DerekBacon** [comment]
I know I believe there are point costs for them online but I personally only play friendly to house rules competitive games. I don't know if it's worth placing a disclaimer about that with the battalions.

**Comment by rweyrauch** [comment]
Added the requested warscrolls.

**Comment by Tigerwraith** [comment]
> I know I believe there are point costs for them online but I personally only play friendly to house rules competitive games. I don't know if it's worth placing a disclaimer about that with the battalions.

There are no points values for them. All points come from the battletomb or GHB. If the GHB does not list them they are not legal for match play.
