### ISSUE TITLE
Tzeentch Artifacts have Command Traits Instead

### ISSUE THREAD

**Issue by acovarru91** [BSData/warhammer-age-of-sigmar#1650]
A Chaos Sorcerer Lord on Manticore has command trait choices listed underneath Artifacts instead of Tzeentch Mortal Artifacts. There appears to be similar issues with other StD leaders. Alhough i haven't tested every single StD leader, it comes up for all I've tested.

**Comment by cartag** [comment]
Fixed in next release.
