### ISSUE TITLE
Skaven point values

### ISSUE THREAD

**Issue by jdhartl** [BSData/warhammer-age-of-sigmar#1657]
The point values for several skaven entries are outdated:
Thanquol on Boneripper should be 400 points
Warlock Engineer should be 100 points
Doomwheel should be 160 points
Hell Pit Abomination should be 240 points
Plagueclaw should be 160 points
Stormvermin should be 120 points per 10 models, or 450 points at 40 models.
Plague Monks should be 70 points per 10 models, or 240 points at 40 models.
Rat Ogors should be 100 per 2 models.
Ratling Gun should be 80 points.
Skryre Acolytes should be 320 points for 30 models, and should have a maximum of 30 models instead of 20.
Arkhspark Voltik should be 60 points
Gascloud Chokelung should be 70 points
Gautfyre Scorch should be 90 points
Rattlegauge Warplock should be 70 points
Whyrlblade Threshik should be 80 points
Warp Lightning Vortex should be 100 points

**Comment by cartag** [comment]
You're citing points from FAQ in Dec 2019. Points listed are from GHB 2020.
