### ISSUE TITLE
January 2021 FAQ Work Tracker

### ISSUE THREAD

**Issue by rweyrauch** [BSData/warhammer-age-of-sigmar#1661]
- [x] Tzeentch
- [x] Flesh-eater Courts
- [x] Seraphon
- [x] Kharadron Overlords
- [x] Lumineth
- [x] Nighthaunt
- [x] GHb 2020
- [x] Broken Realms: Morathi
- [x] Malign Sorcery

**Comment by cartag** [comment]
These are already done
