### ISSUE TITLE
Tzaangor Favorites

### ISSUE THREAD

**Issue by acovarru91** [BSData/warhammer-age-of-sigmar#1663]
Tzaangors are listed under Other instead of Battleline if you're trying to add them them in from your favorites.

**Comment by cartag** [comment]
What faction of a list are you making? Can you share a screenshot of the Roster Editor on Desktop or upload your roster so we can investigate?

**Comment by acovarru91** [comment]
This is mobile with a Disciples of Tzeentch allegiance. 
![Screenshot_20210126-133324](https://user-images.githubusercontent.com/71112069/105895548-42e96280-5fdb-11eb-8d3c-0a49b2097062.jpg) 
![Screenshot_20210126-133320](https://user-images.githubusercontent.com/71112069/105895558-47ae1680-5fdb-11eb-8c12-18ee2fa556e8.jpg)

**Comment by cartag** [comment]
That's looking like a bug with how the mobile app renders where favorites show up. Try adding one under Other and see if it really adds it to Other, or if it adds it to Battleline. 

Basically what is happening is that the Tzaangors ARE Other by default in the data file. If you are using a Tzeentch allegiance or are using a Tzaangor Shaman as your general in a BoC list. The app is listing the favorite under the primary category in the data file, not the changed primary category to make it Battleline. After it gets added to the list though, it should show under Battleline.

**Comment by acovarru91** [comment]
It does get added to Battleline no problem. The only issue i see is where it's popping up in favorites

**Comment by cartag** [comment]
Closing it here, I added an issue with BS itself since it's not a data problem. 

https://github.com/BattleScribe/Release/issues/237
