### ISSUE TITLE
Cities of Sigmar does not include 1-in-4 calculation

### ISSUE THREAD

**Issue by scottywan82** [BSData/warhammer-age-of-sigmar#1669]
Currently none of the Cities of Sigmar lists provides an error when the 1-in-4 limitation is exceeded for Stormcast, Sylvaneth, DoK, or KO units.

**Comment by cartag** [comment]
This is currently a Battlescribe app limitation. I've tried multiple work arounds but there is currently no way to reliably have it calculate the 1 in 4 limitation. This is one part of your list that you will be reliant on self-policing the limitation.
