### ISSUE TITLE
Warhammer: Age of Sigmar v2.2.24 Nurgle Deamon Fix 

### ISSUE THREAD

**Issue by 23Nightmare** [BSData/warhammer-age-of-sigmar#1675]
The Demon Plague Toads of Nurgle should come up as 120 points for 3, not 240 when adding the selection. The Demon Pox riders of Nurgle are also under the same issue, they should be 200 for 3.

**Comment by Tigerwraith** [comment]
@23Nightmare may want to check your GHB 2020 on those poxriders...pts are not 200 per 3.

**Comment by 23Nightmare** [comment]
Good Catch, they are 160 for 3
