### ISSUE TITLE
Kharadron Overlords Issues

### ISSUE THREAD

**Issue by chisox616** [BSData/warhammer-age-of-sigmar#1690]
1. When taking Aether Khemist with Spell in a Bottle Artifact of Power non KO faction specific spells are missing from list (i.e. Warp Lightning Vortex) when artifact allows their selection.
2. When taking Barak-zilfin aetheric navigator can be equipped with staff of ocular optimization. This does not count towards 2 artifact of power limit but error still shows 1 too many artifacts when equipping 2 other artifacts to army in addition to staff.

**Comment by cartag** [comment]
1) Current method is just to add a secondary force like allies to add a spell in a bottle. If somebody wants to take the time to implement this I can explain what needs to be done for it. 
2) You don't get that staff in addition to other artefacts you may receive, it is the first one you have to choose. It takes up  your first artefact selection.

**Comment by rweyrauch** [comment]
Moved to #2603
