### ISSUE TITLE
Khorne data not loading in on pc

### ISSUE THREAD

**Issue by Xanetaaz** [BSData/warhammer-age-of-sigmar#1697]
![Khorne Battlescribe](https://user-images.githubusercontent.com/79477613/108759887-3cec9000-754d-11eb-996d-995df42fdec4.JPG)
There is no options after creating a Khorne roster, tried all 4 variants, main, rear, spear, pitched. Only happens with Khorne.
The left part (where you choose leader, battleline etc.) contains no tekst, menus or icons.
The edit roster field, midle top, dosn't contain any text.
It loads in data via the load bar, but seems to not actually load it in.
Tried deleting and redownloading date, reinstalling Battlescribe, manually deleting the datafiles. Nothing worked.
It works fine on my phone, no problems. Tried 12 other rosters(from top and down), they all worked on pc.

**Comment by cartag** [comment]
I'm now able to duplicate. Pushed a new release.

**Comment by cartag** [comment]
The release just went live, you should be able to update again and create Khorne lists. Thanks for reporting the issue!
