### ISSUE TITLE
Destruction: Igor Mawtribes

### ISSUE THREAD

**Issue by epi01** [BSData/warhammer-age-of-sigmar#1705]
**With the last errata some points are changed**:
. Thundertusk Beastrider: from 300 to 270
. Frostlord on Thundertusk: from 390 to 350
. Huskard from Thundertusk: 340 to 300

**Gnoblar Scraplauncher, Rhinox's Sharp Horn Change the Attacks characteristic from 1 to 2**

**Comment by cartag** [comment]
All of those changes have been live in the data for several months, that errata was introduced in July 2020. Please update your data, the current Ogor Mawtribes data is v18.
