### ISSUE TITLE
Daughters of Khaine: Morgwaeth the bloodied doesn't have options

### ISSUE THREAD

**Issue by fanpire22** [BSData/warhammer-age-of-sigmar#1717]
As in the latest battletome, Morgwaeth the bloodied is a Priest, and as such, should be able to choose a prayer from the list available on page 67.

Also, she's a hero, and should be eligible to choose an artifact of power too from the list of Gifts of Morathi (on page 64) and also from the ones exclusive to Priests (listed on page 65)

**Comment by rweyrauch** [comment]
Named characters are not permitted to select Artefacts nor Command Traits (core rule book pg 17).

**Comment by fanpire22** [comment]
Oh, right, forgot about that...
But prayers are neither a command trait nor artefact. So they should be able to choose a prayer
  El mié., mar. 3, 2021 a 15:47, Rick Weyrauch<notifications@github.com> escribió:   


Named characters are not permitted to select Artefacts nor Command Traits (core rule book pg 17).
