### ISSUE TITLE
Broken Realms : Teclis - Maggotkin of Nurgle Update

### ISSUE THREAD

**Issue by Fzabik** [BSData/warhammer-age-of-sigmar#1746]
### Unit Warscroll update and cost points change
- [x] Beast of Nurgle (120pts) [https://www.games-workshop.com/resources/PDF/AoS_Warscrolls/Eng_BeastsOfNurgle.pdf](url)
- [x] Sloppity Bilepiper (150 pts) [https://www.games-workshop.com/resources/PDF/AoS_Warscrolls/Eng_SloppityBilepiper.pdf](url) 
- [x] Spoilpox Scrivener (140pts) [https://www.games-workshop.com/resources/PDF/AoS_Warscrolls/Eng_SpoilpoxScrivener.pdf](url) 

### Battalion
- [x] Invidian PlagueHost (120 pts) [https://ibb.co/BZPqDXk](url)

**Comment by cartag** [comment]
Changes already implemented, not uploaded yet. Will be live when book goes live.
