### ISSUE TITLE
Har Kuron Roster Issues

### ISSUE THREAD

**Issue by acovarru91** [BSData/warhammer-age-of-sigmar#1748]
Looks like there are missing Daughters of Khaine units from the roster when making a Cities of Sigmar Har Kuron list. So far the missing units include:

Melusai Ironscale
Morgwaeth the Bloodied and Coven
Blood Stalkers
Doomfire Warlocks
Khainite Shadowstalkers
Khinerai Lifetakers 
Khinerai Heartpiercers

In an opposite problem, Stormcast units aren't eligible to be included in Har Kuron. Some units are indeed not available to add but some still show up.

Just updated on Android and remade the roster a few times and the problem occurred each time

**Comment by cartag** [comment]
Resolved in next release.
