### ISSUE TITLE
Ogors: Hrothgorn has no Icebrow Hunter options

### ISSUE THREAD

**Issue by Kevinesque** [BSData/warhammer-age-of-sigmar#1750]
According to his official warscroll, Hrothgorn,
although different in not being able to do the 
same attacks, still has the ICEBROW HUNTER
keyword. Therefore, he should have access to
those options. I have linked the warscroll:
![F25AF43F-ED1D-470B-ADDF-0CD3B72FD854](https://user-images.githubusercontent.com/81734293/113247829-bb7be080-92f6-11eb-8c04-fe93e2d40641.png)

**Comment by abraracurcix** [comment]
He is a named character so he can't have any artefact or command trait, and he can't be included in any battalion. Sorry, I don't know what do you mean.
