### ISSUE TITLE
Ogors (and others?): Realm of origins relic options missing

### ISSUE THREAD

**Issue by Kevinesque** [BSData/warhammer-age-of-sigmar#1751]
In building an Ogor army,
I planned to add some Realm of origin artifacts
to my heroes. However... they don’t seem to be
there. See the pictures... I switched realms once
to give an example of what I’m seeing.
It is only showing one of the options from the
total pool of options that should be available.

It also doesn’t seem to matter if it’s the battle
realm or the realm of origin. I also didn’t test to 
see if this is just Ogors, but hey, I’m new here.
I like this app so far, but maybe Ogors need some
debug loving, eh? This is the second bug I found
today as a user customizing his Ogor build.
I may find more, but time will tell.

![634FB96E-3137-4D26-AF0D-DCDE3161BF27](https://user-images.githubusercontent.com/81734293/113253919-e4a16e80-9300-11eb-9653-e1d1d5504762.png)
![9B32C012-2053-4821-A180-4C803BB57EF5](https://user-images.githubusercontent.com/81734293/113253927-e8cd8c00-9300-11eb-9e68-9c6c889f08a2.png)

**Comment by abraracurcix** [comment]
The last General Handbook reduced the number of Realm Artefacts to only one artefact.
