### ISSUE TITLE
Where to Put: Scenery (Wildwoods/Feculent Gnarlmaw/Vortex

### ISSUE THREAD

**Issue by OftKilted** [BSData/warhammer-age-of-sigmar#177]
The scenery that exists with points needs a location.

Given that everyone 'can' take nearly all of it, a good location (or a scenery catalog) would be a good choice.

Sylvaneth get their 'free version' but everyone gets to pay for the Vortex.

**Comment by FreylisUK** [comment]
For the time being I suggest we add the Balewind Vortex and Sylvaneth Wyldwood to the GST and create a Scenery primary category for them. If we decide to add more we can break them out into their own catalogue.

**Comment by OftKilted** [comment]
Balewind vortex into the GST makes sense.
Sylvaneth Wyldwood is 'sylvaneth' it should probably be added to the Sylvaneth Cat, and given an 'Allies' listing that costs 40 points. (with their native 'Sylvaneth Allegiance' being 0 points for them.

**Comment by FreylisUK** [comment]
I've added the Balewind Vortex and Sylvaneth Wyldwood and created a pull request in #192. The Feculent Gnarlmaw can be added to the Maggotkin cat when we get around to creating it.

**Comment by OftKilted** [comment]
Perhaps what we should do for the 'Scenery' section is actually remove it ... 
If we instead add a SE on the abilities/spells that grant the ability to cast the spell, that targets the issue directly.
For the Balewind Vortex one could actually set it up as a Rule like 'Inspiring Presence' if there are more than 0 instances of WIZARD in the army.
And reference that it costs 100 points to cast.
Sortof a 'Description Rule/Profile' type?

**Comment by FreylisUK** [comment]
After discussion we will leave Scenery out as an actual category for now. The Wyldwood has been added to the Sylvaneth catalogue, and the Feculent Gnarlmaw will follow suit.
