### ISSUE TITLE
Lumineth Realm-Lords Unit Types

### ISSUE THREAD

**Issue by Clouded-Mind** [BSData/warhammer-age-of-sigmar#1770]
I'm unsure if this would qualify as a bug, but was advised to post here just in case.

Right now the battleline section for the Lumineth Realm-Lords contains Wardens, Sentinels, Dawnriders, and Bladelords. From the knowledge that I have, Bladelords are not considered battleline while Dawnriders and Sentinels are only considered battleline if they have an accompanying unit for each of them. I'm unsure if this was done on purpose or not, but thought it was worthwhile to bring it to the attention of those in charge.

**Comment by rweyrauch** [comment]
The battleline for the various Vanari units was done this way on purpose.   I currently do not know how to implement the battleline constraints for Sentinels, Bladelords and Dawnriders in the Battlescribe catalog data format.

**Comment by cartag** [comment]
Make a separate RSE for each unit that can be brought as battleline, then set max in roster as increasing by 1 for each other unit that is added to the roster?

**Comment by TomHawk123** [comment]
Additionally, Hurakan Windchargers can be battleline in Great Nation of Helon armies. There is currently no option to select Great Nations in the scribe.

**Comment by rweyrauch** [comment]
Great Nations are selected from the Allegiance: Lumineth page.   See attached image.
![Screenshot_20210705-201345](https://user-images.githubusercontent.com/7072852/124536973-d8302480-ddcd-11eb-8f54-00d9b29b7a15.png)

**Comment by Veziik** [comment]
1. Windchargers as battleline works
2. Alternatively, add an option on each warden unit to mark a dawnrider or sentinel unity as battelline, similar to dynastic advisors in wh40k/necrons.catz

**Comment by sarahmarr90** [comment]
The great nations have disappeared since the update to AOS 3.0?

**Comment by TomHawk123** [comment]
The Great Nations didn't disappear for 3.0. I am just a noob that didn't understand how that aspect of the app worked.

**Comment by sarahmarr90** [comment]
> The Great Nations didn't disappear for 3.0. I am just a noob that didn't understand how that aspect of the app worked.

I could see them before, but when I look at the app on my phone and desktop (which i have just updated) I can't see them

**Comment by sarahmarr90** [comment]
> The Great Nations didn't disappear for 3.0. I am just a noob that didn't understand how that aspect of the app worked.

Oh wait...found it! Sorry!

**Comment by rweyrauch** [comment]
No worries.

**Comment by cartag** [comment]
Battleline limitations have been implemented.
