### ISSUE TITLE
A tale of a ghost and his unmodified wound rolls

### ISSUE THREAD

**Issue by Stringo164** [BSData/warhammer-age-of-sigmar#1771]
(posted this on the discord but wanted to post it here to be safe)

Might have found an error for the Nighthaunt Executioner. Listed on battlescribe, the soul wars card, and online warscroll that his Beheading Strike goes off on a wound of 6+. In the Nighthaunt Battletome and Sigmar App it is listed as unmodified 6.

I don't know what is the true rule is now but I would assume it's unmodified because the former is too much fun.

**Comment by cartag** [comment]
Resolved with #1764
