### ISSUE TITLE
Realm Lords bug

### ISSUE THREAD

**Issue by PuckDuncher** [BSData/warhammer-age-of-sigmar#1773]
Heya, it appears that with Lumineth it is impossible to select artifacts and command traits for generals. For instance if I select Alumnia great nation it tells me I have to have the waystone in use. I select Lyrior Uthralle as general, but no new options show up for command traits or artifacts. 
Update: I selected a loreseeker as general and I am able to make command traits and artifact selections, although it is possible to select a command trait other than burning gaze (which should be impossible with alumnia selected).

**Comment by cartag** [comment]
Unique, named characters cannot take command traits or artefacts. 

Lumineth isn't restricting Command Traits to the selection for the subfaction you've chosen. That part is a bug.

**Comment by PuckDuncher** [comment]
Ahhh Thank you, I'm still pretty new to AoS, must have missed that rule.
