### ISSUE TITLE
Broken Realms: Belakor updates

### ISSUE THREAD

**Issue by rweyrauch** [BSData/warhammer-age-of-sigmar#1778]
Warscroll Updates:
- [x] Belakor
- [x] Dreadscythe Harridans
- [x] Krulghast Cruciator
- [x] Gardus Steel Soul
- [x] Doomseeker
- [x] Grimwrath Berzerker
- [x] The Sorrowmourne Choir - Lady Olynder second general

Battletome Updates:
- [x] Nighthaunt Processions
- [x] The Emerald Host
- [x] Reikenor's Condemned
- [x] Chaos
- [x] Kharadon Overlords
- [x] Seraphon
- [x] Disciples of Tzeentch

**Comment by cartag** [comment]
I'll tackle Chaos additions

**Comment by rweyrauch** [comment]
I'll take care of the Order changes.

**Comment by rweyrauch** [comment]
I'll also work on the Death changes.
