### ISSUE TITLE
Meeting Engagements

### ISSUE THREAD

**Issue by jdward91** [BSData/warhammer-age-of-sigmar#1781]
In Meeting Engagement - Spearhead, it's showing an error saying you can only have one unit from the "other" category, when in fact you can have two.

**Comment by jdward91** [comment]
Also, it's not validating Battleline correctly. For example, in Spearhead for a Grand Host of Nagash army, I have a Vamp (1 x leader), 10 Grave Guard (1 x battleline), Bat Swarms and Blood Knights (2 x other). This is a valid Spearhead force. However, it's saying I have 1 too many selections from Battleline (max 1), and 2 too many from other (max 1), which is incorrectly validating the units.

**Comment by cartag** [comment]
I'll be updating the GST for max battleline in Spearhead. The problem with Other units is a bit more involved I think. Right now, when it switches a unit from Other to Battleline, it just adds Battleline as the primary category of it. It is still considered Other though. I've tried removing the Other category when switching to Battleline, and was still getting the error. 

I will be researching more.

**Comment by jdward91** [comment]
I'm assuming this issue is now irrelevant, save for the technical quirks of the platform.
