### ISSUE TITLE
Stormcast Eternals problems

### ISSUE THREAD

**Issue by raven1840** [BSData/warhammer-age-of-sigmar#1782]
PC Version

Keeps asking for averon stormstrike to be added to any list.

battalion: ven brecht's black watch - unless ven brecht is the general which he doesn't have to be.  He doesn't need the trait fiendslayer. The system is saying you have to have it to clear the error.

Battalions : semptenials cleansing phalanx doesn't recognise the sequitors as battleline when Lynus Ghalmorian is selected as general, whether in the conclave or seperate pick.

Battalion: cleansing phalanx - doesnt recognise sequitoprs have been chosen regardless of which, of the two that show up, you click.

**Comment by rweyrauch** [comment]
Cleansing Phalanx battalions fixed with #1792.
