### ISSUE TITLE
Move shared Category keywords to the GST

### ISSUE THREAD

**Issue by FreylisUK** [BSData/warhammer-age-of-sigmar#182]
- Add shared Category keywords to GST (e.g. AELF, DUARDIN, etc).
- Add links to shared Category keywords to each relevant catalogue entry.
- Carefully remove duplicate local keywords from each replaced catalogue entry.

**Comment by OftKilted** [comment]
Main category Keywords Migrated. Any additional keywords will be migrated individually.
