### ISSUE TITLE
[Anon] Bug report: Chaos - Skaven - Data.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#1872]
**File:** Chaos - Skaven - Data.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Verminking data:
the thirteen headed one table not match with the unit ability
missing ability: Protection of the Horned Rat, Terrifying

**Comment by cartag** [comment]
Corrected on prep branch
