### ISSUE TITLE
Release Thread 3.0

### ISSUE THREAD

**Issue by cartag** [BSData/warhammer-age-of-sigmar#1876]
Data Developers - Please use this issue to push new releases if doing so via comment.

# Explainer

- Create an issue comment that starts with `/release` on the first line.
- Second (non-empty) line will be used as a release title/name.
- All following lines will be interpreted as a release description/body.
- Description (even if empty) will always be appended with a comparison link to the previous release, unless there is no previous release.

# How to

Add a comment with one of the following to push a release:

### For a standard release:
*given latest release v2.2.2, will create a release v2.2.3 (increases patch)*
> /release
>
> This is title of v2.3.0

### For a Chapter Approved/Big FAQ initial releases (game-wide updates):
*given latest release v2.2.2, will create a release v2.3.0 (increases minor, resets patch)*
> /release bump=minor
>
> This is title of v2.3.0

### For a new game edition:
*given latest release v2.2.2, will create a release v3.0.0 (increases major, resets minor and patch)*
> /release bump=major
>
> This is title of v3.0.0

**Comment by cartag** [comment]
/release bump=major
AoS 3.0

**Comment by cartag** [comment]
/release 
AoS 3.0.1

**Comment by cartag** [comment]
/release
Day 1 of Bug Fixes complete

**Comment by cartag** [comment]
/release
Day 2 of Bug Fixes complete

**Comment by cartag** [comment]
/release
Day 3 of bug fixes complete

**Comment by rweyrauch** [comment]
/release
Day 3.1 of bug fixes complete.

**Comment by rweyrauch** [comment]
/release
Day 4 of bug fixes complete.  Hang in there.

**Comment by cartag** [comment]
/release
Day 5, thank you for all your bug reports!

**Comment by cartag** [comment]
/release
Day 6, more fine tuning

**Comment by rweyrauch** [comment]
/release
Days 7,8 and 9.  The end is near.  At least until the new Battletomes drop.

**Comment by cartag** [comment]
/release
Getting Closer

**Comment by amis92** [comment]
@Mad-Spy @cartag the reactions are blocked because for *some f-ing reason* that action requires the issue not to be locked. It can edit the comment just fine, but not add a reaction to it.

Anyway, the fix is to unlock this. I'll proceed with it.

**Comment by cartag** [comment]
/release
Happy days are here again

**Comment by cartag** [comment]
/release
Now we rest until the next battletome drops

**Comment by cartag** [comment]
/release
I was only kidding about that whole rest thing...

**Comment by cartag** [comment]
/release 
Matched Play and Pitched Battles 2021 Split

**Comment by cartag** [comment]
/release
Let's Try That Again...

**Comment by cartag** [comment]
/release
Help Wanted: L4 Writer for Funny Release Titles
Only sort of joking

**Comment by cartag** [comment]
/release
Time for a Conquest of Generals!

**Comment by cartag** [comment]
/release
Conquest Of Generals Allied Battleline Fix

**Comment by cartag** [comment]
/release
We want our new battletomes, dammit!

**Comment by cartag** [comment]
/release
I don't want to work, I want to bang on the drum all day

**Comment by cartag** [comment]
/release
August FAQ and Legends

**Comment by cartag** [comment]
/release
FAQ QA and Allied Enhancements

**Comment by cartag** [comment]
/release
Sept FAQ

**Comment by cartag** [comment]
/release
Faction Core Battalions for SoB

**Comment by cartag** [comment]
/release
New Battletomes!

**Comment by cartag** [comment]
/release
Points fixes for SCE

**Comment by cartag** [comment]
/release 
QA pass 2

**Comment by rweyrauch** [comment]
/release
Coming out of beta.

**Comment by rweyrauch** [comment]
/release
It takes a village...

**Comment by cartag** [comment]
/release
More QA

**Comment by rweyrauch** [comment]
/release
A few straggler bug fixes.

**Comment by cartag** [comment]
/release
The man in black fled across the desert...

**Comment by rweyrauch** [comment]
/release
I must not fear.  Fear is the mind-killer.

**Comment by cartag** [comment]
/release
Chaos Fixes take 2

**Comment by cartag** [comment]
/release
New Warcry Warbands are here!

**Comment by rweyrauch** [comment]
/release
Kruleboyz fixez!

**Comment by cartag** [comment]
/release
Cities of Sigmar White Dwarf 470 Update

**Comment by cartag** [comment]
/release
A few bug fixes

**Comment by cartag** [comment]
Papa Nurgle sends his blessings

**Comment by cartag** [comment]
/release
Papa Nurgle sends his blessings

**Comment by cartag** [comment]
/release
"And now destiny is far less valuable"

**Comment by cartag** [comment]
/release
Archaon Price Fix, among others

**Comment by rweyrauch** [comment]
/release
Post-holidays blues release.

**Comment by rweyrauch** [comment]
/release
Fury of the something...
