### ISSUE TITLE
July 2021 FAQ updates.

### ISSUE THREAD

**Issue by rweyrauch** [BSData/warhammer-age-of-sigmar#1877]
Needs FAQ'ing

- [x] Beasts of Chaos
- [x] Khorne
- [x] Nurgle
- [x] Skaven
- [x] Slaanesh
- [x] Slaves to Darkness
- [x] Tzeentch
- [x] Flesh Eater Courts
- [x] Soulblight Gravelords
- [x] Nighthaunt
- [x] Sons of Behemat
- [x] Sylvaneth
- [x] Cities of Sigmar
- [x] Daughters of Khaine
- [x] Fyreslayers
- [x] Idoneth Deepkin
- [x] Kharadron Overlords
- [x] Lumineth Realm-Lords
- [x] Seraphon
- [x] Ossiarch Bonereapers
- [x] Orruk Warclans
- [x] Gloomspite Gitz
- [x] Ogor Mawtribes
- [x] Stormcast Eternals

**Comment by cartag** [comment]
Chaos will not have Coalition implemented yet.

**Comment by cartag** [comment]
Strike that, Coalition units 1/4 Beasts of Chaos and 2/4 Slaves to Darkness have been implemented. Same can be done with Cities of Sigmar/other Order files.

**Comment by rweyrauch** [comment]
Did not implement Coalition for KO yet.

**Comment by rweyrauch** [comment]
Major updates complete.
