### ISSUE TITLE
Move Stormcast Eternal endless spells to GST.

### ISSUE THREAD

**Issue by rweyrauch** [BSData/warhammer-age-of-sigmar#1878]
The former Stormcast Eternal endless spells (Comet, Dais and Vortex) are no longer limited to ScE WIZARDS.

**Comment by cartag** [comment]
Could they be moved to Order Data.cat instead of the GST?

**Comment by rweyrauch** [comment]
Could move all of the endless spells to their own catalog instead.   More work but less clutter in the GST.

**Comment by rweyrauch** [comment]
Holding off on moving the SCE endless spells until after the new SCE battletome drops and what factions have access to these spells.

**Comment by rweyrauch** [comment]
ScE endless spells are still limited to ScE wizards.
