### ISSUE TITLE
Bug Report: Order -  Cities of Sigmar.catz

### ISSUE THREAD

**Issue by drrbstr** [BSData/warhammer-age-of-sigmar#1892]
In 3.0.1 when you add an Anointed to the Frostheart or Flame Spire Phoenix the unit disappears from the roster list. If you then add another unit of any kind it will reappear.

**Comment by rweyrauch** [comment]
After adding the Anointed to the Phoenix, the unit battlefield role changes from Behemoth to Leader.   Check in the Leaders portion of the list for the Phoenix w/ Annointed.

**Comment by drrbstr** [comment]
I understand that's what it's supposed to do. However, the unit no longer appears under any role unless I add or remove a different unit. Perhaps this is a bug in BS itself.

**Comment by rweyrauch** [comment]
I checked with the Desktop app.  Will re-test with on the Android app.

**Comment by rweyrauch** [comment]
Just checked on Android.  The Phoenix moves from Behemoth to Leader when the Anointed is added as expected.

What version of BS are you running?   What platform?

**Comment by drrbstr** [comment]
It's v2.03.21.166 on Windows 10.

But I've restarted the computer and it's working properly now. It may remain a mystery at this point.

**Comment by rweyrauch** [comment]
Battlescribe is full of mysteries - a lot of stuff is magically cached.
