### ISSUE TITLE
Bug report: Core Battalion Warlord does not add extra artefact

### ISSUE THREAD

**Issue by plavski** [BSData/warhammer-age-of-sigmar#1893]
AoS 3.0.1

When adding a Core Battalion: Warlord and selecting "Extra Enhancement: Artefacts of Power", a validation error is thrown when two artefacts are selected.

![image](https://user-images.githubusercontent.com/15157275/124395485-44425800-dcfc-11eb-8532-0f39237e6e08.png)

**Comment by cartag** [comment]
This is a bug noticed in several catalogs, it is being corrected.
