### ISSUE TITLE
Bug report: Adding two artefacts shows different validation errors

### ISSUE THREAD

**Issue by plavski** [BSData/warhammer-age-of-sigmar#1895]
AoS 3.0.1

Adding two artefacts when only one is permitted shows two validation errors:

![image](https://user-images.githubusercontent.com/15157275/124395607-f2e69880-dcfc-11eb-9286-403433ea73ab.png)

**Comment by cartag** [comment]
Each time the error procs it will list an error. The root behavior has been corrected though.
