### ISSUE TITLE
Bug Report: Adding Hunters of the Heartland battalion also adds Grand Battery

### ISSUE THREAD

**Issue by plavski** [BSData/warhammer-age-of-sigmar#1898]
AoS 3.0.1

If you add the Hunters of the Heartland battalion, it will proc validation errors for the Grand Battery battalion

![image](https://user-images.githubusercontent.com/15157275/124395945-e3684f00-dcfe-11eb-9191-d525dfe717ef.png)

**Comment by cartag** [comment]
Resolved in #1899.

Thanks for your bug reports, it is appreciated!

**Comment by plavski** [comment]
Thank you and the rest of the team for your hard work on this! It's appreciated by the whole community!
