### ISSUE TITLE
Arcane Tome adding spell lores

### ISSUE THREAD

**Issue by teun135** [BSData/warhammer-age-of-sigmar#1914]
Hey y'all, was perusing your hard work, nice job! I did find one quibble, and that is that you cannot choose a spell lore for a unit that has the Arcane Tome artefact selected.  Only saw this in Orruk Warclans, particularly for Kruleboyz allegiance, have not looked elsewhere for it yet.

**Comment by cartag** [comment]
Thanks for the bug report! This is one we're already aware of and it will be fixed with the next release.
