### ISSUE TITLE
soulblight grave guard/kosargi/vargskyr/bloodborn

### ISSUE THREAD

**Issue by talonz51** [BSData/warhammer-age-of-sigmar#1918]
Grave guard show up twice, and in battle line, when they are not (unless you have a wight king).

You cannot reinforce the kosargi nightguard or vyrkos bloodborn when you should be able to, and both units and the vargskyr cause a limit error when you pick more than one when there is no limit (they are not unique anymore).

**Comment by rweyrauch** [comment]
Fixed.

**Comment by talonz51** [comment]
Still cant reinforce those (non GG) units?

**Comment by rweyrauch** [comment]
Fixes are present in 3.0.3
