### ISSUE TITLE
battalions

### ISSUE THREAD

**Issue by talonz51** [BSData/warhammer-age-of-sigmar#1919]
Command entourage does not show the strategist/magnificent benefits.
Grand battery shows scent tracking instead of slayers.

Where do hunters of the heartlands and alpha-beast pack come from?  Reference please.

**Comment by cartag** [comment]
Hunters of the Heartlands and Alpha-beast Pack come from GHB 2021.

**Comment by cartag** [comment]
Command Entourage requires you to select between the two
![image](https://user-images.githubusercontent.com/4388344/124510548-473b5800-dd91-11eb-9a05-d170cb94f7a8.png)
