### ISSUE TITLE
Lumineth warscroll

### ISSUE THREAD

**Issue by TomHawk123** [BSData/warhammer-age-of-sigmar#1929]
I believe the warscroll for Hurakan, Spirit of the Wind is missing from Lumineth.

**Comment by rweyrauch** [comment]
Spirit of the Wind is listed under Other as expected.  Please clarify the problem you are having.

**Comment by TomHawk123** [comment]
You're correct. It used to be under "Leaders." Thanks.

**Comment by cartag** [comment]
> You're correct. It used to be under "Leaders." Thanks.

Check the latest version of the Battletome, it is not a Leader.
