### ISSUE TITLE
Remove Leader/Behemoth category

### ISSUE THREAD

**Issue by FreylisUK** [BSData/warhammer-age-of-sigmar#197]
- Untag Leader/Behemoth from all affected RSEs
- Replace with Leader and Behemoth tags (with Leader marked as Primary)
- Remove Leader/Behemoth Category Entry from the GST

- [x] Chaos
- [x] Chaos - Brayherd
- [x] Chaos - Everchosen
- [x] Chaos - Monsters of Chaos
- [x] Chaos - Slaves to Darkness
- [x] Death - Tomb Kings
- [x] Death - Vampire Counts
- [x] Death - Flesh-eater Courts
- [x] Death - Legions of Nagash
- [x] Destruction
- [x] Destruction - Beastclaw Raiders
- [x] Destruction - Bonesplitterz
- [x] Destruction - Ironjawz
- [x] Order
- [x] Order - Darkling Covens
- [x] Order - Dispossessed
- [x] Order - Free Peoples
- [x] Order - Fyreslayers
- [x] Order - Seraphon
- [x] Order - Stormcast Eternals
- [x] Order - Wanderers
- [x] Order - Daughters of Khaine
- [x] Order - Kharadron Overlords
- [x] Order - Sylvaneth

**Comment by Mad-Spy** [comment]
I've missed ONE in the Chaos GA cat. I'll sort it later.

**Comment by rweyrauch** [comment]
A quick search reveals that the following catalogs still reference 'Leader/Behemoth' category (on AoS-v2.0 branch):

Chaos.cat
Destruction - Beastclaw Raiders.cat
Destruction - Bonesplitterz.cat
Destruction.cat
Destruction - Ironjawz.cat

**Comment by lbwilson3rd** [comment]
Unsubscribe

"I will work harder."  - Boxer, George Orwell's "Animal Farm."

**Comment by OftKilted** [comment]
Chaos.cat validated as no longer having any units with 'LEADER/BEHEMOTH' keyword.
