### ISSUE TITLE
AoS v87 : Cities of Sigmar v56 : Har Kuron + Misthavn

### ISSUE THREAD

**Issue by Lescaz** [BSData/warhammer-age-of-sigmar#1972]
in the Age of Sigmar v87 release:
- [x] the Har Kuron city cannot select any DoK units
- [x] the Misthavn city Command Ability (shadowstrike) is missing
- [x] the Misthavn Narcotics are not available

**Comment by cartag** [comment]
All cities will need to add a Coalition sub force for the coalition units they wish to use. In the Desktop app you do this by selecting your primary catalogue when adding a second force. 
![image](https://user-images.githubusercontent.com/4388344/124671944-79bd8180-de73-11eb-80d7-364a28a2021c.png)

On mobile, when you add a second force, it will ask what the parent force should be. Select the CoS force then to add the DoK sub-force.
