### ISSUE TITLE
Game system and Catalogue drafts

### ISSUE THREAD

**Issue by taalas** [BSData/warhammer-age-of-sigmar#2]
I added first drafts as a proposal for the Age of Sigmar game system and the Order catalogue. Please let me know if I am completely on the wrong track with this.

**Comment by MrRta1910** [comment]
Where can i access the draft catalog to test

**Comment by amis92** [comment]
In this repo, however it was not released yet, so you can only download it directly from here. On the main page you have a button on the right, "Download ZIP" (main page https://github.com/BSData/warhammer-age-of-sigmar).

**Comment by MrRta1910** [comment]
I can not use that zip on my android

**Comment by amis92** [comment]
You'll have to use PC to download it, and then use dropbox to sync it, or pack it up with battlescribe data tools and send to the phone that bsr file.

**Comment by MrRta1910** [comment]
Can it also have a wound count as a way to balance

**Comment by taalas** [comment]
Not completely sure if I understand what you mean exactly, could you elaborate on that?

**Comment by chevalric** [comment]
As a way to balance forces, people have been using number of wounds in an army as "points". So I'm guessing that @MrRta1910 wants to be able to have this translated to BattleScribe.

**Comment by Colten-Long** [comment]
While working on the lizards, I set the point cost equal to the wounds. While I think this is an insufficient way of comparing models, it seems to be the quickest route and people at the local shop have been using it for 'balance'.

That being said, 5 Temple Guards with 5 wounds, a 3+ save, & 15 attacks are way better than one Jungle Swarm with 5 wounds, no save, & 5 attacks. Jungle Swarms would only be useful in bulk, but using wounds instead of a points system makes them, practically, unusable.

**Comment by Colten-Long** [comment]
The rules reference model count when determining sudden death threshold, but if model count is the only method used for balance, competitive players will only build around the high wound models and ignore the one wound soldiers.

Ultimately, we have not been given an adequate means of comparing the strength of two armies. How we address this is a tough question. Do we:
1. Use wound count (favoring low-wound models)?
2. Use model count (favoring high-wound models)?
3. Scavenge point costs from old fantasy rules?
4. Set a community defined standard for point costs?

Personally, I'm all for the fourth option as I don't think that GW always does a good job with point costs and laying down community guidelines now has a lot of potential. That being said, it would be a large undertaking. 

An example of one possible point system for melee attacks:
(10) Melee attack - 1",6+,6+,-,1
(+2)                        2" range
(+4)                        3" range
(+5)                             5+ to hit
(+8)                             4+ to hit
(+10)                           3+ to hit
(+4)                                 5+ to wound
(+6)                                 4+ to wound
(+8)                                 3+ to wound
(+3)                                     -1 rend
(+6)                                     -2 rend
(*2)                                         2 damage
(*2)                                         D3 damage
(*3)                                         3 damage

So my Temple Guards would pay 83 points for the the following attacks (as would every model with the same attack profile):

2 attacks @ 1", 3+, 3+, -1, 1 [31 pts each]
1 attack @ 1", 5+, 4+, -, 1 [21 pts each]

Going through each weapon in the game then each other attribute would take time, but then we would have a comprehensive scoring system.

**Comment by chevalric** [comment]
The official rules allow you to do anything you want, but there are several community written army composition rules that add points to the models. As long as there is no de facto army build system that the majority of players uses, I think it's pointless (pun not intended ;)) to add points to the models.

For now, I would like to focus on getting all the war scroll data in the system, before worrying about point systems. Going back and adding either wound count or a point value is done easily enough.

The nicest solution would be to make it somehow possible to cater to all players; from the people that just throw together some models to the people that want to have a tournament worthy army that is balanced (at least on paper) with any other opponent in that tournament. But I don't see that happening in an easy way.

**Comment by MrRta1910** [comment]
If i could enter data eg stats from my phone because i travel alot

**Comment by amis92** [comment]
It's not yet possible, however I'm currently developing my own editor, as well as it's planned by BattleScribe dev, Jon. Mine should be out before end of the year.

**Comment by MrRta1910** [comment]
I have 2 days comeing up where i can enter data as im on a plane with my ipad

**Comment by flakpanda** [comment]
Closed due to age
