### ISSUE TITLE
Kharadron Overlords: Cannot select Stick To The Code

### ISSUE THREAD

**Issue by malter20** [BSData/warhammer-age-of-sigmar#2005]
The issue is related to the Android App. There is no selection beyond this level. 
![Screenshot_20210708_082049](https://user-images.githubusercontent.com/87113499/124872473-9c5faf80-dfc5-11eb-88d2-61750afe2b22.jpg)

_Originally posted by @malter20 in https://github.com/BSData/warhammer-age-of-sigmar/issues/1980#issuecomment-876164087_

**Comment by rweyrauch** [comment]
The Android app works correctly.

From the screen shown, press the checkmark to confirm the Allegiance: Kharadron Overlords.  On the next screen shown, press 'Allegiance: Allegiance Khraradron Overlords' text (not the check-box circle).    This takes you to the Allegiance: Kharadron Overlord screen.  You can change the Sky Port by pressing on the check-box circle.   Or you can change the the 'Stick To The Code' options by pressing on the 'Sky-Port: Stick To The Code' text.

**Comment by malter20** [comment]
Understood. Works as intended.
Thank you!
