### ISSUE TITLE
Gutrippaz points issue

### ISSUE THREAD

**Issue by WampaJames** [BSData/warhammer-age-of-sigmar#2008]
The 10 gutrippaz show the correct points but the unit entry is double that 
![B023016F-1B7F-491E-9FA9-CE6B567AD20C](https://user-images.githubusercontent.com/30240527/124924776-b0220a80-dff3-11eb-956f-ebe71bb86eb1.jpeg)

**Comment by rweyrauch** [comment]
Resolved in 3.0.6 or later.
