### ISSUE TITLE
Cities of Sigmar Issues

### ISSUE THREAD

**Issue by acovarru91** [BSData/warhammer-age-of-sigmar#2010]
Demigryph Knights points cost outdated. Needs to be 175. 

Judicators missing from battleline when adding Stormcast as a Coalition. 

Drakesworn Templar listed under Leaders, but is a Stormcast unit and should be under coalition only.

**Comment by acovarru91** [comment]
Just to clarify the Drakesworn Templar issue:

While the unit is correctly under Leader, Behemoth, it is not a Cities of Sigmar unit and only is a Stormcast unit so it should not be under the Cities of Sigmar Leader list inherently. It should only be able to be added via Stormcast Coalition

**Comment by rweyrauch** [comment]
Got it.   It looks like the Drakesworn selection is left over from the previous way CoS was implemented.  I'll remove the selection.
