### ISSUE TITLE
Bug report: Warsong Revenant not marked as sub 10 wounds leader

### ISSUE THREAD

**Issue by plavski** [BSData/warhammer-age-of-sigmar#2014]
AoS 3.0.6

The Sylvaneth Warsong Revenant, Arch-Revenant, Ylthari, & Branchwych are not marked as a sub 10 wounds leaders so can't be taken as sub commanders in the Warlord battalion.

**Comment by plavski** [comment]
Did this issue regress or not propagate? https://github.com/BSData/warhammer-age-of-sigmar/pull/1894/commits/286436a43bb797b201cfe4eaadd77842259fb361

**Comment by plavski** [comment]
Looks like it regressed in this PR: https://github.com/BSData/warhammer-age-of-sigmar/commit/982c8740dd4eb1a3d78fd343bf54b7cba85676fb#diff-c3c2ccfa1864f87aa068dd5f59d087eb0e919204e3acb8a3cca6cb8b04e08e9c

**Comment by cartag** [comment]
Just fixed. Will be updated with the release we'll do tonight.

**Comment by plavski** [comment]
Think you missed the Warsong Revenant tho?

**Comment by cartag** [comment]
Me? Never... Coincidentally, there's another new file up for Sylvaneth. Not related at all.
