### ISSUE TITLE
Sylvaneth Issue: Core Battalion Classifications 

### ISSUE THREAD

**Issue by Jumbaligha** [BSData/warhammer-age-of-sigmar#2022]
Under the Core Battalion selection options, some models are coming up as a Commander while they are I n fact a Sub-Commander. 

Models include: Arch Revenant, Branchwych, Warsong Revenant, and Ylthari

**Comment by cartag** [comment]
Thanks for reporting this! This was reported and fixed earlier today (#2014) and will be part of tonight's bug fix release.
