### ISSUE TITLE
More spell lore issues

### ISSUE THREAD

**Issue by exaegrum** [BSData/warhammer-age-of-sigmar#2026]
- [x] OBR? - Arkhan and Nagash are still posing problems - with the dialogue to select all of their individual spells, it locks them to exactly six and won't let them take a core spell, as other uniques currently can. 
- [x] Sylvaneth - Alarielle and the Warsong Revenant also do not currently have core spell access at all.
- [x] LRL - Teclis currently lets you choose one from any of the three tome lores/the core lore, when he should inherently know all of the Lumineth tome lore spells.
- [x] Slaanesh? - Synessa also lets you chose one when they should inherently know all of the Slaanesh tome spells.
- [x] NH - Nighthaunt's Lore of the Underworlds is radio buttons instead of checkboxes. This is an issue if you take an extra spell lore enhancement.

**Comment by cartag** [comment]
I appreciate you submitting bug reports and doing QA work, but for future bug reports would you mind keeping them to one faction per issue? It makes it easier to track where bugs come from. Nagash for example can be brought by multiple factions so knowing where the issue persists is helpful. I'm working on getting these corrected.
