### ISSUE TITLE
Enhancements bleeding between forces in a roster

### ISSUE THREAD

**Issue by exaegrum** [BSData/warhammer-age-of-sigmar#2027]
Armies get weird if you add multiple forces to a roster. Sometimes they can access spell lores and/or artefacts they shouldn't.  For example, adding a roster of Soulblight Gravelords, Nighthaunt, and/or Ossiarch Bonereapers forces in any combination will allow units to take from each others spell lores. Chaos factions seem to be the other main offender here.

**Comment by cartag** [comment]
Are you taking multiple root level forces, or are you meaning when you add in forces as ally or coalition? If you can provide steps to replicate that will be super helpful.

**Comment by exaegrum** [comment]
Root level forces is where artefacts and multiple spell lores become an issue. Looking into it further there seems to be some issues with allies too - Lady Olynder and Arkhan can take from the Lore of the Deathmages(but nobody else can, and they can't take the lores of their own factions) if allied into SBGL, and everyone in SBGL(but not other factions like OBR) can take from the Lore of the Underworlds(and not their own factions) if allied or coalitioned into Nighthaunt.

**Comment by exaegrum** [comment]
If I had to guess, the issue with Lady Olynder and Arkhan taking the lore as allies is that they're MORTARCH keyworded. No idea what's up with the rest.

**Comment by cartag** [comment]
Multiple root level forces aren't legal, and the entire game structure is built around having a singular root level force. I'm willing to bet that is the reason you're having these issues, as most checks look for the Allegiance selection for your army. If you have multiple root level forces, it will add an Allegiance entry for each one, throwing things off. Try restructuring your list to one root level force and the others as allies or coalition and see if that still has a problem. 

As for others, I'll research more tomorrow.

**Comment by exaegrum** [comment]
Ah, that makes sense. I had presumed it was set up to allow multiple roots for things like Coalition of Death, so you could add each teammates decklist to the same roster.
With allies and coalition, I only had the issues I mentioned with the mortarchs getting SBGL lore and SBGL getting nighthaunt lore. Everything else I tested seemed to work as intended.

**Comment by cartag** [comment]
All of the spell lores are based off of allegiance for visibility, I'm unable to duplicate issues. Can you please give steps to duplicate the issue?

**Comment by exaegrum** [comment]
1) Create a Nighthaunt force.
2) Add a Soulblight Gravelords force as allies. This also happens with them added as coalition, but that's not legal anyway.
3) Add a Soulblight Gravelords wizard to the roster.

They will have the Lore of the Underworlds as an option to choose from.
![image](https://user-images.githubusercontent.com/87075757/125164638-4a539100-e161-11eb-9970-eab6b38e08f7.png)

**Comment by cartag** [comment]
Fixing in next release.
