### ISSUE TITLE
Vokmortian's Retinue

### ISSUE THREAD

**Issue by exaegrum** [BSData/warhammer-age-of-sigmar#2028]
While the three Ossiarch Bonereapers battalions from White Dwarf have been disabled due to no longer being legal, there's a copy of "Vokmortian's Retinue" left that should simply be deleted - it's incorrect to begin with in addition to the battalion it was supposed to be not being legal.

**Comment by cartag** [comment]
Vokmortian's Retinue was from the Feast of Bones box. It's left in for open play. https://github.com/BSData/warhammer-age-of-sigmar/issues/1138

**Comment by exaegrum** [comment]
Should the WD ones not be left in for open play then?

**Comment by cartag** [comment]
The others shouldn't have been removed, just locked to one particular sub faction, if my understanding of the OBR file is correct.
