### ISSUE TITLE
Cities of Sigmar - Tempest Eye and Living City Coalition Units

### ISSUE THREAD

**Issue by BassyDave** [BSData/warhammer-age-of-sigmar#2030]
When selecting a Stronghold of Order that has a Battle Trait that grants it access to coalition units from other factions (Tempest Eye/Kharadron Overlords and Living City/Sylvaneth), should the respective units show up in the unit selection lists to be added to the roster?

Apologies if this is a feature change, but I could have sworn I'd seen the units in there recently without having to add the force separately when creating the roster.

**Comment by cartag** [comment]
This changed with the new edition, you will need to add a Coalition sub-force for them. So when creating a Tempest Eye list, you will want to add a second force for KO or SCE, selecting the existing CoS force as the parent force for it. 
![image](https://user-images.githubusercontent.com/4388344/125109738-f5e8dc80-e0a0-11eb-9891-3c776aad191d.png)
