### ISSUE TITLE
Daughters of Khaine Artifact Error

### ISSUE THREAD

**Issue by Stringo164** [BSData/warhammer-age-of-sigmar#2043]
When making a DoK list, I have a warlord battalion w/ the extra artefacts of power enhancement. But when I add the extra artifact I am getting an error that there are to many selected artifacts.

**Comment by cartag** [comment]
This should have been fixed with the latest release. Can you please update your data, try to create it again, and report back if it is still having the problem? Steps to duplicate will be helpful also if it's still happening.

**Comment by Stringo164** [comment]
It is fixed with the update!

**Comment by cartag** [comment]
Thanks for the bug report and for letting me know it's taken care of!
