### ISSUE TITLE
Daughters of Khaine Zainthar Kai Artefact Issue

### ISSUE THREAD

**Issue by acovarru91** [BSData/warhammer-age-of-sigmar#2049]
When selecting Zainthar Kai as a temple, you receive an error when including 2 artifacts. With Zainthar Kai you are able to give a hero an extra artefact. Furthermore, the mandatory artefact of power Crimson Talisman is limited to Melusai heroes only. If your hero is not an Ironscale you do not have to take it. Doing this flags your roster with an error that the Crimson Talisman must be taken.

**Comment by cartag** [comment]
Resolved in next release
