### ISSUE TITLE
No error thrown when selecting multiple models to be the army general.

### ISSUE THREAD

**Issue by Valorcalls** [BSData/warhammer-age-of-sigmar#2051]
As title, I've yet to find an army list where setting any number of leader models as general throws an error.

Should be max one for an army.

**Comment by cartag** [comment]
I seriously thought this was already set up but apparently it isn't past a per-catalogue standpoint. Implementing Max 1 in roster for General category, set to -1 if instance of Multiple Generals category in list. One Slaanesh Host allows 3 generals.
