### ISSUE TITLE
Tzeentch Covens

### ISSUE THREAD

**Issue by shrykm** [BSData/warhammer-age-of-sigmar#2052]
Disciples of Tzeentch are missing being able to choose a coven under allegiance

**Comment by cartag** [comment]
It's there. Tap on Allegiance: Tzeentch if you're on mobile. On desktop, here's the proof it's there: 
![image](https://user-images.githubusercontent.com/4388344/125168464-f2b62500-e162-11eb-9f15-09e3d4f39acd.png)
