### ISSUE TITLE
Cities if sigmar does not show allied units

### ISSUE THREAD

**Issue by Khalew76** [BSData/warhammer-age-of-sigmar#2057]
Cities of sigmar does not show stormcast units available or others like the KO when you pick tempest eye. It used to on first 3 release.

**Comment by cartag** [comment]
Since the coalition system was implemented and we can enforce the 1/4 limits now, you will need to add a sub force to add coalition units. 
https://github.com/BSData/warhammer-age-of-sigmar/issues/2030
