### ISSUE TITLE
Sequitors greatmace cap incorrect

### ISSUE THREAD

**Issue by ilinxildari** [BSData/warhammer-age-of-sigmar#2060]
Reinforcement should allow for more greatmaces for a squad. battletome states 2 greatmaces for every 5 sequitors. Currently battlescribe is producing a warning error if you assign more than 2 to a squad of 10.

**Comment by cartag** [comment]
This looks like it was corrected a few days ago in #1998. I've checked the latest version of the file and it's behaving correctly in v89. V92 releasing tonight will also have the fix.
