### ISSUE TITLE
Warlord Battalion Incorrect Minimum Unit Selections 

### ISSUE THREAD

**Issue by acovarru91** [BSData/warhammer-age-of-sigmar#2071]
I have only tested this in Slaves to Darkness and Slaanesh. When i add a Warlord Core Battalion, it is flagging my roster for error regarding unit choices. It is saying Leader requires minimum 2, Sub-Commanders minimum 4, and troops minimum 2. So far it's been the same error for both armies.

**Comment by cartag** [comment]
I'm unable to duplicate this in v94 of the main file. What platform are you experiencing the issue on?

**Comment by acovarru91** [comment]
Android, mobile. As of now, i also can't seem to replicate the after deleting the roster and redoing the list.
