### ISSUE TITLE
SCE Spell Lore Update 

### ISSUE THREAD

**Issue by acovarru91** [BSData/warhammer-age-of-sigmar#2075]
Lore of Invigoration restricted to Evocators only.

**Comment by rweyrauch** [comment]
Cannot reproduce.
Lore of Invigoration is correctly available to SCE WIZARDS.
Can you provide reproduction steps?

**Comment by acovarru91** [comment]
Sorry, i wrote this poorly. Lore of Invigoration is now restricted to Evocators only per recent FAQ.

**Comment by rweyrauch** [comment]
Thanks.  Missed that part of the FAQ.
