### ISSUE TITLE
Slaanesh Invaders Command Traits

### ISSUE THREAD

**Issue by acovarru91** [BSData/warhammer-age-of-sigmar#2085]
You receive a roster error when selecting a universal command trait for your general.  It is flagging having at least 1 Obsession of the Invaders as mandatory.

**Comment by Valorcalls** [comment]
This is intended behavior, as per the core rules.

**Comment by acovarru91** [comment]
Slaanesh subfactions do not have mandatory command traits. Any Slaanesh general can have access to universal command traits.

**Comment by cartag** [comment]
I'm fixing it.
