### ISSUE TITLE
Soulblight Gravelords Extra Enhancement: Spell Lores - Lore of the Vampires

### ISSUE THREAD

**Issue by werefoofle** [BSData/warhammer-age-of-sigmar#2090]
When taking the Extra Enhancement: Spell Lores option from a Core Batallion, a roster validation error occurs if you try to take two spells from the Lore of the Vampires. This roster validation error does not occur with the Lore of the Deathmages, the Universal Spell Lore, or when mixing spells from multiple lores, so I believe it is a mistake with the Lore of the Vampires.
![Capture2](https://user-images.githubusercontent.com/79936725/125691895-7fcb5d6b-9259-4da7-b7f1-e4a096e65361.PNG)

**Comment by cartag** [comment]
Thanks for reporting this bug! It will be fixed in the next release.
