### ISSUE TITLE
Coalition in tempest eye and KO does not let you pick adjutant or general

### ISSUE THREAD

**Issue by Khalew76** [BSData/warhammer-age-of-sigmar#2098]
Using a coalition with tempest eye cities of sigmar army with the KO does not let you set the general or adjutant as a KO character

**Comment by cartag** [comment]
Coalition unit cannot be added as General, per the Cities of Sigmar FAQ. Adding Adjutant in all coalition armies later today.

**Comment by cartag** [comment]
Adjutant already set in KO catalogue for CoS main force.
