### ISSUE TITLE
Lumineth conditional battleline (almost there!)

### ISSUE THREAD

**Issue by DaveHSheff** [BSData/warhammer-age-of-sigmar#2138]
The selection of conditional battleline units is now working fine, but Sentinels and Dawnriders can still be double reinforced when they are not battleline. The Battleline condition for Reinforced max number of selections is missing.

Thanks

**Comment by cartag** [comment]
Modified them to only set conditional if ancestor instance of conditional battleline. Also changed Bladelords condition to similar, just to make future maintenance easier.
