### ISSUE TITLE
Sylvaneth issues

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/warhammer-age-of-sigmar#214]
- [x] Tree-revenants should be 80/420, not 90/430.
- [x] Weapon options on Kurnoth Hunters are incorrect, they should have a choice between bows and quiverlings, swords or scythes, not bows _plus_ one of the others.
- [x] Spite-Revenants points are incorrect, they should be 80/420, not 160/500.
- [x] None of the units have their weapons in SEs as per the guidelines.
- [x] Drycha's colony/swarm option should be max 1 in Parent.
- [x] Dryads should be 100/270, not 100/300.

**Comment by FreylisUK** [comment]
I'll get on this next...

**Comment by FreylisUK** [comment]
Fixed in #216
