### ISSUE TITLE
Only 1k or 2k lists selectable

### ISSUE THREAD

**Issue by ilinxildari** [BSData/warhammer-age-of-sigmar#2158]
we now have guidance for +/- 500 point games. I can't seem to find points variations as an option either like there used to be.

**Comment by cartag** [comment]
Pitched Battles in GHB 2021 only has two levels of games, 1000 and 2000. Conquest of Generals/Matched Play from the rule book has five points levels. Conquest of Generals will have all points levels available at the next release.
