### ISSUE TITLE
Strange behavior reinforcing battleline units in StD and BoC.

### ISSUE THREAD

**Issue by salmelo** [BSData/warhammer-age-of-sigmar#2161]
When reinforcing Battleline units from a BoC or StD army, the number field jumps directly from 0 to 2 if you click the up button, and jumps directly back to 0 if you click the down. You can manually type a 1 in the box and that works.
Additionally, some units don't correctly update the model count: Gors and Ungors will continue to say 10 regardless of the reinforcement count, and Chaos Knights will only double up to 10, they won't triple to 15. Varanguard double to 6 but stays at 3 instead of tripling to 9.
Chaos Chariots, specifically, will skip 1 when clicking the up button but will hit it when clicking the down button.

**Comment by cartag** [comment]
The numbers not incrementing/decrementing as they should is a wonderful BS bug that has surfaced affecting 40k files as well. I'm not sure of the reason for it yet or how to prevent it from happening. 

Updating Chaos Knights, Varanguard, and Chariots names.
