### ISSUE TITLE
Slaanesh StD Coalitions and Allies missing Battleline Units

### ISSUE THREAD

**Issue by salmelo** [BSData/warhammer-age-of-sigmar#2162]
Chaos Chariots aren't listed as Battleline units in any StD Coalition/Allied forces under a Slaanesh army. Allied (not Coalition) StD forces under a Pitched Battle 2021 Slaanesh Army, specifically, are also missing Chaos Marauders and Chaos Warriors.

**Comment by rweyrauch** [comment]
Per the Matched Play rules, Allied units are never Battleline.

**Comment by salmelo** [comment]
They still have the Battleline role, they just don't count towards the number your required to take. It's an important distinction because you could still reinforce them twice if you wanted and, less relevant for battlescribe, it matters for some grand strategies and battle tactics. Also, coalition units aren't restricted at all in Contest of Generals.

**Comment by rweyrauch** [comment]
Currently discussing how to implement this on the aos-development channel on Discord.  Stay tuned.

**Comment by cartag** [comment]
Corrected in next release
