### ISSUE TITLE
Contest of Generals army validation

### ISSUE THREAD

**Issue by zmaltais** [BSData/warhammer-age-of-sigmar#2169]
This was addressed on reddit, however, I am adding an issue here for tracking.

You cannot select anything between 1000 and 2000 points for `Contest of Generals` causing list validation to fail. 

[Thread here, which includes screen caps and steps to reproduce.](https://www.reddit.com/r/BattleScribe/comments/ososcc/aos_contest_of_generals_defaults_to_1000_points/)

**Comment by cartag** [comment]
Already corrected, fix will be live with next release.
