### ISSUE TITLE
Skaven? which cat file?

### ISSUE THREAD

**Issue by Mikle103** [BSData/warhammer-age-of-sigmar#218]
Hey All, 

Grate work i have just got back into the game after a long break, with the release of 40K 8th i have been using BS for list building and wish to do same with AoS.

So I am trying to rebuild my skaven army for AoS but cannot find the catalog they are in???

have downloaded branch data AoS-2.0 by Oftkilted

Ant help would be good.

**Comment by Mikle103** [comment]
Never mind found it.

**Comment by OftKilted** [comment]
The 2.0 catalogs are currently in the process of being built. Points totals, validation etc. will likely have issues. While some catalogues are in good shape, we have not yet reached a release.

**Comment by OftKilted** [comment]
No worries @Mad-Spy is currently splitting the Skaven catalog out of the Chaos catalog. 
So updates are in progress. 👍
