### ISSUE TITLE
Core Battalions

### ISSUE THREAD

**Issue by Rahjiskar** [BSData/warhammer-age-of-sigmar#2184]
It should be possible to select two Core Battalions for the same unit. An error appears if it is done, however:

Page 88 of the GHB 2021 does says that: "Usually, a unit can only belong to one battalion. However, some very large battalions include other, smaller battalions. In this case, it is possible for a unit to belong to two different battalions at the same time."

**Comment by cartag** [comment]
By "some large battalions" they're meaning warscroll battalions that have other warscroll battalions included in them, or core battalions that have other smaller core battalions in them. As it stands, there are no core battalions that offer this functionality. Closed as invalid.
