### ISSUE TITLE
Order - Kharadron Overlord Thunderer Weapons Limits

### ISSUE THREAD

**Issue by OftKilted** [BSData/warhammer-age-of-sigmar#219]
Grundstock Thunderers can take 2 weapon choices for each model in the unit. (i.e. 5 Thunderers can take 10 weapons?) 

Multiple weapons (including Arkanaut Cutter and Arkanaut Privateer Pistol) missing SE for Arkanaut Company and most units are missing the SE for weapons in unit entries.

**Comment by FreylisUK** [comment]
Fixed.
