### ISSUE TITLE
Soulblight gravelord errors

### ISSUE THREAD

**Issue by DoomAdept** [BSData/warhammer-age-of-sigmar#2207]
Just ran into two issues. First, Deadwalker Zombies seem to be incorrectly categorised as 'other' instead of 'battleline'. Second, Kosargi Nightguard cause an error to be displayed saying that you cannot have more than one squad of them, which as far as I can tell from the gw faq displaying the new separate profiles for radukars' court, isn't correct.

**Comment by rweyrauch** [comment]
Zombie battleline issue resolved in #2191.
