### ISSUE TITLE
Seraphon Thunder lizard 

### ISSUE THREAD

**Issue by TemplarMarx** [BSData/warhammer-age-of-sigmar#2209]
When attempting to make detachemnts using thunder lizard stegadon it is not removing the behemoth keyword. In these faction they should loss that and gain the battleline not have both.

**Comment by rweyrauch** [comment]
Duplicate of #2201.
Fixed.

**Comment by TemplarMarx** [comment]
I have updated my data however they still have the behemoth keyword
