### ISSUE TITLE
Thunder lizard behemoth keyword

### ISSUE THREAD

**Issue by TemplarMarx** [BSData/warhammer-age-of-sigmar#2212]
seraphon stegadon is keeping the behemoth keyword and that is stopping you from putting it into the troop option for detachments. This was tagged as duplicate and resolved however all that has been resolved is that it's working and you can put them in the battleline role however its keeping the behemoth as well and that is what's causing the problem.

**Comment by cartag** [comment]
It has been resolved, and in the latest version of the file, v85, you will see it is corrected. After a release is pushed it can take up to 12 hours for Appspot to catch up and actually acknowledge the release. A small bit of patience is required here. If there were any way to speed up the process of releases we would. It's beyond our control.

**Comment by TemplarMarx** [comment]
Oh ok thank you did not know about the up to 12 hours thanks.

**Comment by TemplarMarx** [comment]
Ok thank you I just didnt want what I was seeing to be ropped in with the previous issue. Didnt know about the 12 hours wait potentially. Thanks Sent from my Sprint Samsung Galaxy S8+.
-------- Original message --------From: cartag ***@***.***> Date: 8/8/21  4:53 PM  (GMT-06:00) To: BSData/warhammer-age-of-sigmar ***@***.***> Cc: TemplarMarx ***@***.***>, Author ***@***.***> Subject: Re: [BSData/warhammer-age-of-sigmar] Thunder lizard behemoth keyword (#2212) 
It has been resolved, and in the latest version of the file, v85, you will see it is corrected. After a release is pushed it can take up to 12 hours for Appspot to catch up and actually acknowledge the release. A small bit of patience is required here. If there were any way to speed up the process of releases we would. It's beyond our control.
