### ISSUE TITLE
Core Battalion: Linebreaker - Order - Seraphon v85 - Stegadon - Thunderlizards

### ISSUE THREAD

**Issue by dukemadcat** [BSData/warhammer-age-of-sigmar#2216]
Not sure if this is related to issue #2212.

Maybe I forget something about the rules but as far as I understand a Thunderlizard Stegadon may become Battleline but is also a Monster that is not a Leader so it should be possible to select it for a Linebreaker Monster slot. Correct?

I just updated my data and I am using **Order - Seraphon v85**. With this version this is not possible.

**Comment by cartag** [comment]
Monster slot is officially Behemoth that is not a Leader. If it is battleline, it is no longer a behemoth. If it is a Behemoth, it is eligible for the Monster slot, and confirmed it is available in the current file.

**Comment by dukemadcat** [comment]
Thanks for the clarification 😅
