### ISSUE TITLE
Lumineth Realm Lords

### ISSUE THREAD

**Issue by Elitzer** [BSData/warhammer-age-of-sigmar#2258]
**Description of the bug**
There are options on the scinari cathalar played has a leader to select Great Nation Artefacts and Commands but since there is nowhere to chose a Great Nation since the last update, these sections are blank.

**Expected behavior**
There should be a way to select a Great Nation and then the list would be filled

**Comment by cartag** [comment]
You select a Great Nation the same way you select a subfaction for any army.  
![image](https://user-images.githubusercontent.com/4388344/131772027-4c55a156-33a7-4731-848c-9073d7459e0e.png)
