### ISSUE TITLE
Allied units issues

### ISSUE THREAD

**Issue by exaegrum** [BSData/warhammer-age-of-sigmar#2259]
Hello! Allied units currently can still select an enhancement such as a spell lore(universal or keyworded, in the case of Olynder and the Deathmage lore), or an artefact. In addition, you can currently select an allied unit as a general and if you do, you can give it a command trait. Allied units should not be able to be selected as generals, nor should they be able to take any enhancement.

**Comment by cartag** [comment]
General should be set to hide if it's an allies or coalition force. I have a feeling it's not in some files though. Judging by your comments, Soulblight Gravelords are one especially affected.

**Comment by cartag** [comment]
I'll have to go through the catalogs one by one to fix this, next release will be a little while.

**Comment by mgm1675** [comment]
Yeah - I tend to test things with Death because I'm sure of what's supposed to be there, and I'm using them most so that tends to be where I notice them first.

**Comment by cartag** [comment]
> I'll have to go through the catalogs one by one to fix this, next release will be a little while.

I lied, it didn't take as much effort as I thought once I figured how to streamline it. Will be in next release.
