### ISSUE TITLE
Orruk mob (legends) not showing up in an allied force

### ISSUE THREAD

**Issue by Gingrel** [BSData/warhammer-age-of-sigmar#2261]
I made a Gitz force with allied Orruk Warclans and I noticed the Orruk Mob didn't show up in any category.

Quoting car_tag from discord: "It's a remnant of a fix we did to make Coalition battleline count toward the limit before they FAQd it"

"If you could open an issue that would be good, I'll need to make a sweep of all legends to make sure it's fixed for all"

**Comment by cartag** [comment]
Corrected in next release.
