### ISSUE TITLE
Kharadron Overlords: wrong profile for Endrinriggers' Aethermatic Saw

### ISSUE THREAD

**Issue by maguerrieri** [BSData/warhammer-age-of-sigmar#2266]
Endrinriggers' saws should only have 1 attack each, but currently have 3. I guess they incorrectly have the Endrinmaster's saw instead of their own profile?

**Comment by cartag** [comment]
Endrinriggers Aethermatic Saws only have Attacks of 1 in current data file. 

![image](https://user-images.githubusercontent.com/4388344/132251816-1d0dcee1-3100-43d4-b8fb-64508b05311b.png)

**Comment by maguerrieri** [comment]
Huh. Is it possible that this was an issue in migrating from a previous version, or something? In any case, for taking a look!
