### ISSUE TITLE
Soulblight Gravelords - Additional Generals Validation Error

### ISSUE THREAD

**Issue by DelothVyrr** [BSData/warhammer-age-of-sigmar#2269]
**Describe the bug**
Many Soulblight Gravelord named characters allow them to be an additional army General when taken as part of their Dynasty. However, these named characters are not listed as a General, and selecting them as General in addition to the standard General comes up as a validation error.

**To Reproduce**
1. Choose Kastelai Dynasty
2. Add an un-named character to the roster and make them General
3. Add Prince Vhordrai to the roster
4. Vhordrai should also be counted as a General but is not, and selecting General for him gives an error

**Expected behavior**
Named characters in their respective dynasty should be made a General automatically, or be allowed to select it even if another character is also the General.

**Device and data (please complete the following information):**
 - All devices
 - Warhammer Age of Sigmar 3.0.22

**Comment by cartag** [comment]
There will be a new checkbox for Count As General that will only be visible when you have the appropriate sub-faction selected.
