### ISSUE TITLE
Seraphon missing grand strategy

### ISSUE THREAD

**Issue by sedulam** [BSData/warhammer-age-of-sigmar#2285]
Seraphon data does not show grand strategy

**To Reproduce**
Create roster with Seraphon GHB 2021. 
Check grand strategy is not present 
Try to add grand strategy

**Expected behavior**
To have the grand strategy when I create the roster, or to be able to add it. 

**Device and data (please complete the following information):**
 - OS: Android 
 - BattleScribe version 2.03.25
 - Release version Seraphon v91

**Comment by cartag** [comment]
Fix already uploaded, just no release has been pushed yet.
