### ISSUE TITLE
Skaven Stormfiends

### ISSUE THREAD

**Issue by RatRiot** [BSData/warhammer-age-of-sigmar#2295]
**Describe the bug**
Stormfiends has the "CLANS MOULDER" Keyword on the new Warscroll and needs an Update on Battlescribe (checked it on the gw Homepage and the new AoS App)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device and data (please complete the following information):**
 - BattleScribe version [e.g. 2.03.45]
 - Release version [e.g. v1.2.3]

**Additional context**

**Comment by cartag** [comment]
The Stormfiends have to have a workaround keyword, they are shown having STORMFIENDS MOULDER and STORMFIENDS SKRYRE instead of CLANS MOULDER and CLANS SKRYRE, this is due to a limitation with Battlescribe. They still have the right keywords, they just have to be listed a bit differently.
