### ISSUE TITLE
Bug Report - Stormcast Eternals - Glitches

### ISSUE THREAD

**Issue by plavski** [BSData/warhammer-age-of-sigmar#2296]
**Describe the bug**
Knight-Judicator with Gryph-hounds - 135 points in BS, 205 points in book.
Aetherwings - 45 points in BS, 65 points in book.
Knight Draconis - 175 points in BS, 255 in book.
Knight Relictor - 175 points in BS, 140 points in book.
Dais Arcanum - 30 points in BS, 55 in book
Celestian Vortex - 30 points in BS, 80 in book
Everblaze Comet - 110 points in BS, 100 in book

Sequitors are missing battleline role

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device and data (please complete the following information):**
 - OS: Windows
 - BattleScribe version: 2.03.21
 - Release version: v112

**Additional context**

**Comment by rweyrauch** [comment]
Thanks for the excellent bug report and help in QA on the catalogs.
