### ISSUE TITLE
Bug Report - Stormcast Eternals - Auto add Faithful Gryph Hound

### ISSUE THREAD

**Issue by plavski** [BSData/warhammer-age-of-sigmar#2303]
**Describe the bug**
When creating a new Stormcast Eternals list, the Faithful Gryph-Hound is auto-added in the Other category.

**To Reproduce**
1. Create new SCE list for GHB 2021

**Expected behavior**
No units in list

**Actual behaviour**
Faithful Gryph-hound appears automatically

**Screenshots**
![image](https://user-images.githubusercontent.com/15157275/133940909-c99df5a6-1c57-4eeb-8fa8-1440cea2876e.png)

**Device and data (please complete the following information):**
 - OS: Windows
 - BattleScribe version: 2.03.21
 - Release version: v112

**Comment by cartag** [comment]
Already fixed.

**Comment by cartag** [comment]
It'll be in the next release.

**Comment by plavski** [comment]
Was it fixed in 113? I'm using that release now and it still happens.

**Comment by cartag** [comment]
Oh motherf... that bug snuck back in, sorry. I'll get it fixed for the next release.
