### ISSUE TITLE
Bug Report - Stormcast Eternals - Unable to assign Holy Command unique enhancement

### ISSUE THREAD

**Issue by plavski** [BSData/warhammer-age-of-sigmar#2305]
**Describe the bug**
Cannot assign a Holy Command command ability unique enhancement (p. 111)

**To Reproduce**

1. Make new SCE list
2. Add general

**Expected behavior**
Option to add Holy Command command ability

**Actual behaviour**
No option for Holy Command appears on general, nor available in options

**Screenshots**
![image](https://user-images.githubusercontent.com/15157275/133944016-e5234f4f-9dec-43b2-9f68-b245fae11557.png)
![image](https://user-images.githubusercontent.com/15157275/133944024-f9033795-605c-4484-810f-e88e7b663a6f.png)

**Device and data (please complete the following information):**

OS: Windows
BattleScribe version: 2.03.21
Release version: v113

**Additional context**
Note: You are also unable to select another Unique Enhancement via the Magnificent battallion option.

**Comment by rweyrauch** [comment]
Partially implemented by #2318.

Limits not implemented correctly.
