### ISSUE TITLE
Bug report: Destruction - Orruk Warclans.catz - Mount Traits

### ISSUE THREAD

**Issue by CptNonsense** [BSData/warhammer-age-of-sigmar#2331]
Describe the bug
Unique mounted units can be given mount traits, when they are forbidden from getting them via the core book (Enhancements 27.3).  Identical to issue #2330  but for Orruks

To Reproduce:
1.  Create Orruk Warclans list
2.  Add Gordrakk

Expected behavior
- No mount traits available

Actual behavior
- Mount traits available

Device and data (please complete the following information):
-  OS: Android
-  BattleScribe version: 2.03.25
-  Release version: v115

Notes
- May have been an overcorrection from issue #2324.  Unique character Swampboss Skumdrekk should not, in fact, have mount traits.

**Comment by rweyrauch** [comment]
Over correction indeed.
