### ISSUE TITLE
Stormcast Eternals 3.0 Point Values Incorrect sent to BattleScribe

### ISSUE THREAD

**Issue by EpicGamerGeek** [BSData/warhammer-age-of-sigmar#2377]
**Describe the bug**
Point values under Warhammer AoS 3.0 do not match what is shown by Games Workshop importing into latest version of BattleScribe.

Please update unit points

**Comment by cartag** [comment]
Can you elaborate as to which unit's points are off?

**Comment by cartag** [comment]
You really need to update your data files then, there was a massive update to the data when that book was released. It was literally released the same day as the book. Update your data and try again, then report back if it's still wrong.

**Comment by EpicGamerGeek** [comment]
Hi

 

Thanks for the reminder to update data.

When I attempt to update it, I get the following error in BattleScribe:

**Comment by cartag** [comment]
Have you been able to update? Do you have any points discrepancies to report after the update?

**Comment by EpicGamerGeek** [comment]
Hi

I apologize for not getting back to you.   I blew away the app on my PC and downloaded a new copy and ran the data updates.  All is good now.

Thank you for your assistance.

Dave
