### ISSUE TITLE
Daughters of Khaine Temple selection

### ISSUE THREAD

**Issue by AllHailMorathi** [BSData/warhammer-age-of-sigmar#2420]
So im trying to build my Daughter's of Khaine list and there is no way for me to select my temple (Hagg Nar, Draichi Ganeth, The Kraith, Khailebron,  Khelt Nar, Zainthar Kai.) So I was hoping for convenience sake that this selection could be added in, as they give different command traits to your general among other things

**Comment by cartag** [comment]
It's literally one of the things that fills in when you first build the list.
![image](https://user-images.githubusercontent.com/4388344/140171987-fed5ca34-bd80-437a-8fae-bc1c3d435548.png)

**Comment by AllHailMorathi** [comment]
I'd like to know where because it's not displayed.

**Comment by cartag** [comment]
Under Allegiance, I've circled it in this second picture to help you out. 
![image](https://user-images.githubusercontent.com/4388344/140232603-cb6df4c4-5198-4785-92a0-11f7e7ae130a.png)

**Comment by cartag** [comment]
If you're on mobile, look under Allegiances. It's already there, I promise.

**Comment by AllHailMorathi** [comment]
Sorry must have been a bug or something because when I fallowed the path
you displayed it just wasn't doing anything. I restarted my phone and now
it's working fine. I don't know what was going on there.
