### ISSUE TITLE
Steam Tanks And Monster Battlescroll

### ISSUE THREAD

**Issue by OrsingerI** [BSData/warhammer-age-of-sigmar#2421]
Error:

As per the core Battalion rules (26.3) as to what defines the monster role, I should be able to select Cities of Sigmar steam Tanks for things like "Alpha Best pack" and "Line Breaker" as they qualify as "Behemoth that is not Leader".  I can't do this if I have a Steam Tank Commander as the general as the steam Tanks become battle line and that apparently causes them to conflict

**Comment by OrsingerI** [comment]
I apologize as i'm newer to AoS list building. But is the Steam Tank W/ Commander meant to take 2 leader slots? Right now, if i choose 3 Steam Tanks w/Commander, i no longer have any Leader Slots available

**Comment by cartag** [comment]
It shouldn't have taken up two slots, that's a good find. Thanks for reporting the issue!

**Comment by OrsingerI** [comment]
A genuine thank you for doing what you do.

**Comment by OrsingerI** [comment]
Also, Cogsmiths: there seems to be an Extra ability that might be a hold over from previous editions

**- Engineer	In your hero phase, a Cogsmith can repair a single WAR MACHINE within 4". That model repairs 1 wound.**
- Master Engineer	In your hero phase, you can pick 1 friendly IRONWELD ARSENAL WAR MACHINE unit within 3" of this model. You can heal up to D3 wounds allocated to that unit.

Where do they get that first engineer ability? It's not on the warscroll nor in the core rules.
