### ISSUE TITLE
Missing Characters in Legion of the First Prince

### ISSUE THREAD

**Issue by Snnugies** [BSData/warhammer-age-of-sigmar#2424]
After the last update the following characters from Monstrous Arcanum have been lost in the warp:
-Exalted greater demon of Khorne
-Exalted greater demon of Nurgle
-Exalted greater demon of Tzeentch
-Mazarall the Butcher
-Skaarac thr Bloodborn
-Soulfeaster Keeper of Secrets

Probably they just need to be listed and referenced

**Comment by cartag** [comment]
Those are ineligible for Legion of the First Prince as they are not from any of the listed battletomes eligible for LotFP. They were included by mistake at first.

**Comment by cartag** [comment]
If you have arguments for their inclusion that can be backed up by GW literature, I'm receptive to it, that's why I'm leaving this open for the time being.

**Comment by Snnugies** [comment]
True. By definition they cannot be included since they are not part of the battletomes. My bad, should have checked it better. Thanks for your work.

**Comment by cartag** [comment]
Thank you for submitting the bug report in the first place! It is appreciated, and I hope you continue to report any other bugs you find in the future!
