### ISSUE TITLE
Coallition forces requiring additional selections of Allegiance and Grand Strategy

### ISSUE THREAD

**Issue by ZeeIsMee** [BSData/warhammer-age-of-sigmar#2434]
**Describe the bug**
I'm trying to build a Barak-Thryng army but when I add a coalition unit it tells me I need to select an Allegiance and Grand Strategy. When I add those in, it tells me I have too many Allegiance and Grand Strategy selections.

**To Reproduce**
1. Go to force selection
2. Add a new force as coalition
3. See error

**Expected behavior**
A coalition force is added without requiring additional Allegiance and Grand Strategy selections

**Screenshots**
Screenshots taken on mobile, bug present on both mobile and PC
https://imgur.com/a/thuczkt

**Device and data (please complete the following information):**
 - OS: Android and Windows 10
 - BattleScribe version: 2.03.21
 - Release version v3.0.38

**Comment by cartag** [comment]
Thank you for reporting the issue! I saw your Reddit post earlier. All of the factions have been updated now to resolve the issue. The fix will be live with our next release.

**Comment by cartag** [comment]
#2432

**Comment by ZeeIsMee** [comment]
> 
> 
> Thank you for reporting the issue! I saw your Reddit post earlier. All of the factions have been updated now to resolve the issue. The fix will be live with our next release.

That was fast! Thank you so much for the response.
