### ISSUE TITLE
Soulfeaster Keeper warscroll errors

### ISSUE THREAD

**Issue by jessicagaylord** [BSData/warhammer-age-of-sigmar#2447]
**Describe the bug**
Soulfeaster Keeper of Secrets warscroll has issues relating to spell lores, abilities, etc.

**To Reproduce**
1. Go to Chaos - Slaanesh database
2. Click on Soulfeaster Keeper of Secrets warscroll
3. View

**Expected behavior**
Soulfeaster should be able to select from two Slaanesh spell lores, and the Dark Temptations CA should be changed to a normal warscroll ability. Additionally, it should list the weapon profile for the Sinistrous Hand.

**Screenshots**

**Device and data (please complete the following information):**
 - BattleScribe version [e.g. 2.03.45]
 - Release version [e.g. v1.2.3]

**Additional context**

**Comment by cartag** [comment]
Thanks for reporting the bug! It will be in the next release.
