### ISSUE TITLE
Death - Ossiarch Bonereapers: Subfaction Artefact Validation

### ISSUE THREAD

**Issue by exaegrum** [BSData/warhammer-age-of-sigmar#2469]
Currently, selecting an Ossiarch Bonereaper subfaction will throw a validation error requiring you to select that legion's artefact. While these artefacts are required to be the first one chosen, this should not throw an error if you have not taken any artefacts(the most likely case being running only unique heroes). 

Expected behavior would be for it only to be required as the first one - i.e. to be selected before taking any others.

v3.0.42

**Comment by cartag** [comment]
Covered by #2472
