### ISSUE TITLE
Death - Nighthaunt: Artefact issues

### ISSUE THREAD

**Issue by exaegrum** [BSData/warhammer-age-of-sigmar#2470]
Nighthaunt currently has several artefact issues.

1) Corpse Candle is mandated for the Reikenor's Condemned subfaction or it will throw a validation error. This should only be required as the first artefact, not a requirement for validation if you took no artefacts(i.e. have only unique heroes).

2) Conversely, the Emerald Host subfaction has no validation for the Traitor Knight's Blade. This should be the first artefact you need to give to a KNIGHT OF SHROUDS(note that you can take other artefacts first if you give them to something that does not have a KNIGHT OF SHROUDS keyword)

3) Both of the aforementioned artefacts are oddly situated - the Corpse Candle is tacked onto Relics of the Underworlds, while the Traitor Knight's Blade is a selection box like General is. I would expect these to get their own category, as "Artefacts - Processions" or something of the sort, following convention.

4) There is a "Malign Portents Artefacts - Knight of Shrouds" category. It contains a single artefact, the Balefire Blade. This is a duplicate of an artefact in Weapons of the Damned.

5) The aforementioned Balefire Blade(in both categories) has a [...] prefixing its description

v3.0.42

**Comment by cartag** [comment]
1) No factions have a logic to check if there are only unique characters in a list. It's a fact of the implementation as a whole. If you want to do hop on discord and talk to us, but it's not worth the effort to implement it across the repo. 

2) It was a minor fix so I did it

3) No major redesign will be done until after the book drops, which wiill be soon

4) Deleted 

5) Deleted
