### ISSUE TITLE
Death - Ossiarch Bonereapers: Prettyscribe spell lore issue still present

### ISSUE THREAD

**Issue by exaegrum** [BSData/warhammer-age-of-sigmar#2481]
Someone previously mentioned an issue with Prettyscribe duplicating spell lores on Nagash and Arkhan. Despite their spell lore selection having been changed, this is still the case. Moreover, Arkhan's spell lore has a typo, and the spells do not show up in "Spells Known."
![image](https://user-images.githubusercontent.com/87075757/146582895-52c43f68-4d4f-4214-be1d-fab4674f5969.png)
![image](https://user-images.githubusercontent.com/87075757/146582916-fc8d0378-699f-4937-b7e3-246a78207085.png)

Latest files pulled from Github.

**Comment by exaegrum** [comment]
Addendum: also an issue in Soulblight Gravelords.

**Comment by rweyrauch** [comment]
You should post Prettyscribe issues here: https://github.com/rweyrauch/PrettyScribe/issues.
