### ISSUE TITLE
Widespread subfaction enhancement issues still present

### ISSUE THREAD

**Issue by exaegrum** [BSData/warhammer-age-of-sigmar#2483]
Readding #2472, as #2479 did not address the issue.

Upon selecting a subfaction with a designated command trait and/or artefact, these enhancements will be required to properly validate. This should not be the case, as they should only be required to be the first ones selected, not mandated if you do not have any. This issue appears across all factions with enhancements like this, as far as I can tell.

![image](https://user-images.githubusercontent.com/87075757/146584318-05a84713-c2d3-43d9-8b40-afa49ecf54fe.png)

Latest files from Git.

**Comment by cartag** [comment]
This simply isn't going to done across all armies. Most people play armies without unique characters and thus can validate a list properly. With AoS 3.0 seeming to focus less on subfaction artefacts (no battletome yet has had them) I'm just going to close this as it will eventually clear itself up as new books come out.
