### ISSUE TITLE
Chaos - Nurgle: Befouling Host battleline

### ISSUE THREAD

**Issue by exaegrum** [BSData/warhammer-age-of-sigmar#2491]
There is an issue with the Befouling Host subfaction where adding a Feculent Gnarlmaw to a list will duplicate the Beasts of Nurgle selection in Battleline.
![image](https://user-images.githubusercontent.com/87075757/146614061-d3fce3f8-ee67-40e3-813f-d638a55ce716.png)

Latest files from Git(most recent Nurgle QA pass 4)

**Comment by cartag** [comment]
This is a Battlescribe bug with duplicates showing.
