### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by warriorsoul15** [BSData/warhammer-age-of-sigmar#2517]
I would like to help maintain the bsdata files for AOS. I am familiar with git / github

**Comment by rweyrauch** [comment]
Excellent.  The help is welcome.   This is the Discord chat we use: https://www.bsdata.net/discord.   Post in the aos-development thread.

What factions do you have interest in?

**Comment by warriorsoul15** [comment]
i am on the discord already.

Stormcast,  LFP, S2D mostly
