### ISSUE TITLE
AoS 3 Gloomspite Gitz leader traits

### ISSUE THREAD

**Issue by jamievenning** [BSData/warhammer-age-of-sigmar#2535]
If a non-WIZARD, MOONCLAN keyworded leader (e.g. Loonboss on Giant Cave Squig) is given the Arcane Tome artefact then they gain the necessary keywords (MOONCLAN WIZARD) to select command traits from the Gifts of the Gloomspite list of wizard traits.  Presently, this is not available.  

Game reason(s) for this: 
- Dodgy Character trait that grants -1 to hit the git
- Upfield casting of Mystic Shield on Mangler Squigs
- Flaming Weapon
- Unbinds

Thank you for reading this.

**Comment by cartag** [comment]
Nice catch!
