### ISSUE TITLE
Lumineth sub factions and upgrades

### ISSUE THREAD

**Issue by jord9787** [BSData/warhammer-age-of-sigmar#2537]
Hey

I'm new to this but I have noticed that when making my lumineth list I don't have any options to choose my sub faction such as iliatha for example and all the corresponding sub faction wargear warlord trait etc

can this be added in please? It's the only issue I have had with this file

**Comment by cartag** [comment]
This is something that's already there. If you're on mobile, you just need to drill down on the Allegiance selection, it's a choice beneath there. Here's where it is on desktop so you can see where to find it. 

![image](https://user-images.githubusercontent.com/4388344/147624237-859c6a2e-3434-407f-b7d5-a875717aef62.png)
