### ISSUE TITLE
Blue and Brimstone Horror points

### ISSUE THREAD

**Issue by Snnugies** [BSData/warhammer-age-of-sigmar#2552]
Good day

Right now, when choosing the type of unit in the Horrors of Tzeentch unit, it shows the same cost (250) for the three options (Pink Horrors, Blue Horrors and Brimstone Horrors), when each should have it's own. The correct points is, if I'm not mistaken, 115 for 10 Brimstone Horrors and 140 for 10 Blue Horrors. This happens for both the Arcanites of Tzeentch and the Legion of the First Prince.

This probably came when changing the points for the Pink Horrors in the last update.

Thank you very much for your time and all your work

**Comment by cartag** [comment]
The points changed for Horrors of Tzeentch, not for Pink Horrors. The points value of 250 is correct, as of BATTLESCROLL: GODS & HEROES
