### ISSUE TITLE
Scintillating Traile, Mount traits, Stormcast Eternals

### ISSUE THREAD

**Issue by Peryuri** [BSData/warhammer-age-of-sigmar#2658]
Hello, i noticed today that, in the Stormcast Eternals, i'm unable to select the "Scintillating trail" Mount Trait for my heroes that can benefit from it.
I noticed first with the Tauralon, then I checked and it seems to be missing from every choice of hero with a mount.
Checking the rulebook of the Stormcast, there are no limitations that stop any mount to get the trait.
Hoping I'm doing this correctly, since it's my first bug report.
Cheers.

**Comment by cartag** [comment]
Duplicate of #2654, already resolved

**Comment by cartag** [comment]
And yes, you did do it correctly! Thanks for the bug report!
