### ISSUE TITLE
Cannot add Krondspine to battalions

### ISSUE THREAD

**Issue by JML99** [BSData/warhammer-age-of-sigmar#2670]
When building my list for Stormcast Eternals 2000 point GHB, I cannot add Krondspine to the Battle Regiment battalion (or any others).  The option is not there.
![image](https://user-images.githubusercontent.com/107063858/172430150-4f3f1234-21cc-46cb-9902-198b46a0f20f.png)

**Comment by cartag** [comment]
Thanks for the informative bug report!
