### ISSUE TITLE
Galletian Veterans keyword

### ISSUE THREAD

**Issue by exaegrum** [BSData/warhammer-age-of-sigmar#2694]
The GALLETIAN VETERANS keyword is restricted to non-mounted units. Currently, this restriction is not being applied.

**Comment by cartag** [comment]
The keyword has been added manually, which units have you found that the keyword has been applied to?

**Comment by exaegrum** [comment]
Hexwraiths (Nighthaunt) and Kavalos Deathriders(Ossiarch Bonereapers) were the two I noticed it on; I didn't check any others.
