### ISSUE TITLE
[Bug] Sylvaneth - Revenant Seekers tagged as Uncategorised

### ISSUE THREAD

**Issue by plavski** [BSData/warhammer-age-of-sigmar#2712]
**Describe the bug**
Revenant Seekers are Uncategorised when they should be Other

They also don't seem to have any abilities
![image](https://user-images.githubusercontent.com/15157275/175814338-f3e5586a-14c8-40ab-a494-7dff34cbef6c.png)

**Comment by rweyrauch** [comment]
Fixed in 3.1.2
