### ISSUE TITLE
Missing battle tactics and grand strategies

### ISSUE THREAD

**Issue by exaegrum** [BSData/warhammer-age-of-sigmar#2722]
The following battle tactics/grand strategies are missing:

Grand Strategies:
- [x] Ossiarch Bonereapers

Battle Tactics:
- [x] Beasts of Chaos
- [x] Khorne
- [x] Skaven
- [x] Slaanesh
- [x] Slaves to Darkness
- [x] Nighthaunt
- [x] Ossiarch Bonereapers
- [x] Soulblight Gravelords
- [x] Orruk Warclans
- [x] Sons of Behemat
- [x] Cities of Sigmar
- [x] Daughters of Khaine
- [x] Fyreslayers
- [x] Sylvaneth

**Comment by cartag** [comment]
Beasts of Chaos and Khorne were both there, just listed under uncategorized. Checking on the others.

**Comment by rweyrauch** [comment]
Added missing OBR White Dwarf 472 updates.

**Comment by rweyrauch** [comment]
Finished up all remaining battle tactics.
