### ISSUE TITLE
Order v2.1 Warscrolls Compendium Updates

### ISSUE THREAD

**Issue by FreylisUK** [BSData/warhammer-age-of-sigmar#273]
**Warscrolls Compendium Catalogues**
*Note: These are not required for the v2.0 release.
- [x] Bretonnia (Bretonnia (Warscrolls Compendium).cat)
- [x] Dark Elves (Dark Elves (Warscrolls Compendium).cat)
- [x] Dwarfs (Dwarfs (Warscrolls Compendium).cat)
- [x] The Empire (The Empire (Warscrolls Compendium).cat)
- [x] High Elves (High Elves (Warscrolls Compendium).cat)
- [ ] Lizardmen (Lizardmen (Warscrolls Compendium).cat)
- [x] Wood Elves (Wood Elves (Warscrolls Compendium).cat)

**Comment by rweyrauch** [comment]
Lizardmen catalog included in issue #204.
