### ISSUE TITLE
Missing Bastian Carthalos Entry

### ISSUE THREAD

**Issue by jmlob** [BSData/warhammer-age-of-sigmar#2735]
Missing Bastian Carthalos Entry In Catalog

**Comment by cartag** [comment]
Do you mean Lord-Commander Bastian Carthalos? 

![image](https://user-images.githubusercontent.com/4388344/176344176-0720df26-648c-4770-aa3f-412a9aec3987.png)

**Comment by jmlob** [comment]
Sorry I am such and idiot. Side note, I cloned the AOS repo, but not sure how best to contribute to the data files. There is a mention of a db editor but not sure if it is available on a Mac build of battle scribe. 


Sent from Yahoo Mail for iPhone


On Tuesday, June 28, 2022, 10:21 PM, cartag ***@***.***> wrote:




Closed #2735 as completed.
