### ISSUE TITLE
Order - Idoneth Deepkin: eel battleline 

### ISSUE THREAD

**Issue by exaegrum** [BSData/warhammer-age-of-sigmar#2746]
Akhelian Ishlaen Guard and Akhelian Morsarr Guard are battleline if general is an AKHELIAN KING. This currently works fine with chosen general, but Volturnos, High King of the Deep is a Warmaster who always counts as a general, but currently does not unlock them as battleline. These units should be unlocked as battleline if Volternos is included in the army at all, since he will always be a general.

**Comment by rweyrauch** [comment]
Note found this rule explicitly stated in the Core Rules FAQ (April 2022):

Q: If I have more than one general, and each one allows different types
of units to count as Battleline, do all of those units count as Battleline
units when I pick the rest of my army?
A: Yes.

**Comment by PBobovsky** [comment]
The fix no longer applies, including Volturnos doesn't make Ishlaen or Morsarr guard as battleline.

Similar issue in Gloomspite Gitz: Skragrott is a loonboss moonclan warmaster that is supposed to make squigs into battlelines just by including him in the army. It doesn't.
