### ISSUE TITLE
Chaos - Disciples of Tzeentch - Horrors of Tzeentch

### ISSUE THREAD

**Issue by exaegrum** [BSData/warhammer-age-of-sigmar#2753]
1) Horrors of Tzeentch should no longer have the WIZARD keyword.
2) Currently, only units of one type of horror are supported. Mixed units (i.e. 9 pinks and 1 blue) should be allowed.
3) Name should be Horrors of Tzeentch, not Horrors.

**Comment by cartag** [comment]
1) Fixed in next release
2) I'm not micromanaging it that far. Technically you can bring just 7 Pink horrors instead of all 10, but it's not worth programming it for the off chances since you're paying for all ten anyway. 
3) Fixed in next release.
