### ISSUE TITLE
Corrupted files

### ISSUE THREAD

**Issue by Nyx1824** [BSData/warhammer-age-of-sigmar#2768]
Everytime I try removing and adding or downloading the new update for age of sigmar it simply tells me the file is corrupted no matter what. I've tried un-installing the app, deleting the data and restarting my phone as well as clearing my cache.
1. Go to Age of Sigmar 3.1.5
2. Click on download
3. See error, "file is corrupted"

**Expected behavior**
For the download to occur normally

**Screenshots**
[Screenshot of issue](https://imgur.com/a/RQXDu5Y) 

**Device and data (please complete the following information):**
 - OS: Samsung
 - BattleScribe version  2.03.45
 

**Additional context**

**Comment by rweyrauch** [comment]
Have not been able to reproduce this failure on both the PC and Android versions of Battlescribe using the 3.15 data releases.  

Will keep the issue open to see if others are having similar difficulty.

**Comment by rweyrauch** [comment]
No additional report of corrupted data files.
