### ISSUE TITLE
Support for Path to Glory campaigns in Narrative

### ISSUE THREAD

**Issue by cahe** [BSData/warhammer-age-of-sigmar#2787]
It'd be amazing if we had support for p2g rules in battlescribe. This would include:

- Validation for unit and enhancement limits as described in the order of battle section
![image](https://user-images.githubusercontent.com/3882/182596130-ad07919c-4536-4202-b18c-8af5a8758e4d.png)
- Support or simplified support for stronghold and territory management (it modifies aforementioned limits)
- Support for tiers of battle
![image](https://user-images.githubusercontent.com/3882/182596360-be77f535-f557-4d8a-a823-adbbae1326f8.png)

Other things as well could be nice - Vault, Casuality scores, etc.

**Comment by cartag** [comment]
I will agree with you that yes, it would be amazing if Battlescribe could support P2G. 

The downside being that Battlescribe is not made for campaign settings like that. It's simply not built on the back end to handle implementations of units that can have changes to them or units that aren't going to be brought to some battles. That's the reason Necromunda isn't implemented in BS and why anybody who tries quickly gives up. It's not a lack of wanting, it's a lack of support in the product. And with the app dev going MIA and not updating the app any more, it's not going to change. 

Sorry that's the answer.
