### ISSUE TITLE
Phantasmagoria of Fate units count as coalition, giving plenty of errors.

### ISSUE THREAD

**Issue by zgron** [BSData/warhammer-age-of-sigmar#2789]
Hello,

When using the Phantasmagoria of Fate on the Open & Narrative Tzeentch force I quickly get an error that I've capped my coalition. If I understand the rules correctly units in this battalion shall function exactly as if they belong to the Tzeentch and Beast of Chaos faction, I.e not come in as a coalition.

Additionally, any form of Tzaangor unit in the Phantasmagoria of Fate battalion throws an error for some reason. I want them in the battalion to access Brayherd Ambush.

Grashrak Fellhoof is also missing from the selections.

Make sure the coalition and allies function alongside the Phantasmagoria of Fate as well, one might want to take in some through those channels to create other battalions at the cost of the units losing their Beasts of Chaos rulings.

Cheers,
...

**Comment by zgron** [comment]
There also seems to be something wrong with grand strategy, it asks for one more even though I already have one. If I add another I have 1 too many.

**Comment by rweyrauch** [comment]
Could you post the roster you are having problems with?

**Comment by zgron** [comment]
Hope this works.

Also, spell lores aren’t visible for the war battalion



[b]++ **Narrative and Open Play** (Chaos - Tzeentch) [2,975pts] ++[/b]

[b]+ Core Battalion +[/b]

[b]Core Battalion: Command Entourage:[/b] Extra Enhancement: Artefacts of Power, Magnificent

[b]+ Leader +[/b]

[b]Exalted Greater Daemon of Tzeentch [515pts]:[/b] 6. Tzeentch's Firestorm
. Arcane Tome

[b]Grashrak Fellhoof [150pts]:[/b] Command Entourage - 2-3 Sub-Commanders, Ghost-mist

[b]Tzaangor Shaman [135pts]:[/b] 4. Shield of Fate, Command Entourage - 2-3 Sub-Commanders

[b]+ Other +[/b]

[b]Grashrak's Despoilers[/b]

[b]Slaangor Fiendbloods [130pts]:[/b] 3 Slaangor Fiendbloods

[b]+ Allegiance +[/b]

[b]Allegiance[/b]
. Allegiance: Tzeentch: The Guild of Summoners

[b]+ Game Options +[/b]

[b]Game Type:[/b] 3000 Points - Warhost

[b]Grand Strategy:[/b] Sever the Head

[b]+ Malign Sorcery +[/b]

[b]Endless Spell: Burning Sigil of Tzeentch [50pts][/b]

[b]Endless Spell: Daemonic Simulacrum [60pts][/b]

[b]Endless Spell: Tome of Eyes [40pts][/b]

[b]+ Warscroll Battalion +[/b]

[b]Battalion: Phantasmagoria of Fate [1,895pts]:[/b] Phantasmagoria of Fate
. Beastlord
. Bestigors: 10 Bestigors, Banner bearers, Brayhorns
. Bullgors: 3 Bullgors, Bullgor Great Axes, Warherd Banner Bearer, Warherd Drummer
. Bullgors: 3 Bullgors, Bullgor Great Axes, Warherd Banner Bearer, Warherd Drummer
. Centigors: 5 Centigors, Banner bearers, Brayhorns
. Cygor
. Dragon Ogor Shaggoth: 0. Brimstone Familiar, 0. Prophet of the Ostensible, General
. Gors: 10 Gors, Banner bearers, Brayhorns, Gor Blade and Beastshield
. Gors: 10 Gors, 2 Gor Blades, Banner bearers, Brayhorns
. Great Bray-shaman
. Tuskgor Chariots: Tuskgor Chariot
. Tuskgor Chariots: Tuskgor Chariot
. Tzaangor Skyfires: 3 Tzaangor Skyfires
. Tzaangors: 10 Tzaangors
. Ungors: 10 Ungors, Banner bearers, Brayhorns, Gnarled Shortspears
. Ungors: 10 Ungors, Banner bearers, Brayhorns, Gnarled Shortspears

[b]++ Total: [2,975pts] ++[/b]

Created with [url=https://battlescribe.net]BattleScribe[/url]

**Comment by rweyrauch** [comment]
This helps.  Thanks.

**Comment by rweyrauch** [comment]
The battalion works correctly if you create it from a Beasts of Chaos force.
