### ISSUE TITLE
[Bug Report] Nurgle issues, grand strategy selection issue

### ISSUE THREAD

**Issue by plavski** [BSData/warhammer-age-of-sigmar#2824]
- The Nurgle sub-allegiances still carry old categories, ie. `Blessed Sons`, `Droning Guard` etc. are still categorised as being in `Wrath of the Everchosen`
- Beast of Nurgle in Befouling Host is marked as a Galletian Veteran even though it has more than 4 wounds

Non-nurgle issue:

When creating a list from the GHB 2022, the Universal Grand Strategies are available in BS. But the GHB requires that _only_ grand strategies from the GHB and battletomes are allowed. Hold the Line, Vendetta, and Sever the Head should not be available for a list made according to the GHB 2022.

<img width="182" alt="image" src="https://user-images.githubusercontent.com/15157275/186394485-814c635e-b85a-4f4b-86bf-868643c2ac68.png">

**Comment by rweyrauch** [comment]
A number of 'Categories' are used internally to filter/control availability of the various units in all of the many possible army list configurations.   In the case of the Nurgle the 'Wrath of the Everchosen' is one such category.  There does appear to be a way in Battlescribe to hide this type of internal/control category.

Currently investigating further.

**Comment by rweyrauch** [comment]
There is no way in the Battlescribe app to hide 'internal-only' categories.  The 'Wrath of the Everchosen' category no longer applies and can be removed.
