### ISSUE TITLE
Legion of Azgorh roster error requiring Warscroll Batallions in Pitched Battles

### ISSUE THREAD

**Issue by Dylandoesprogramming** [BSData/warhammer-age-of-sigmar#2829]
I currently have the latest data pulled for Battlescribe, and have a Legion of Azgorh list I'm working on.

Despite the force being marked as Pitched Battle GHB 2022 - I am receiving a roster error: "(1k LoA (Age of Sigmar v140) must have 1 more selections of Blackshard Warhost - 2 Infernal Guard Fireglaives (minimum 1)"

Blackshard Warhost is a Warscroll batallion and cannot be used in pitched battles, so this error as far as I can tell should not be appearing in this situation.

I am on v3.1.12 which appears to be the latest.

**Comment by Tigerwraith** [comment]
What does your list look like when it gives you that Error?

**Comment by Tigerwraith** [comment]
![image](https://user-images.githubusercontent.com/39889736/187489815-ae09cf77-815d-42f7-aff7-e9b1b98a7938.png)

**Comment by Dylandoesprogramming** [comment]
I am using the mobile version of Battlescribe if that changes anything - though I know you guys have no control over the code for battlescribe if that is somehow causing the issue.

Here's the list I used exported as text, let me know if theres a way to export an actual list file or something that might work better for you.

++ *Pitched Battle GHB 2022* 1,000 (Chaos - Legion of Azgorh [LEGENDS]) [1,000pts] ++

+ Core Battalion +

Core Battalion: Battle Regiment

+ Leader +

Drazhoath the Ashen [345pts]: Battle Regiment - 1 Commander, General

+ Battleline +

Infernal Guard Fireglaives [110pts]: 10 Infernal Guard Fireglaives, Battle Regiment - 2-5 Troops

Infernal Guard Ironsworn [200pts]: 20 Infernal Guard Ironsworn, Battle Regiment - 2-5 Troops, Musician, Reinforced, Standard Bearer

+ Other +

Bull Centaur Renders [195pts]: 3 Bull Centaur Renders, Battle Regiment - 2-5 Troops

+ Artillery +

Magma Cannon [150pts]: Battle Regiment - 0-1 Monster or Artillery

+ Allegiance +

Allegiance: Allegiance: Legion of Azgorh

+ Game Options +

Game Type: 1000 Points - Vanguard

Grand Strategy: Defend What's Ours

++ Total: [1,000pts] ++

Created with BattleScribe (https://battlescribe.net)

**Comment by Dylandoesprogramming** [comment]
Found a way to export the roster file and put it on drive. https://drive.google.com/file/d/1TR4bmqXEX-9cWNLZPrECABuZvIXd_gSP/view?usp=sharing no worries if you arent comfortable downloading a random file from me, but thought I'd put it out there in case it helps.
