### ISSUE TITLE
[Anon] Bug report: Death - Data.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#2950]
**File:** Death - Data.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** The Briar Queen is missing a magic box from her roster entry (details below) also when you select General the additional options don't appear.

Magic	Cast/Unbind	Spells Known	Ref
The Briar Queen	1/1	Arcane Bolt, Mystic Shield and Howling Vortex

**Comment by rweyrauch** [comment]
The Briar Queen is a unique character and is not permitted to take extra enhancements (command traits, artefacts, etc.).
