### ISSUE TITLE
Support for Tiers of Battle in Narrative

### ISSUE THREAD

**Issue by cahe** [BSData/warhammer-age-of-sigmar#2966]
When playing a path to glory campaign you are given opportunity to play at different tiers of battle. Even the lower tier gives you the ability to add to your army a second artefact / command ability, etc.

Unfortunately there's no way of accounting for that at the moment. And it results in this:

![image](https://user-images.githubusercontent.com/3882/207757646-5abbd9a8-e288-4ed9-bfdb-2f44e6361847.png)

My proposal would be to implement this by simply having a new "thing" in Game Options that enables you to choose tier of battle, or just the number of extra enchantments per type, so that we can still use the awesome validation rules implemented in AoS data otherwise. I assume this is possible, because Core Batalion: Warlord exists and does similar thing.

These are the types of enchantments you can get in addition to the standard ones:
![image](https://user-images.githubusercontent.com/3882/207758789-940c9388-8e34-41b2-9a7b-c5694a008715.png)

What do you think? Thanks in advance! 💯

**Comment by rweyrauch** [comment]
This is possible to implement.  I'll take a closer look and figure out how much effort.
