### ISSUE TITLE
Anvilgard War Hydra and Karhybdi cannot be added to Linebreaker battalions, even though they are in fact monsters

### ISSUE THREAD

**Issue by Veziik** [BSData/warhammer-age-of-sigmar#3032]
**Describe the bug**

**To Reproduce**
1. Create A Cities of Sigmar Army
2. Set the subfaction [City] to Anvilgard
3. Add 2 or 3 Hydra/Karybdi
4. Add a Linebreaker core battalion
5. see that the Hydra/Karybdi cannot be added to the linebreaker detachment as a monster, even though it is a monster

**Expected behavior**
War Hydra and Kharybdi in an anvilgard army are still mosnters despite their status as battleline, so they should still be able to be part of a linebreaker battalion

**Screenshots**

**Device and data (please complete the following information):**
 - OS: Android
 - BattleScribe version v2.03.25.338
 - Release version v3.2.3

**Additional context**

**Comment by rweyrauch** [comment]
When in Anvilgard, the Hydra/Kharibdyss gain the 'battleline' role but lose the the 'behemoth' role (see Core Rules 25.5.1).   The definition of a 'Monster' in a core battalion is a 'behemoth' that is not a 'leader' (see Core Rules 26.2).   As such, in spite of having the MONSTER keyword, the 'battleline' Hydra and Kharibdyss are not monsters with respect to core battalions.
