### ISSUE TITLE
Chaos - Skaven: missing points costs.

### ISSUE THREAD

**Issue by maddoodles** [BSData/warhammer-age-of-sigmar#3118]
The following units are missing their points costs:
- Poisoned Wind Mortar (LEGENDS) (70pts)
- Skittershank's Clawpack (220pts)
- Spiteclaw's Swarm (150pts)

**Comment by rweyrauch** [comment]
Legend units do not have points, nor are they technically permitted in matched play.   

The Skittershank's Clawpack and Spiteclaws Swarm units must be included with their respective leader.  The leader unit has points assigned to it.
