### ISSUE TITLE
No Artillery section in Seraphon

### ISSUE THREAD

**Issue by Boz83** [BSData/warhammer-age-of-sigmar#3147]
Hi all

First off thank you for all you do, you are all a credit to the hobby. When trying to write a list for the new Seraphon battletome there is no artillery category so we can't select the spawn of Chotec.

Kind Regards 
Boz

**Comment by exaegrum** [comment]
This is resolved in #3146.

**Comment by Boz83** [comment]
I don't agree this is fixed. I've just been on and the spawn is nowhere to be found in either the battleline or other section. How do I add this unit to my roster?
![Screenshot_20230513-192601](https://github.com/BSData/warhammer-age-of-sigmar/assets/101415990/1aac8248-4823-472c-b708-aa6f262cbf6c)

**Comment by exaegrum** [comment]
Ensure your data is up to date - delete and redownload it if still having issues.
