### ISSUE TITLE
Stormcast Eternals v73 - no SCE holy commands to pick

### ISSUE THREAD

**Issue by cahe** [BSData/warhammer-age-of-sigmar#3193]
You cannot pick any unique enhancments (holy commands) on SCE roster anymore.
![image](https://github.com/BSData/warhammer-age-of-sigmar/assets/3882/13fe123c-c600-4396-8378-11999202d4b4)

Tested in GHB and Narrative modes

**Comment by exaegrum** [comment]
They've been moved to Game Options section (same place you select a triumph). As mechanically they aren't tied to specific units, it made no sense to have them as a unit selection.
