### ISSUE TITLE
SBGL unable to select bloodlines

### ISSUE THREAD

**Issue by Ldeat6328** [BSData/warhammer-age-of-sigmar#3197]
Unable to select bloodline from alligence
Warhammer: Age Of Sigmar v3.3.6
Battlescribe v 2.03.15
OS: IOS
![IMG_1247](https://github.com/BSData/warhammer-age-of-sigmar/assets/123335421/5764805d-512a-4920-ac9e-9c8575cf6b6d)
![IMG_1248](https://github.com/BSData/warhammer-age-of-sigmar/assets/123335421/bd59a15a-77fd-44f3-9dcf-8709c40853dd)

**Comment by Tigerwraith** [comment]
Tap on the name and not the radio button.

**Comment by Tigerwraith** [comment]
![Screenshot_20230726-160802](https://github.com/BSData/warhammer-age-of-sigmar/assets/39889736/24dbfc79-f1d0-4609-8f64-d083cdd357a1)

**Comment by Tigerwraith** [comment]
![Screenshot_20230726-160811](https://github.com/BSData/warhammer-age-of-sigmar/assets/39889736/8b90263d-4dc2-4caa-8fad-1054e123742b)
