### ISSUE TITLE
Data Quality - Stormcast Eternals Allegiance selection has inconsistent type

### ISSUE THREAD

**Issue by logisticpeach** [BSData/warhammer-age-of-sigmar#3208]
The data file for the Stormcast Eternals faction has the following entry for the **Allegiance** selection:

` <selectionEntry id="c6a3-2acf-1e46-3896" name="Allegiance" hidden="false" collective="false" import="true" type="unit">`

Note the `type="unit"` here - most other catalogues I've inspected have the more sensible `type="upgrade"` here. For example, [Lumineth Realmlords](https://github.com/BSData/warhammer-age-of-sigmar/blob/c2fdca2ebb9a914f38575e4013b2185b853b1e06/Order%20-%20Lumineth.cat#L213C6-L213C6) and [Idoneth Deepkin](https://github.com/BSData/warhammer-age-of-sigmar/blob/c2fdca2ebb9a914f38575e4013b2185b853b1e06/Order%20-%20Idoneth%20Deepkin%20-%20Data.cat#L73)

I would expect all datasets to have a consistent schema and treat concepts in a constant way.

**Comment by exaegrum** [comment]
Your expectation is unfortunately nowhere near met - there is currently a fairly large lack of consistency in general in the implementation. I would like to completely redo the system from scratch, but would like to wait until 4e in case we get indexed like 40k. I'll change this one bc it's a 5 sec fix, but in general schema issues that aren't causing problems aren't going to be touched until then.
