### ISSUE TITLE
Cities of Sigmar 3rdEd?

### ISSUE THREAD

**Issue by MariusSuther** [BSData/warhammer-age-of-sigmar#3219]
I'm not sure if this is the right place to ask, but is there any word as to when the content for the new Cities of Sigmar battletome will be added? As it will likely be a while before they added to the AoS app, at the moment i'm forced to lay out a strange spread of warscroll cards and such whenever I have a game!

**Comment by exaegrum** [comment]
They're a WIP right now - I've finished implementing everything except for the humans. I'd like to have them done sometime this week, but no guarantees?
