### ISSUE TITLE
Daughters of Khaine army bug on Battlescribe with Melusai Ironscale as general

### ISSUE THREAD

**Issue by HikariTempest** [BSData/warhammer-age-of-sigmar#3308]
If I create a Daughters of Khaine army and add Melusai Ironscale as the general everything looks okay and I can see the Melusai units being possible battleline units. But as soon as I add one of either of them there are suddenly two of each type.

Before I add any other Melusai units after asigning Melusai Ironscale as my general:
Battleline:
Blood Sisters
Blood Stalkers
Sisters of Slaughter
Witch Aelves

After I add for either the Blood Sisters or Blood Stalkers:

Blood Sisters
Blood Sisters
Blood Stalkers
Blood Stalkers
Sisters of Slaughter
Witch Aelves

**Screenshots**
![image](https://github.com/BSData/warhammer-age-of-sigmar/assets/91137888/4e947e38-5f0d-40e5-be72-318f7e0bff4b)

**Device and data (please complete the following information):**
 - OS: Windows
 - App being used to create lists Battlescribe
 - App version 2.03.21
 - Data release version 3.3.28

**Comment by exaegrum** [comment]
This bug is present with all conditional battlefield roles - it's an issue with Battlescribe itself, not the data. Unfortunately, this means we cannot fix it. Note that alternative builders using BSData, like New Recruit, do not have this behavior.
