### ISSUE TITLE
Data seems to wig out involving Knights of the Empty Throne and Varanguard.

### ISSUE THREAD

**Issue by mouthwideopen** [BSData/warhammer-age-of-sigmar#3313]
So, how Knights of the Empty Throne works is that Varanguard are made to be battleline, *but*, you can make them a general if you want, and they receive the Leader keyword should you make them a general. They don't become a hero though, so they don't get command traits. You don't HAVE to run Varanguard as your general, if you don't want to. But you can. 

Anyways, when I set anyone in my list as a general, Varanguard or not, all of the Varanguard are given the Leader keyword erroneously, and then marked as simply "Not Legal" in my listbuilder (including any that are set as a general, for some reason.)

The Varanguard should not be moved to the Leader category unless they are set as my general. Setting someone else as my general should have them stay in Battleline, and even if I set a Varanguard as my general, it shouldn't move other Varanguard units to the Leader category as well.

**Comment by Cgboal** [comment]
This is the same in other subfactions afaik. This has been an issue for like 6 months.
