### ISSUE TITLE
Allied Leaders not included in the Text export

### ISSUE THREAD

**Issue by jonasrademar** [BSData/warhammer-age-of-sigmar#3334]
**Describe the bug**
Allied Leaders not included in the Text export

**To Reproduce**
1. Go to Lists and create a "Chaos - Tzeentch" army
2. Click on Child Forces, select "Chaos - Slaanesh" and then "Allies +"
3. Scroll down and add units from the Slaanesh contingency 
4. Click List Options in the top right and select "Export List" and "Text"

**Expected behavior**
All units should be in the list

**Screenshots**
![image](https://github.com/BSData/warhammer-age-of-sigmar/assets/2114125/f3f28d67-c6fa-408f-9c25-d383909fbcab)
![image](https://github.com/BSData/warhammer-age-of-sigmar/assets/2114125/f7e01cf6-4f53-4ca0-8792-e64f30d19fa7)

**Device and data (please complete the following information):**
 - Tested on Chrome (PC) & Android app, and with multiple army types (not just Tzeentch & Slaanesh as in the above example)

**Comment by exaegrum** [comment]
This is a bug in New Recruit, not the data. I've passed it on to the devs.
