### ISSUE TITLE
Destruction - Firebelly - No Weapon Profile indicator for Firebreath attack

### ISSUE THREAD

**Issue by OftKilted** [BSData/warhammer-age-of-sigmar#334]
Fire Breath has a distance profile but no indicator that it is a 'Special' attack (either with * or 'Special' or 'Ability')

Should it be left that way as the ranged attack is a Unit Ability, not an actual 'weapon attack'?

**Comment by tekton** [comment]
Is *is* a missile weapon, so for the sake of rules that interact with weapons it isn't a special attack- it's effect is described as an ability but it is a weapon. Putting stars in the fields though, as that lines up more with that we've done elsewhere.
