### ISSUE TITLE
Shaman of the Chilled Lands command trait not working correctly

### ISSUE THREAD

**Issue by BlackhoundVXX** [BSData/warhammer-age-of-sigmar#3354]
**Describe the bug**
If you add the Shaman of the Chilled Lands command trait to your general (1) and then add all the spells from the Lore of Primal Frost to your general (2) you get an error that you have too menay selection from the spell lore (3). 

![image](https://github.com/BSData/warhammer-age-of-sigmar/assets/116191259/fb120ea8-95ec-496f-88ac-edfc2ff7d686)

**To Reproduce**
1. Add the Shaman of the Chilled Lands command trait to your general
2.  Add all the spells from the Lore of Primal Frost to your general 

**Expected behavior**
You should not get an error message since it is totally legal. 
![image](https://github.com/BSData/warhammer-age-of-sigmar/assets/116191259/33abf95d-11d7-42bd-880c-59291d56e489)

**Screenshots**
see in description

**Device and data (please complete the following information):**
 - OS: windows
 - App being used to create lists Battlescribe
 - App version 2.03.21
 - Data release version 3.3.46 Feb 22 2024

**Additional context**
N/A

**Comment by exaegrum** [comment]
This isn't a bug - shaman of the chilled lands will automatically give you access to them, there isn't a need to select them separately. You are legally allowed to select a spell you already know with one of your spell enhancements, it's just pointless.

**Comment by BlackhoundVXX** [comment]
Hello, 
I know having the command trait gives you access to them, but they are not listed in the html version with your hero if you don't do so. I personnaly like to print the HTML version for my list and use it as a reference during games. Having all the spells listed gives me access to all the wording really easilly. 

I just can ignore the warning, print the list and I'm fine. Having a warning listing I have too many spells is just a minor annoyance. ;)  Maybe I just stress out because I always think I broke something while making minor changes ;) 

Cheers.
