### ISSUE TITLE
Error in Sevireth (Lumineth Realm-Lord ) Scour ability

### ISSUE THREAD

**Issue by BlackhoundVXX** [BSData/warhammer-age-of-sigmar#3357]
**Describe the bug**
Scour ability should activate at the end of the charge phase not at the start of the charge phase. 

**To Reproduce**
N/A

**Expected behavior**
see screenshots

**Screenshots**
in battlescribe 

![image](https://github.com/BSData/warhammer-age-of-sigmar/assets/116191259/2323d1a5-1d80-4d36-8d6c-17edac8955ef)

How it should be worded : 

![image](https://github.com/BSData/warhammer-age-of-sigmar/assets/116191259/095f9c43-c36d-4b7c-939c-04693f622e95)

**Device and data (please complete the following information):**
 - OS: Windows
 - App being used to create lists :  Battlescribe
 - App version 2.03.21
 - Data release version 3.3.47 (Feb 27 2024)

**Additional context**
n/a

**Comment by exaegrum** [comment]
resolved in #3359
