### ISSUE TITLE
MoN Battle Formation

### ISSUE THREAD

**Issue by Tigerwraith** [BSData/warhammer-age-of-sigmar#3387]
**Describe the bug**
Wording of Afflection Cyst is not current
**To Reproduce**
Mouse over Affliction Cyst for MoN and it reads
Pick a friendly Nighthaunt unit that is not in combat to use this ability
Remove that unit from the battlefield and set it up again on the battlefield more than 9" from all enemy units

**Expected behavior**
It should read
Declare: Pick up to 2 friendly MoN units that have Fly . Effect: Remove the targets from the battle eld and set them up again on the battle eld more than 9" from all enemy units.

**Screenshots**

**Device and data (please complete the following information):**
 - App being used to create lists [e.g. New Recruit, Bluescribe, Battlescribe]
 - App version
 - Data release version [e.g. v1.2.3]

**Additional context**

**Comment by exaegrum** [comment]
This is the wrong repo, but i've resolved it. Future issues should be raised at https://github.com/BSData/age-of-sigmar-4th/issues.
