### ISSUE TITLE
Destruction - Beastclaw Raiders, Torrbad battalion incorrect points.

### ISSUE THREAD

**Issue by rweyrauch** [BSData/warhammer-age-of-sigmar#339]
Currently a hefty 1620.  Much better bargain at 160.

**Comment by rweyrauch** [comment]
The Torrbad Battalion is including all of the units needed to make up the battalion.   Warscroll battalion validation is not a v2.0 feature.   Recommend that all battalion validation be removed for v2.0 release.  Battalion validation will be implemented in v2.x.

**Comment by tekton** [comment]
I agree on the moving this one to post launch :)
