### ISSUE TITLE
[Anon] Chaos - Skaven: Saying I need to select an Allegiance but I’ve already selected one 

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/warhammer-age-of-sigmar#3392]
**Problem:**
Saying I need to select an Allegiance but I’ve already selected one 

**Expected:**
Fix bug

**List:** https://www.newrecruit.eu/app/list/PZhBa
**Unit:** Allegiance, id: `b2ca-078c-afe6-34d9`

**Comment by Tigerwraith** [comment]
This is for open play for AoS 3ed. This release is no longer supported. This will be closed.
