### ISSUE TITLE
Khorne Bloodbound Issues

### ISSUE THREAD

**Issue by cartag** [BSData/warhammer-age-of-sigmar#40]
Listed in Allegiance as "Khrone Mortals" instead of "Khorne Mortals." Should include other units with MORTAL and KHORNE keywords, including those from Slaves to Darkness.

Mighty Skullcrushers should not be listed as Battleline units unless Lord of Khorne on Juggernaut is general of army.

**Comment by flakpanda** [comment]
Thanks for pointing out the spelling error. And I am in the middle of
reworking the units for the allegiances. I'll double check the
skullcrushers modifiers.

**Comment by flakpanda** [comment]
Fixed and will push out with next release.

**Comment by flakpanda** [comment]
Closed #40
