### ISSUE TITLE
Age of Sigmar: Questions and missing FW monsters

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#412]
**File:** Age of Sigmar.gstz

**BattleScribe version:** 2.01.19

**Platform:** Android

**Dropbox:** No

**Description:** Unless I'm missing something, there's no ability to start a roster without a faction allegiance - i.e. One with just Death, Destruction, Chaos, or Order allegiance - with all the appropriate units available in the right categories (Ironjawz Ardboyz becoming an "Other" choice rather than Battleline for example).

All the Forge World monsters are missing bar the Carmine Dragon.

**Comment by OftKilted** [comment]
One would select “Allegiance” and then select your “Grand Alliance” Faction.

The Chaos forgeworld monsters are in the monsters of chaos catalog

Order is in order - monstrous Arcanum
