### ISSUE TITLE
Destruction  - FW Monsters missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#422]
**File:** Age of Sigmar.gstz

**BattleScribe version:** 2.01.19

**Platform:** Android

**Dropbox:** No

**Description:** Hi there

I can't seem to find the Forge World monsters for the Destruction faction (Squig Gobba, Rogue Idol etc.)

**Comment by tekton** [comment]
Cleaning these up tonight and tomorrow morning

**Comment by rweyrauch** [comment]
Added 'Destruction - Monsters.cat'.
