### ISSUE TITLE
Units Missing From Grand Alliance: Death

### ISSUE THREAD

**Issue by arclance** [BSData/warhammer-age-of-sigmar#43]
All Units and Warscroll Battalions from the "Vampire Counts" (pg.151 Generals Handbook) and "Tomb Kings" (pg.150 Generals Handbook) are missing from the Death Grand Alliance file (Death.cat)
All these units have the "Death" Keyword and so are part of the Death Grand Alliance as per the rules from the "Allegiance" rule box on pg.156 in the Generals Handbook.

The relevant Warscrolls can be found in the "Warhammer Age of Sigmar Rules" section of the Games Workshop website.  https://www.games-workshop.com/en-US/Warhammer-Age-of-Sigmar-Rules
Tomb Kings "Skeleton Warriors" have an equipment option "Tomb Shield" the ones from the "Death Grand Alliance" section don't have but have the same points cost.

**Comment by magusnebula** [comment]
Yes, these will be added, compendium armies as far as I know were going to be added last. This is in progress in the read.me. As far as the skeleton warriors, it could just stay under the same unit choice since they have the same points.

**Comment by flakpanda** [comment]
Closed #43

**Comment by arclance** [comment]
@magusnebula 
I have seen nothing that indicates the order things will be done in.
The read.me is bulleted list of five lines none of them sentences describing the overall plans for the order things will be done.
Death is currently listed as "Death: Points, Completed" which I would assume covers [u]all[/u] Death units since every warscroll (other than terrain) is part of one of the grand alliances.
Since Death is listed as "Completed" yet units are missing I can only assume they were missed accidentally or left out deliberately.
Since this was closed by flakpanda without any commits being made to resolve the problem of missing warscrolls or commenting on what is going on with them I find the second reason to be more likely.

**Comment by flakpanda** [comment]
I closed the issue because it was explained correctly to you by @magusnebula. In the GHB, the **5 sections** for pitched battle points are chaos, destruction, death, order, and **compendium**. The compendium section list all legacy units in the game. The same ones you are asking about in this ticket. They are currently listed in the Readme as "in progress", and will be included when completed.
