### ISSUE TITLE
Helping with WoodElve Repositiry

### ISSUE THREAD

**Issue by Cupropituvanso** [BSData/warhammer-age-of-sigmar#45]
Hello

I have downloaded your repository and thanks for your work.
For my use I want to fill it with profiles for units, weapons and anything necessary for the WoodElves Units. Normally I would do it in german and use only for myself, but I could do it on english and give it to you.

If this is interesting for you, please tell me if there is any update in work for the order catalog file.

Best Regards
Cupro

**Comment by amis92** [comment]
Hello, @Cupropituvanso 
. Please accept the invitation in the email or on the [BSData organization webpage](https://github.com/BSData). Welcome aboard!

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

Cheers!

PS It looks like the most active here lately is @flakpanda, so you might want to coordinate things with him.
