### ISSUE TITLE
Units from Artillery battlefield role are not present when including them as Allies.

### ISSUE THREAD

**Issue by rweyrauch** [BSData/warhammer-age-of-sigmar#464]
BS v2.01.20.281 for Android.

The Ironweld Arsenal artillery units are not present when including the faction as an ally force.  

Example:
Create 2000 point roster for SCE.  Add IA as an ally.  The IA artillery units are not available for selection.

Only confirmed at the moment with SCE + IA.

**Comment by rweyrauch** [comment]
This bug is present in other situations when the parent faction does not contain any Artillery units and the child/ally faction does.

Ex: BCR allied with Gitmob Grots.

**Comment by rweyrauch** [comment]
Note this bug only happens in 'Force Selection'  'Merged' and 'Nested' modes.

**Comment by OftKilted** [comment]
@Jonskichov This appears to be a battlescribe issue related to force selection visibility.

**Comment by Jonskichov** [comment]
This was a bug. A fix has been uploaded for Android and should start rolling out now.

iOS fix has been uploaded and will become available in the next day or so once it's been reviewed.

**Comment by rweyrauch** [comment]
Fixed in BS v2.01.20.282 for Android.
