### ISSUE TITLE
[Anon] Bug report: Chaos - Daemons of Chaos.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#486]
**File:** Chaos - Daemons of Chaos.catz

**BattleScribe version:** 2.01.20

**Platform:** Android

**Dropbox:** No

**Description:** Hellcannon is missing from Daemons of Chaos catalogue.

**Comment by OftKilted** [comment]
The Hellcannon is included in the 'Warriors of Chaos' Warscroll Compendium.

It is also in the AoS 'Daemons of Chaos' list of units in the Warhammer AoS app.

**Comment by OftKilted** [comment]
Adding Hellcannon to the Daemons of Chaos pending 'Warriors of Chaos' catalog creation.

**Comment by OftKilted** [comment]
Hellcannon moved to Warriors of Chaos catalog to mirror Warscroll Compendium Location
