### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by rastus** [BSData/warhammer-age-of-sigmar#49]
Hi. Looking to join and help with maintaining the AoS catalogues (have already forked and had pull requests accepted but figure it'll be easier if I can get involved directly),

Thanks

**Comment by flakpanda** [comment]
Paging @amis92

**Comment by amis92** [comment]
Hello, @rastus. Please accept the invitation in the email or on the [BSData organization webpage](https://github.com/BSData). Welcome aboard!

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

Cheers!
