### ISSUE TITLE
Request: allow narrative/open play lists

### ISSUE THREAD

**Issue by QuinnStevens** [BSData/warhammer-age-of-sigmar#494]
Currently it seems the only options for lists are pitched battles of either 1k, 2k or 2.5k pts. It would be nice to be able to use battles drive to keep track of my non-matched-play-legal narrative & open play armies without having the app complain that I don't have enough battle line, for instance.

**Comment by OftKilted** [comment]
Is this a request for the '**Pitched Battle Variations**' rules suggested in the new Core Rules?

- Play any of the individual Game Types at +/- 250 points
- Play just using Points (leader/battleline/etc still exist. but have no real bearing as there are no warscroll/battleroles to be validated)

Or is this full '**Open Play/Narrative**' where there are no Battleroles (Leader/Battleline/Behemoth/etc.) , and allows one to select multiples of UNIQUE units.

Currently, the Battlescribe catalog files do internal validation for units, including validation for UNIQUE units. And all Battlerole handling is managed as part of the unit availability selections.

**Comment by QuinnStevens** [comment]
Either the full open play/narrative or the playing using points only would work for me.

**Comment by OftKilted** [comment]
@QuinnStevens Full Open Play/Narrative would require a substantial rework of the catalogs. 

We'll take a look to see if there is an 'easier fix' for a solution.

I'll add this to our implementation request queue for a future release. 😄

**Comment by OftKilted** [comment]
New "**Pitched Battle** Profile created to allow modification of points levels without leaving list. Also allows 'removal of constraints' for points and unit types.

**Comment by OftKilted** [comment]
Resolved with most recent release
