### ISSUE TITLE
Chaos - June 2018 FAQ Update

### ISSUE THREAD

**Issue by OftKilted** [BSData/warhammer-age-of-sigmar#516]
June 2018 FAQ Is out. Request for update.

- [x] Brayherd
- [x] Everchosen
- [x] Khorne
- [x] Monsters of Chaos
- [x] Skaven
- [x] Tzeentch
- [x] Warherds
- [x] Nurgle

**Comment by FreylisUK** [comment]
Nurgle updates in #520
