### ISSUE TITLE
BattleScribe 2.0

### ISSUE THREAD

**Issue by Jonskichov** [BSData/warhammer-age-of-sigmar#53]
BattleScribe 2.0 is just about here.

Have you tested it?

https://github.com/BattleScribe/Desktop-Alphas/issues/1

**Comment by Master-lux** [comment]
It always appears an error concerning some conditions if an roster is loaded. This error comes from the force Entries (Pitched Battle). I´m unable to modify them and if i try to delete one the Data editor blocks /crashes.

**Comment by Master-lux** [comment]
Fixed with the new upload
