### ISSUE TITLE
Chaos - Skaven - Stormvermin points

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#560]
**File:** Chaos - Skaven.catz

**BattleScribe version:** 2.01.18

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Stormvermin should have an option to take 40 for 500 points. The Generals Handbook is wrong on this. The Warscroll Builder has it correctly though.

**Comment by tekton** [comment]
While that may be true I don't seem to see any official FAQ, errata, etc released for this one just yet.

**Comment by OftKilted** [comment]
Not clarified in the GHB 2018. There is a 'change designation' indicated next to the Stormvermin, but unless it is a unit size decrease (or that it costs 500 points at a unit size of 30) the warscroll builder isn't a definitive source.

**Comment by OftKilted** [comment]
Added 'Horde Pricing' option for 80 points that becomes available when 30 Stormvermin have been selected to meet the '500 point' requirement.

**Comment by OftKilted** [comment]
No available option for unit of 40 per current GHB. Resolving issue with 'horde pricing' option until further errata from GW.
