### ISSUE TITLE
Chaos - Legion of Azgorh - Hashut's Wrath Artillery Train's Composition

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#562]
**File:** Chaos - Legion of Azgorh.catz

**BattleScribe version:** 2.01.20

**Platform:** Android

**Dropbox:** No

**Description:** Hashut's Wrath Artillery Train's mandatory composition has changed in the latest rules.

It should be:

1 Daemonsmith
1 Iron Daemon

Any 3 from the following:

Iron Daemon
Dreadquake Mortar
Deathshrieker Rocket Launcher
Magma Cannon

**Comment by FreylisUK** [comment]
Fixed in #568
