### ISSUE TITLE
Chaos - Khorne - SkullSeeker Host Composition

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#563]
**File:** Chaos - Khorne.catz

**BattleScribe version:** 2.01.14

**Platform:** Windows

**Dropbox:** No

**Description:** The Battalion requirements for SkullSeeker Host is wrong.  should list SKULLMASTER, Herald of Khorne as required instead of Bloodmaster, Herald of Khorne.

**Comment by OftKilted** [comment]
Skullseeker Host requirements (though unusual) are actually a Bloodmaster, not a Skullmaster, this has not been FAQ'd.

“ORGANISATION
A Skullseeker Host consists of the following units:
• 1 Bloodthirster of Insensate Rage
• 1 Bloodmaster, Herald of Khorne
• 2-5 units of Bloodcrushers
• 1-3 units of Skull Cannons”
