### ISSUE TITLE
Order - Stormcast Eternals - Liberators Grand weapons Collectivity issue

### ISSUE THREAD

**Issue by WindstormSCR** [BSData/warhammer-age-of-sigmar#565]
grand weapons are set as collective, requiring all liberators units to have the same selections.

**Comment by OftKilted** [comment]
Error seen when selecting multiple units of Liberators in the same Force.

Add first unit of Liberators. Increase unit size to 10. Select weapon choice, and add 2 great weapons (one of each type)
Add second set of liberators. Select core weapon choice. Do NOT add a great weapon to the unit. Error will flag "All Liberatorss must have the same number of selections from grand weapons."

**Comment by FreylisUK** [comment]
This is fixed in my branch. I'll close it off when I've finished the full Battletome update.
