### ISSUE TITLE
Order: Stormcast Eternals Battalion Updates

### ISSUE THREAD

**Issue by rweyrauch** [BSData/warhammer-age-of-sigmar#571]
Update the SE Warscroll Battalions for 2018 Battletome:

New Battalions:
- [x] Cleansing Phalanx
- [x] Grand Convocation
- [x] Hailstorm Battery
- [x] Sacrosanct Chamber
- [x] Soulstrike Brotherhood

Depricated Battalions:
- [x] Aetherstrike Force
- [x] Anvils of the Heldenhammer Warrior Chamber
- [x] Astral Templars Examplar Chamber
- [x] Blacktalon's Shadowhammers
- [x] Celestial Hunting Pack
- [x] Celestial Vindicators Warrior
- [x] Celestial Warbringers Harbinger
- [x] Hallowed Knights Warrior Chamber
- [x] Hammers of Sigmar Warrior Chamber
- [x] Knights Excelsior Exemplar Chamber
- [x] Storm Heralds
- [x] Storm Vortex Garrison
- [x] Tempest Lords Harbinger Chamber

**Comment by FreylisUK** [comment]
On it...

**Comment by OftKilted** [comment]
@FreylisUK Lets NOT delete the 'removed battalions' and instead transition them to No Points, and (OPEN PLAY) labeling.

**Comment by rweyrauch** [comment]
Making the old battalion open play only is a better plan.

**Comment by rweyrauch** [comment]
Implemented with #583.
