### ISSUE TITLE
Order - Kharadron Overlords - Great Endrinworks categorised as Artefacts of Power

### ISSUE THREAD

**Issue by BerkshireKnight** [BSData/warhammer-age-of-sigmar#572]
A Kharadron Overlords army is entitled to 1 Great Endrinwork (+1 per battalion) *and* one Artefact of Power (+1 per battalion), but the force treats both as Artefacts and raises an error if I have one of each selected.

**Comment by rweyrauch** [comment]
Fixed by PR #575.
