### ISSUE TITLE
Stormcast Eternals: Allegiance Abilities

### ISSUE THREAD

**Issue by ThePatient** [BSData/warhammer-age-of-sigmar#578]
The battle traits for the **Stormcast Eternals** needs the following changes:

- [x] **Scions of the Storm** has new wording
- [x] **Shock and Awe** needs to be added
- [x] **Stormhosts** need to be added

**Stormhosts**:
- [x] Hammers of Sigmar
- [x] Hallowed Knights
- [x] Celestial Vindicators
- [x] Anvils of the Heldenhammer
- [x] Knights Exclsior
- [x] Celestial Warbringers
- [x] Tempest Lords
- [x] Astral Templars

**Comment by ThePatient** [comment]
I forked the repo and have an update for the Scions of the Storm wording, but I wasn't sure how to implement the other changes.

I would love to help out, but I'm not quite sure how the data format works yet.

**Comment by FreylisUK** [comment]
Hi there! I'm in the process of updating the Stormcast catalogue and have changes in my fork at the moment. I should have the whole thing done in the next couple of days.

**Comment by ThePatient** [comment]
Ah. Lovely! Carry on then.
