### ISSUE TITLE
Request: Battalions should enforce composition rules 

### ISSUE THREAD

**Issue by BerkshireKnight** [BSData/warhammer-age-of-sigmar#58]
If be really useful if, once a warscroll battalion is selected, it enforces minimum numbers of the required units.

**Comment by Igtenio** [comment]
This is actually on my to-do list as I go through adding units. Once I get to the Battalions I'll see about implementing this.

**Comment by Igtenio** [comment]
I added a pull request for my additions to the Chaos catalogue. Once those come in, take a look at the Goreblade Warband. It's not exactly what you requested, but I'm not sure BattleScribe can do exactly what you asked.

In short, when the Battalion is selected, it won't make the Unit requirements ability disappear nor the soft warning that the battalion is selected until that many units are in the roster. Once they are, both vanish, along with the Invalid Battalion warning.

**Comment by rastus** [comment]
Take a look at the Ironjawz Battalions - they include the minimum unit requirements within the Battalion selection itself and handle optional unit selections/upper limits). Still a couple of quirks I'd like to iron out but I think it works well.

**Comment by StealthKnightSteg** [comment]
@rastus those little quirks might have something to do with the Leader / battleline selections that aren't matched by the battalions?
