### ISSUE TITLE
Stormcast Eternals: Lord Arcanum cannot take Command Traits

### ISSUE THREAD

**Issue by cartag** [BSData/warhammer-age-of-sigmar#588]
It looks like it's not linking to the SSE of General and has it's own listing, causing it to not show when General is selected.

**Comment by cartag** [comment]
This is for all Lord Arcanum models too btw.

**Comment by FreylisUK** [comment]
This was fixed with the catalogue update but didn't make the 2.0.4 release unfortunately; new PR created in #589.
