### ISSUE TITLE
[Anon] Bug report: Destruction - Ironjawz.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#602]
**File:** Destruction - Ironjawz.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** Yes

**Description:** THE UNIT ORRUK GORE GRUNTAS IS MISSING NOT IN THE BATTALSCRIBE.

**Comment by OftKilted** [comment]
Orruck Gore-gruntas is available in the non-dropbox catalog as a Battleline unit.
