### ISSUE TITLE
Destruction - Ironjawz - No Allegiance Traits or Grand Alliance Trait listed- Wierdnob Shaman Missing stats

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#607]
**File:** Destruction - Ironjawz.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Can you please include the allegiance traits for 'iron jaws' and 'destruction' grand alliance.
Weirdknob shaman not showing warscroll data like movement,wounds,bravery and save

**Comment by tekton** [comment]
I totally didn't add them and forget to link them...no...that didn't happen...
