### ISSUE TITLE
Destruction - Ardboys point cost

### ISSUE THREAD

**Issue by ShaneHobbes** [BSData/warhammer-age-of-sigmar#609]
Ardboys are 20 points cheaper now. 160 per 10, still 450 for a max unit of 30.

Ardfist Battalion should then be 60 points cheaper at its minimum. 730 instead of 790 for the point reduction of Ardboys

**Comment by tekton** [comment]
something is weird with this one, i think a commit got clobbered, but it should be fixed with the next release
