### ISSUE TITLE
Destruction - July 2018 FAQ Update

### ISSUE THREAD

**Issue by OftKilted** [BSData/warhammer-age-of-sigmar#617]
Update the Destruction Catalogs to the July 2018 FAQ

- [ ] Destruction - Aleguzzler Gargant
- [ ] Destruction - Beastclaw Raiders
- [ ] Destruction - Bonesplitterz
- [ ] Destruction - Firebelly
- [ ] Destruction - Gitmob Grots
- [ ] Destruction - Greenskinz
- [ ] Destruction - Gutbusters
- [ ] Destruction - Ironjawz
- [ ] Destruction - Maneaters
- [ ] Destruction - Monsters
- [ ] Destruction - Moonclan Grots
- [ ] Destruction - Ogre Kingdoms
- [ ] Destruction - Orcs and Goblins
- [ ] Destruction - Spiderfang Grots
- [ ] Destruction - Troggoth

**Comment by tekton** [comment]
Closed with PR#634
