### ISSUE TITLE
All Catalogs - Allegiance Trait Update Management (July 2018 FAQ Update)

### ISSUE THREAD

**Issue by OftKilted** [BSData/warhammer-age-of-sigmar#620]
Hide Grand Alliance Battle Trait/Allegiance Traits if a specific faction alliance is taken (except for allegiances that do not have any allegiance traits)

**Comment by rweyrauch** [comment]
The following Order catalogs require changes for Allegiance Traits:

- [ ] Order - Daughters of Khaine
- [ ] Order - Idoneth Deepkin
- [ ] Order - Kharadron Overlords
- [ ] Order - Seraphon
- [ ] Order - Sylvaneth

**Comment by OftKilted** [comment]
Death/Chaos Updated

**Comment by tekton** [comment]
Desetruction on the done-ish
