### ISSUE TITLE
Tzeentch Lord of Change

### ISSUE THREAD

**Issue by silentpolygon** [BSData/warhammer-age-of-sigmar#637]
The curves Beak and Wickede Talons are noch Weapon Choice. Onkyo the Baleful Sword and the Rod of Sorcery. Rother Was the LoC hast the Beaks and Talons.

**Comment by OftKilted** [comment]
“A Lord of Change is a single model. It carries a Staff of Tzeentch and either a Baleful Sword or a Rod of Sorcery. Alternatively,it can carry a Staff of Tzeentch and tear at its foes with its Curved Beak and Wicked Talons”

So, Weapon options:
Staff and Sword
Staff and Rod

Alternately:
Staff and Talons

Effectively:
Staff and (Sword or Rod or Claws and Talons)

**Comment by silentpolygon** [comment]
Ok...so i played it wrong the whole time. Thank you.
