### ISSUE TITLE
Request : Chaos - Tzeentch - Slaves to Darkness Sorcerer Lord on Manticore not available in Tzeentch Cat

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#655]
**File:** Chaos - Tzeentch.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** Yes

**Description:** When I create a Tzeentch army, I can choose a Chaos Sorcerer Lord, but not a Chaos Sorcerer Lord on Manticore from the Leader category. Maybe it's a fine point of the rules that I cannot locate.

**Comment by OftKilted** [comment]
Until catalog libraries are made available in a future version of Battlescribe no additional units will be added directly to avoid library issues.

**Comment by cartag** [comment]
Resolved in latest version.
