### ISSUE TITLE
Nighthaunt - No Command Trait options when making Lady Olynder the General

### ISSUE THREAD

**Issue by jasonstanden** [BSData/warhammer-age-of-sigmar#658]
Self explanatory....

When I make Lady Olynder my general, I don't get the Command Trait options appearing to select from.

**Comment by OftKilted** [comment]
Lady Olynder is a Named character. Named characters do not get access to Artefacts or Command Traits.

P. 242 Core Book “NAMED CHARACTERS
Named characters such as Nagash, Archaon and Alarielle are singular and mighty warriors, with their own personalities and artefacts of power. As such, these models cannot have a command trait or artefact of power.”
