### ISSUE TITLE
Points value for idoneth

### ISSUE THREAD

**Issue by kalstel** [BSData/warhammer-age-of-sigmar#678]
Hello. First off I appreciate what you guys do and how it’s helped me play the game better. I do not know if it’s been addressed but I did a search on weather someone put a request for the points value of idoneth deepkin to be updated to ghb 2018. If it was addressed then I apologize. Thank you for your time and consideration.

**Comment by OftKilted** [comment]
The Idoneth Deepkin Points in the GHB were faq’d. Do you have a specific unit that you can point to as being incorrect?

https://whc-cdn.games-workshop.com/wp-content/uploads/2018/06/age_of_sigmar_generals_handbook_errata_en-1.pdf

**Comment by kalstel** [comment]
I apologize. I am still learning about the the game in regards to erratas and faqs.  Thanks for the great work

**Comment by OftKilted** [comment]
@kalstel No worries, we miss things like everyone else :+1: Thanks for the feedback!

If your issue has been resolved, feel free to close the issue. Or I can close it for you if you’d prefer.
