### ISSUE TITLE
Performance Problems [High Memory Usage on Android]: Chaos - Khorne.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#687]
**File:** Chaos - Khorne.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** When trying to create an army or add forces to a different army, the message creating roster times out and says I have run out of ram.  Selecting low ram makes no difference.  All other forces creating and adding seem to be fine.  I can create khorn and add it as a force on iOS.  I am only having difficulty with Android.  Lenovo tablet TB-X103F_180307.  Android 6.0.1.

**Comment by OftKilted** [comment]
The TB-X103F_180307 only has 1GB of RAM.

**Comment by Tenchi954** [comment]
I am also experiencing this same issue. I am using a Fire HD 10 with the latest version of the os and battlescribe.
