### ISSUE TITLE
Unit selection - Forces of destruction

### ISSUE THREAD

**Issue by Wolfchild6250** [BSData/warhammer-age-of-sigmar#69]
Lots of Ogor (were Ogre Kingdoms) units that start with 2 or 3 models can't be increased incrementally by 1 model above base value, instead all I can do is multiply the base value to get eg. "3x2 Mournfang Pack" in the same entry.

**Comment by ResidentSteve** [comment]
Hello, it's because in the generals handbook you can only increment a squad by the initial size. Mournfang are increased by two at a time for example. You can add one mournfang to the squad but it isn't pro-rata, you still pay for 2 and this is why you can't add individuals in battlescribe

**Comment by Wolfchild6250** [comment]
Thank you

Get Outlook for Android<https://aka.ms/ghei36>



On Wed, Dec 14, 2016 at 8:05 PM +0000, "ResidentSteve" <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #69<https://github.com/BSData/warhammer-age-of-sigmar/issues/69>.
