### ISSUE TITLE
Destruction: Gitmob Grots not available as “Other” when selecting as Allies

### ISSUE THREAD

**Issue by OftKilted** [BSData/warhammer-age-of-sigmar#696]
Gitmob grots are missing in action when they are selected as an allied force.

**Comment by tekton** [comment]
The decision was made to allow this since GH18 has changed the logic around a bit.

**Comment by UrsinePatriarch** [comment]
Is this still a problem?
I just reworked most of the major Destruction cats, so I can try to fix this if y'all like.
Far as I understand, it's just the old AoS1 formatting that's messed up still, right?
