### ISSUE TITLE
New Publication: Chaos - Beasts of Chaos

### ISSUE THREAD

**Issue by OftKilted** [BSData/warhammer-age-of-sigmar#706]
Merge Catalogs and Create "Beasts of Chaos" catalog

**Comment by actionb461** [comment]
Not a developer here but very excited for this to be added

**Comment by actionb461** [comment]
Hi! Not to be annoying, I'm just curious is this still being worked on?

**Comment by UrsinePatriarch** [comment]
I'm interested enough in this that I might take a crack at it.

Anyone else working on it?

**Comment by teage-like-league** [comment]
I am currently working on this. If you would like you can remove the Stalled tag and assign to me.

**Comment by cartag** [comment]
@teage-like-league are you still working on this?
