### ISSUE TITLE
AoS Stormcast - unable to select stormhost

### ISSUE THREAD

**Issue by bigstadder** [BSData/warhammer-age-of-sigmar#707]
I just fell in love with battlescribe and I am so impressed by your data file. Is there a trick to selecting stormhosts for Stormcasts or are they on the books to be implemented later?

**Comment by rweyrauch** [comment]
The Stormcast catalogs support the Stormhosts.   On the mobile app, you select the Stormhost by selecting the Stormcast Eternals allegiance.
![select allegiance 1](https://user-images.githubusercontent.com/7072852/46453736-e69e0d00-c757-11e8-94ba-3d264f1acdad.png)
![screenshot_20181003-215646](https://user-images.githubusercontent.com/7072852/46453738-e998fd80-c757-11e8-9425-000bc09fd53a.png)
![screenshot oct 3 2018 9_56_52 pm](https://user-images.githubusercontent.com/7072852/46453740-eaca2a80-c757-11e8-8f0c-2fdd1de96011.png)

**Comment by bigstadder** [comment]
Oh my goodness. It works. Thank you so much!!!!


----- Original Message -----
