### ISSUE TITLE
[Anon] Bug report: Order - Scourge Privateers.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#716]
**File:** Order - Scourge Privateers.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** The Skink priest doesn't have it's Starbolt ranged attack.

**Comment by rweyrauch** [comment]
The 'Weapon Option' allows you to select either the 'Priestly Trappings' or the 'Cloak of Feathers'. If you select the 'Cloak of Feather' the Priest gets the Starbolt missile weapon.
