### ISSUE TITLE
Battalions should enforce composition rules - Order

### ISSUE THREAD

**Issue by alphalas** [BSData/warhammer-age-of-sigmar#72]
- [x] Bretonnia 
- [x] Collegiate Arcana
- [x] Dark Elves
- [x] Darkling Covens
- [x] Daughters of Khaine
- [x] Devoted of Sigmar
- [x] Dispossessed
- [x] Dwarfs
- [x] Eldrich Council
- [x] Free Peoples
- [x] Fyreslayers
- [x] High Elves
- [x] Idoneth Deepkin
- [x] Ironweld Arsenal 
- [x] Kharadron Overlords
- [x] Lion Rangers
- [x] Lizardmen
- [x] Monstrous Arcanum
- [x] Order Draconis
- [x] Order Serpentis
- [x] Phoenix Temple
- [x] Scourge Privateers
- [x] Seraphon
- [x] Shadowblades 
- [x] Stormcast Eternals
- [x] Swifthawk Agents
- [x] Sylvaneth
- [x] The Empire
- [x] Wanderers
- [x] Wood Elves

**Comment by alphalas** [comment]
Rastus's comment on #58 explains how to.

**Comment by rweyrauch** [comment]
All Order catalogs include battalion validation.
