### ISSUE TITLE
Missing units with Death - Grand host of Nagash

### ISSUE THREAD

**Issue by Lollinick** [BSData/warhammer-age-of-sigmar#723]
Lady Olynder
Kurdoss Valentian
Reikenor the Grimhailer
Chainghasts
Dreadblade Harrow

**Comment by rweyrauch** [comment]
These units were released with v2.0.3.   Is you data up-to-date?

**Comment by rweyrauch** [comment]
Missing units are in the catalog but are visible to select.

**Comment by rweyrauch** [comment]
As designed.

**Comment by rweyrauch** [comment]
The
