### ISSUE TITLE
Chaos - Tzeentch - Points incorrect for multiple units

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#724]
**File:** Chaos - Tzeentch.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Pts cost for Tzaangor Skyfires and Tzaangor Enlightened are not correct.
Skyfires are 200 pts, not 220.
Enlightened are 100 on foot and 140 on discs, not 160.

**Comment by OftKilted** [comment]
Libraries/Cross-Referencing hasn't been implemented. All units are unique to a catalog. Which can cause some catalogs to become very large. (e.g. Khorne.) This has been known to cause performance problems on devices with less than 1GB of RAM.
