### ISSUE TITLE
Suggestion: Add spells and command abilities for Realms of Origin

### ISSUE THREAD

**Issue by BerkshireKnight** [BSData/warhammer-age-of-sigmar#726]
As title! It'd be helpful if your selected realm of origin displayed the associated spell and command ability.

**Comment by rweyrauch** [comment]
Realm spells are selected based upon the realm in-which the battle/game is taking place.  The realm choice is part of the battle setup and cannot be determined when the list is created.   There are no realm-specific command abilities.

The AoS catalogs do support artifact selections based on the realm of origin.

**Comment by Mikle103** [comment]
Hi, 
I understand where you are coming from as realm is determind at setup, but what if i am using a tablet with BS on it and am can then add the realm and spells and have a accurate list with all information in one place.

I like a paperless system, and do a PDF print of list and use this on tablet to referance when playing. So yes who says that list creatition cannot be finished when battle setup is done. 
Just my 2 cents worth.

**Comment by rweyrauch** [comment]
We could add a 'Realm of Battle' as an option.   Selecting a realm would add a list of the realm-specific spells.  I'll tinker around with this.

**Comment by rweyrauch** [comment]
Implemented by #740.
