### ISSUE TITLE
Battalions should enforce composition rules - Chaos

### ISSUE THREAD

**Issue by alphalas** [BSData/warhammer-age-of-sigmar#73]
- [x] Blades of Khorne
~~Beastmen~~ (Depreciated. No Battalions currently in Catalog)
- [x] Brayherds
- [x] Chaos Gargants
~~Daemons of Chaos~~ (Depreciated and not in Matched Play.)
- [x] Disciples of Tzeentch
Everchosen (Battalions use units from other catalogs. To be addressed after inheritance.)
~~Host of Slaanesh~~ (No Battalions listed in GHB 2017)
- [x] Monsters of Chaos (Applicable Monsters of Chaos have been added to their respective catalogs)
~~Monstrous Arcanum~~ (This has been rolled into Monsters of Chaos)
- [x] Maggotkin of Nurgle
- [x] Skaven 
- [x] Skaven Eshin
- [x] Skaven Masterclan
- [x] Skaven Moulder
- [x] Skaven Pestilens
- [x] Skaven Skryre
- [x] Skaven Verminus
- [x] Slaves to Darkness
- [x] Tamurkhan's Horde
- [x] Legion of Azgorh
- [x] Thunderscorn (No Battalions.)
~~Warherds~~ (No Battalions.)
~~Warriors of Chaos~~ (No Battalions. This Battletome has been depreciated.)

**Comment by alphalas** [comment]
Rastus's comment on #58 explains how to.

**Comment by OftKilted** [comment]
All current CHAOS GHB 2017 catalogs that are not using multi-catalog battalions are validated.
Unable to cleanly validate the Everchosen catalog due to lack of Inheritance. Closing issue, will reopen or create new once Battlescribe adds inheritance.
