### ISSUE TITLE
[Anon] Bug report: Chaos - Daemons of Chaos.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#733]
**File:** Chaos - Daemons of Chaos.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Missing chart information for a braketed great unclean one unit

**Comment by rweyrauch** [comment]
What is a braketed great unclean one?

The GUO is in the Nurgle catalog as is the Exalted Greater Daemon of Nurgle.
