### ISSUE TITLE
Death - December 2018 FAQ Update

### ISSUE THREAD

**Issue by rweyrauch** [BSData/warhammer-age-of-sigmar#745]
- [x] - Nighthaunt
- [ ] - Legions of Nagash
- [x] - Flesh-eater Courts
- [x] - Vampire Counts

**Comment by rweyrauch** [comment]
The Dec 2018 FAQ only applies to the Legions of Nagash.

**Comment by rweyrauch** [comment]
There is no way to select the 'Guardian of Souls with Mortality Glass' unit in the Death catalog.  Missing a Root Selection Entries?

**Comment by Shoxaju** [comment]
the necromancer is part of Legions of Nagash, but does not show up in the listing

**Comment by UrsinePatriarch** [comment]
@rweyrauch Whoops.
Dammit, I knew I missed something; I'll fix it tonight. 
@Shoxaju Whatcha mean, mate? You'll have to be more specific,

**Comment by Shoxaju** [comment]
@UrsinePatriarch I went through all the death allegiances but couldn't find the necromancer, but the warscroll from GW says it's part of the Legions of Nagash. Should be in the leader section, unless there's an option somewhere I'm missing.

**Comment by UrsinePatriarch** [comment]
@Shoxaju Seems fine to me, mate. Any other problems that might be causing it?
<img width="289" alt="capture" src="https://user-images.githubusercontent.com/46959832/53856335-79f59b80-3f9f-11e9-8f74-07c3c8ff04df.PNG">

**Comment by Shoxaju** [comment]
interesting. It doesn't show up in mobile then. I can't find it anywhere.

**Comment by UrsinePatriarch** [comment]
Outside of this dude being unable to find Necromancer on his phone due to an entirely different issue (I can find it just fine on mine, so I'm not sure what would be causing it for them), this issue seems closed as of my recent upload.
