### ISSUE TITLE
New Publication: Destruction Gloomspite Gitz

### ISSUE THREAD

**Issue by rweyrauch** [BSData/warhammer-age-of-sigmar#759]
Create Gloomspitz Gitz catalog.

**Comment by tekton** [comment]
Being sick slowed me down, still chugging

**Comment by UrsinePatriarch** [comment]
Howdy, mate; I’m new and this is my first foray into repo stuff, but I’ve also been working on the GG stuff for the past day or two. I’d love to see what you have up and see what I can do to help! 

I spent most of today setting up the different General interactions with Battleline units and Command Traits, etc, basing my logic on the Deepkin and Nighthaunt files; I’d love your input on it if you haven’t done so already.

**Comment by cartag** [comment]
I just now saw this, but I'm about 75% through a ground-up build of the catalog. How far along are you on yours? This is what happens when I want to play a new army and get bored.

**Comment by UrsinePatriarch** [comment]
I've got the units mocked up for the most part; all I've got left are specific, long-winded abilities and Battalions.

Did you work out a workable General system for Command Traits and Battleline options? That's the only thing I'm actually fairly proud of, so I'm interested in comparing notes.

**Comment by cartag** [comment]
Nevermind, my computer crashed and I lost a good chunk of progress. I had my command traits set up with all in a SSEG, with each section being it's own SEG. I set them as hidden, and to unhide if Ancestor is instance of KEYWORD. Same thing for Battleline. I have a SSE called General that is linked to all HEROs and has the Command Trait SSEG in it.

**Comment by UrsinePatriarch** [comment]
Hey hey, same here; apparently I might've been doing something right, haha.
If yah like, I can keep working or leave it to y'all; I'm most curious to see where Tekton was/is.

**Comment by UrsinePatriarch** [comment]
As an update to this, I just got all of the points and General/artefact/CT/etc coordination set up; gonna be working on battalions soon, then abilities to fill in.

No idea where I can drop this to show off since it's unfinished, but I hope you'll be patient either way.

**Comment by UrsinePatriarch** [comment]
After way too long, it's mostly done!

Units have their abilities and points and everything all set up, the infrastructure is complete, and battalions actually work, haha.

All that's left now are the things I need to hand-transcribe, i.e. those not in Warscrolls (artefacts, spells, command traits, allegiance abilities, etc.) and it'll be all done; thanks again for your patience.

**Comment by rweyrauch** [comment]
Might be wise to merge and commit what you have.

**Comment by UrsinePatriarch** [comment]
No idea what that means, but I completed everything else in the meantime!

If you could point in the direction of what the heck I can do to upload this, I'd be mighty obliged.

**Comment by cartag** [comment]
![image](https://user-images.githubusercontent.com/4388344/52505498-e5b73500-2ba8-11e9-84bf-498033029cd0.png)

I can work on wrapping it up if you want

**Comment by UrsinePatriarch** [comment]
Trying to not sound super catty, mate, but I tried that bit; I'm not quite _that_ daft unless I'm missing something big here.
<img width="337" alt="capture" src="https://user-images.githubusercontent.com/46959832/52505675-40a55800-2bba-11e9-8cfa-96b9f49efc86.PNG">

**Comment by Mad-Spy** [comment]
You won't be able to upload to the main repo because you won't have permissions. 

You'll need to fork it (using the Fork button at the top of the page). This will make you a personal copy of the repo. Next, copy your file into your new fork. Once you've done that, create a pull request (from the pull requests tab) to request that your changes get "pulled" into the main repo by someone with permissions.

**Comment by UrsinePatriarch** [comment]
Excellent!
Specific and to the point; thanks for being patient with my new-ness, mate; be back once it's done.

**Comment by OftKilted** [comment]
@UrsinePatriarch your pull request #782 needs to be reviewed.

**Comment by cartag** [comment]
I pulled it from your repo and started working on it.

**Comment by UrsinePatriarch** [comment]
Working on what mate? Double-checks and whatnot?
I'm curious if I missed anything.

**Comment by rweyrauch** [comment]
I just merged your pull request and will remove the 'extra' catalogs (the .catz and Destruction_-_GG.cat.

**Comment by UrsinePatriarch** [comment]
Alright, thanks a ton again, Rick; I'm working on double-checks right now and I'll post any fixes I find probably later this week.
