### ISSUE TITLE
Tzeentch Tzaangor Enlightened and Skyfire Points update

### ISSUE THREAD

**Issue by HumanityXM** [BSData/warhammer-age-of-sigmar#764]
Within the Chaos - Tzeentch lists
The current entries for tzaangor SKyfires show as 220pts, the latest updates from beasts of chaos changed their points to 200 for 3.

Tzaangor enlightened changed to 100pts for 3 on foot and 140pts for 3 on discs. Current entry in BS has them listed at 160pts, with and without discs.

**Comment by OftKilted** [comment]
Resolved with most recent release. Closing issue.
