### ISSUE TITLE
Support for Skirmish 2.0

### ISSUE THREAD

**Issue by nottsknight** [BSData/warhammer-age-of-sigmar#768]
January WD released an updated set of rules for Skirmish. Are there any plans to support these rules in Battlescribe at all? The warscrolls are all exactly the same as for regular AoS, but models have individual points costs. I'd imagine it'd require a separate repo, but thought I'd raise the issue just to see what the current plans were (if any).

**Comment by rweyrauch** [comment]
There are no plans yet as far as I know.

**Comment by OftKilted** [comment]
The current challenge with the implementation is that most units aren’t done as “individual purchase” they’re purchased in blocks of a minimum allotment. (IE 1 unit of 2 selections of 10 models).

While leaders would only require a repointing cost, almost all other units would require a rework or modification to work.
