### ISSUE TITLE
No permission to push updated files 

### ISSUE THREAD

**Issue by StealthKnightSteg** [BSData/warhammer-age-of-sigmar#78]
Recently I have returned and I worked a little on the Order file (see also my submissions on issues), but apparently I can still clone projects, update them, but can't push updates under my permissions.
(This might be a covert join request for this specific section, I do hope I can still update whfb as I used to? I might feel nostalgic..)

**Comment by amis92** [comment]
Hi there, sorry for a problem, it seems I might have been a little too zealous when cleaning org up and dividing members into teams. I've added you to the GW team, you should have the write access now.

**Comment by StealthKnightSteg** [comment]
thank you!
