### ISSUE TITLE
Updated Publication: Death Flesh Eaters Court

### ISSUE THREAD

**Issue by rweyrauch** [BSData/warhammer-age-of-sigmar#783]
Update FEC catalog with new battletome.

- [x] Update unit warscrolls
- [x] Update battalion warscrolls
- [x] Update points
- [x] Command traits Royalty
- [x] Command traits Nobility
- [x] Artefacts Royal Treasury
- [x] Artefacts Noble Heirlooms
- [x] Spell Lores
- [x] Mount traits Terrorgheist
- [x] Mount traits Zombie Dragon
- [x] Endless spells
- [x] Grand Courts
- [x] Battleline if... for Grand Courts

**Comment by UrsinePatriarch** [comment]
I might be able to work on this if no one else does; I'll keep you posted, chief.
