### ISSUE TITLE
Gloomspite Gitz - Multiple

### ISSUE THREAD

**Issue by cartag** [BSData/warhammer-age-of-sigmar#788]
- [ ] Skagrott - Should not be able to take artefacts as a named character
- [ ] Mollog - Should not be able to take artefacts as a named character
- [ ] Mollog - Should not be able to take command trait if general as a named character
- [ ] Spider Riders - Drums and Totem limited to 1/10 models
- [ ] Shiny Wotnot - change last sentence to ‘If the mortal wound was inflicted by an endless spell, on a 6+ that mortal wound is negated, and that endless spell is dispelled (any other mortal wounds it could have inflicted are negated).’
- [ ] Loonboss - I'm Da Boss - Change first and second sentences to ‘You can use this command ability at the start of the combat phase. If you do so, pick 1 friendly Moonclan Grot unit wholly within 12" of a friendly model with this command ability, or wholly within 24" of a model with this command ability that is your general.’
- [ ] Loonboss with Giant Squig - I'm Da Boss - Change first and second sentences to ‘You can use this command ability at the start of the combat phase. If you do so, pick 1 friendly Moonclan Grot unit wholly within 12" of a friendly model with this command ability, or wholly within 24" of a model with this command ability that is your general.’
- [ ] Scuttleboss on Gigantic Spider -  Ride 'em All Down! - Change first and second sentence to ‘You can use this command ability at the start of your charge phase. If you do so, pick 1 friendly Spiderfang Grot unit wholly within 18" of a friendly model with this command ability.’
- [ ] Gift of the Gloomspite - Great Shaman - Need to allow second spell to be selected
- [ ] Gift of the Gloomspite - Boss Shaman - include rule they get in profile
- [ ] Blessings of the Bad Moon - Tough 'n Leathery - Modify wounds stat in profile
- [ ] Blessings of the Bad Moon - The Clammy Hand - change to ‘If this general is within 12" of a friendly Bad Moon Loonshrine at the end of your turn, you can use the Bad Moon Loonshrine’s ‘Moonclan Lair’ scenery rule 2 times at the end of that turn.
- [ ] Marks of the Spider God's Blessing - Tough 'n Leathery - Modify wounds stat in profile
- [ ] Fortuitous Troggoth Traits - Tough As Rocks - Modify wounds stat in profile

**Comment by UrsinePatriarch** [comment]
All taken care of, chief; I'll have the new .cat up with my next update, whether it be the revised LoN or the Beasts of Chaos I'm working on.

Thanks for the heads up.

**Comment by OftKilted** [comment]
@ursinepatriarch - There’s a current branch with Beasts of Chaos that has been stalled. I’d recommend forking that or working in that branch ... and please join the Gitter

**Comment by cartag** [comment]
Adding errata fixes in to top post

**Comment by cartag** [comment]
I also made this bug report a task list, so you can check off what you get finished as you work on it. It's really handy.

**Comment by UrsinePatriarch** [comment]
> * [X]  Skagrott - Should not be able to take artefacts as a named character
> * [X]  Mollog - Should not be able to take artefacts as a named character
> * [X]  Mollog - Should not be able to take command trait if general as a named character
> * [X]  Spider Riders - Drums and Totem limited to 1/10 models
> * [X]  Shiny Wotnot - change last sentence to ‘If the mortal wound was inflicted by an endless spell, on a 6+ that mortal wound is negated, and that endless spell is dispelled (any other mortal wounds it could have inflicted are negated).’
> * [X]  Loonboss - I'm Da Boss - Change first and second sentences to ‘You can use this command ability at the start of the combat phase. If you do so, pick 1 friendly Moonclan Grot unit wholly within 12" of a friendly model with this command ability, or wholly within 24" of a model with this command ability that is your general.’
> * [X]  Loonboss with Giant Squig - I'm Da Boss - Change first and second sentences to ‘You can use this command ability at the start of the combat phase. If you do so, pick 1 friendly Moonclan Grot unit wholly within 12" of a friendly model with this command ability, or wholly within 24" of a model with this command ability that is your general.’
> * [X]  Scuttleboss on Gigantic Spider -  Ride 'em All Down! - Change first and second sentence to ‘You can use this command ability at the start of your charge phase. If you do so, pick 1 friendly Spiderfang Grot unit wholly within 18" of a friendly model with this command ability.’
> * [X]  Gift of the Gloomspite - Great Shaman - Need to allow second spell to be selected
> * [X]  Gift of the Gloomspite - Boss Shaman - include rule they get in profile (Only Madcap Shaman and Fungoid are eligible for this, right?)
> * [ ]  Blessings of the Bad Moon - Tough 'n Leathery - Modify wounds stat in profile [No idea how to do this]
> * [X]  Blessings of the Bad Moon - The Clammy Hand - change to ‘If this general is within 12" of a friendly Bad Moon Loonshrine at the end of your turn, you can use the Bad Moon Loonshrine’s ‘Moonclan Lair’ scenery rule 2 times at the end of that turn.
> * [ ]  Marks of the Spider God's Blessing - Tough 'n Leathery - Modify wounds stat in profile [No idea how to do this]
> * [ ]  Fortuitous Troggoth Traits - Tough As Rocks - Modify wounds stat in profile [No idea how to do this]

Seems like most of these were just errata fixes that I hadn't gotten around to yet; any way you can point me towards how to directly modify stat sheets? Please don't tell me it's literally just having two separate unit profiles with each one being hidden under certain conditions.

....dammit, that's what it is, isn't it?

**Comment by UrsinePatriarch** [comment]
Also @OftKilted ; what does forking actually do in that instance other than create a copy of the main repo? And Gitter?

**Comment by alphalas** [comment]
![12d83f4b-e629-4591-9956-51857cbd4d60](https://user-images.githubusercontent.com/15703066/52950119-24d54b00-334c-11e9-8b5f-d541b9b9a52a.png)

 Gitter is the place where, you know, the landing page says to talk to us before making any changes to the files? 

https://gitter.im/BSData/warhammer-age-of-sigmar

**Comment by UrsinePatriarch** [comment]
Just to be clear for anyone looking into this eventually, I'm currently working on the formatting for the file alongside all of the above changes; should have it done by the end of the month.

Thanks for your patience ~

**Comment by xerusjoe** [comment]
Didn't see it in any of the other bits, but Spider Riders are 100pts per every 5, but at the 6x5 level they should be 540. Currently they are 600pts for 6x5.

**Comment by UrsinePatriarch** [comment]
@xerusjoe Good catch! Dunno how I missed that.
I'll update that now, my dude, and it'll be uploaded once I'm done with the technical formatting.
