### ISSUE TITLE
Legions of Nagash Formatting

### ISSUE THREAD

**Issue by UrsinePatriarch** [BSData/warhammer-age-of-sigmar#789]
Howdy, all.

Seems the LoN catalog has a whole lot of extraneous formatting and frankly wrong issues going on with it.

Might just be my understanding, but it seems like a lot of the Nighthaunt Battalions require Nighthaunt exclusive units, but those battalions are still available to other LoN Allegiances; not sure if that's incorrect or not.

The naming conventions are also all kinds of odd, and some of the Battalions flat-out don't work; last I checked, a Legion of Sacrament list can't actually take the LORDS OF SACRAMENT Battalion because it'll require Arkhan to be in two places at once, both Leader and Battalion. I suspect the other Mortarchs' Battalions are likely the same.

Furthermore, there are a TON of what I'm presuming to be older references to pre-LoN formatting problems (Set hidden if FEC, set hidden if Deathmages, etc etc); I'm not sure these are needed anymore and they're fairly cluttery, so I'd like to know if they serve any purpose anymore.

Sorry if I'm stepping on anyone's toes doing this; just trying to clear things up to see if I can help.
- Cheers ~

**Comment by OftKilted** [comment]
Please clarify “Naming Conventions are also all kinds of odd”.

Thanks for the bug report on Arkhan.

The cross references exist as they happen to reference guids from the FEC catalog and battlescribe catalogs haven’t migrated to using libraries yet. And the logic while potentially extraneous is accurate.

**Comment by UrsinePatriarch** [comment]
Clarification: older Battalions are ALL IN UPPERCASE FOR WHATEVER REASON while newer ones are not. It looks sloppy and odd, not to mention the fact that I'm fairly sure we shouldn't even be able to see most of those battalions due to unit restrictions and whatnot.

Could you explain the second part more thoroughly, though? I feel as if I'm missing something. My main concern was the fact that at this point, FEC should have almost no bearing on LoN concerns as they're strictly allies now, unless I'm vastly missing the point.

For instance, look at the logic behind Arkhan in the screenshot here; he's set to be hidden if:
Option 1) The Roster is Allegiance: Deathmages (No longer possible)
Option 2) There's an Allied Detachment and the roster has any of the main 5 LoN allegiances, but Deathlords is still there (also no longer possible)
Option 3) Ancestor is NOT Allies and roster is not one of the main 5 Allegiances. This will only occur in the instance of Nighthaunt or Soulblight, so why not use "Greater Than 0" clauses for those two instead of "Equal to 0" clauses for the other 5/6?
<img width="357" alt="capture" src="https://user-images.githubusercontent.com/46959832/52947096-c310e300-3343-11e9-9ea9-16c9d8f223bc.PNG">


I apologize again if I'm getting anything wrong here, but many of these data files just seem like needless spaghetti code.
