### ISSUE TITLE
Khorne Bloodbound - Multiple

### ISSUE THREAD

**Issue by cartag** [BSData/warhammer-age-of-sigmar#790]
- [x] Non-daemons should be able to take Daemonic Gifts, per latest errata. 
- [x] Karanak - Prey of the Blood God - per latest errata should read ‘After armies are set up, but before the first battle round begins, you can pick 1 enemy Hero to be Karanak’s quarry. You can re-roll hit and wound rolls for attacks made by Karanak that target the quarry.’

**Comment by cartag** [comment]
- [ ] Missing The Boundless Hunt battalion from Wrath and Rapture.

**Comment by rweyrauch** [comment]
The most recent Karanak warscroll has updated the Prey of the Blood God ability yet again.  This text in currently in the catalog.
The Boundless Hunt battalion is already in the v26 Khorne catalog.
