### ISSUE TITLE
Slaanesh - Multiple

### ISSUE THREAD

**Issue by cartag** [BSData/warhammer-age-of-sigmar#791]
- [x] Infernal Enrapturess - Is not currently able to be selected as general, should be able to
- [x] Hellstriders of Slaanesh, Enrapturing Banner - Change the last sentence of the rules text to: ‘Subtract 1 from hit rolls for attacks made by enemy models while they are within 6" of any friendly units that include any Enrapturing Banners.’

**Comment by rweyrauch** [comment]
Both of these changes are already present in Slaanesh v17.
