### ISSUE TITLE
AoS starter set warscrolls

### ISSUE THREAD

**Issue by chevalric** [BSData/warhammer-age-of-sigmar#8]
How do we handle the AoS Starter set? There's a couple of issues with regards to the warscrolls in there.
1. The separately released Lord-Celestant is a different model from the Starter Set one, with different stats.
2. The Prosecutors are not available outside of the Starter Set, but might be released separately later on.
3. The Starter Set Liberators have fewer abilities and weapon choices compared to the separate set.

I'm sure there are also differences for the Chaos models.

How do we add the Starter Set models? Should it be a separate category altogether?

**Comment by MrRta1910** [comment]
U have the dracoth as a unit upgrade for the lord celestant

**Comment by flakpanda** [comment]
Closed due to age
