### ISSUE TITLE
Age of Sigmar v42 flesh eater courts v12

### ISSUE THREAD

**Issue by varanguard** [BSData/warhammer-age-of-sigmar#808]
There are quite a few missing entries in this list as well as the inability to do anything with bloodlines and delusions.  I assume that this isnt updated to reflect the changes in the new book.  Is there anything in the works to reflect the changes?

**Comment by varanguard** [comment]
Sorry if this isn't the correct place to put this, new to github

**Comment by rweyrauch** [comment]
Updates for the new FEC battletome will be available in the next release of the AoS catalogs.

**Comment by rweyrauch** [comment]
Available in release 2.0.21.
