### ISSUE TITLE
Legacy Warscrolls Omitted

### ISSUE THREAD

**Issue by hutting7** [BSData/warhammer-age-of-sigmar#84]
Hi there, 
Can we get Legacy warscrolls included into the data please? Things like Sigvald the Magnificent and Chaos Forsaken as well as Tomb Kings and Bretonnians, these are still valid to play in matched-play and have point values and battlefield roles. I'm regularly using these in my games and it means I can't use Battlescribe for my full list.

**Comment by ResidentSteve** [comment]
Hello,

Tomb Kings should be in there already.

There's some other legacy stuff as well, but it'll all be there eventually.
