### ISSUE TITLE
Flesh eater courts

### ISSUE THREAD

**Issue by Faintsmil3** [BSData/warhammer-age-of-sigmar#846]
3 flayers cost 170 points like they should but when you take more flayers they only cost 160 points more when they should cost 170 points more.
So 6 flayers should cost 340 points and not 330 points and 9 flayers should cost 510 points and not 490 points and so on.

**Comment by Faintsmil3** [comment]
Why is this closed when the points is still not adjusted?

**Comment by OftKilted** [comment]
Because there hasn’t been a release since the close. So the fix will show up after the next release.
