### ISSUE TITLE
Order - Fyreslayers v22

### ISSUE THREAD

**Issue by KrymzonAshe** [BSData/warhammer-age-of-sigmar#871]
Error with Runefather Selected as General and Hearthguard Berzerkers added into Roster selection. 
States "Other cannot have any selections of Hearthguard Bezerkers (hidden.)" 

These units should be avialable only when the Runefather is selected as general no? Once he is deselected as general error goes away, and does not occur when any other is selected as a general.

Thanks.

**Comment by rweyrauch** [comment]
This behavior is a side effect of how Battlescribe handles 'Battleline' vs 'Other' for units that are battleline a particular unit is the general.
The workaround for message is to remove the unit that was initially added from the 'Other' catagory and then re-add them from the 'Battleline' catagory.
As a rule, in the AoS catalogs it is best to select your general first and then add the supporting units.

**Comment by KrymzonAshe** [comment]
Thank you!
