### ISSUE TITLE
[Join Request] AoS

### ISSUE THREAD

**Issue by Colten-Long** [BSData/warhammer-age-of-sigmar#9]
I would like to join.

**Comment by amis92** [comment]
I take it you want to contribute to the repo? Or just use them datafiles?

**Comment by Colten-Long** [comment]
I can contribute. Do you have anyone working on Lizardmen?

**Comment by chevalric** [comment]
No, Lizardmen is not being worked on yet. You're welcome to help out!

**Comment by Colten-Long** [comment]
Great, I'll upload my initial Lizardmen file as soon as I'm added. I'll send a message to Amis directly as well.

**Comment by amis92** [comment]
To "send a message" (email notification of not disabled) just make a mention (`@username`). Adding now. Remember to accept the invitation! Welcome aboard.
