### ISSUE TITLE
Some entries deleted in Orders.at

### ISSUE THREAD

**Issue by Cupropituvanso** [BSData/warhammer-age-of-sigmar#94]
Great Eagle deleted completely.
Treelord missing all profiles.
No idea what is also away.

Looks like it dissappears during merge

**Comment by msinosic** [comment]
Great Eagle re-added

**Comment by Cupropituvanso** [comment]
Played yesterday and found also other issues, like wrong values. I will check all wood elves units and repair it.

**Comment by Cupropituvanso** [comment]
I think I have corrected the most ... I hope this was a one time only problem :)
