### ISSUE TITLE
Chaos: GHB 2019 Points Update

### ISSUE THREAD

**Issue by rweyrauch** [BSData/warhammer-age-of-sigmar#951]
Update Chaos with new Points

**Core Catalogues**
- [x] Beastmen
- [x] Beasts of Chaos
- [X] Brayherds - DEPRECATED
- [x] Chaos Gargants - DEPRECATED
- [x] Daemons of Chaos
- [x] Everchosen
- [x] Khorne
- [x] Legion of Azgorh
- [x] Monsters of Chaos
- [x] Nurgle
- [x] Skaven
- [x] Slaanesh
- [x] Slaves to Darkness 
- [x] Thunderscorn- DEPRECATED
- [x] Tzeentch
- [x] Warherds - DEPRECATED
- [x] Warriors of Chaos

**Comment by cartag** [comment]
Removing data files that have been deprecated
