### ISSUE TITLE
Chaos - Skaven: Clanshields outdated

### ISSUE THREAD

**Issue by FlamingSheep** [BSData/warhammer-age-of-sigmar#977]
On units CLAN RATS and STORMVERMIN

Current:
You can add 1 to save rolls for a unit with Clanshields against attacks that have Damage 1.

Updated:
Add 1 to save rolls for attacks that target a unit that carries Clanshields while it has 10 or more models.

Source:
Chaos Battletome Skaven, pg. 119

**Comment by cartag** [comment]
Fixed in next release.
