### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by Cyrrian** [BSData/warhammer-age-of-sigmar#98]
Hello,

I'd like to help with maintaining the data.

Thank you

**Comment by amis92** [comment]
Hello, @Cyrrian. Please accept the invitation in the email or on the [BSData organization webpage](https://github.com/BSData). Welcome aboard!

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

Cheers!
