### ISSUE TITLE
Nurgle - Affliction cyst with lord of Aff. as general causes error 

### ISSUE THREAD

**Issue by RedBishop777** [BSData/warhammer-age-of-sigmar#982]
If lord of affliction, inside an affliction cyst, is made general, following error appears:

"Battalion: Affliction cyst cannot have instance of pusgoyle blightlords"

Cheers!

**Comment by cartag** [comment]
Blightlords change from Other to Battleline depending on if the Lord of Affliction is the general or not. As it switches it will tell you that one cannot have any instances of Other, which are in the roster, instead of Battleline, which it just unhid and made available.

**Comment by RedBishop777** [comment]
Indeed, you have to remove them and add "fresh" ones for the error to go away. Annoying but not breaking.

cheers!
