### ISSUE TITLE
[Anon] Bug report: Destruction - Ironjawz.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warhammer-age-of-sigmar#983]
**File:** Destruction - Ironjawz.catz

**BattleScribe version:** 2.02.04

**Platform:** Windows

**Dropbox:** No

**Description:** Ironfist Battalion is should cost 160 points (as per Generals 2019) and instead costs 180

**Comment by rweyrauch** [comment]
GHB points changes are available in release 2.1.  Update your catalogs.
