### ISSUE TITLE
Skink Chief and Jungle Swarms missing

### ISSUE THREAD

**Issue by Aginor404** [BSData/warhammer-age-of-sigmar#99]
Just noticed the Seraphon units "Skink Chief" and "Jungle Swarms" are missing.
Those are still valid units so I think they should be included.

Their warscrolls can be found here, pages 18 and 29:
https://www.games-workshop.com/resources/PDF/AoS_Compendiums/warhammer-aos-lizardmen-en.pdf

There are also other old Warscrolls in that compendium, most of them are not be very useful anymore but some might be.

**Comment by alphalas** [comment]
Skink chief, Jungle swarms, oxyotl, tenehenehenehaun, and the battalions  are not seraphon, rather they are still lizardmen, as per the AoS official app. Yes, they should be still added, but not to seraphon.

**Comment by Aginor404** [comment]
I understand your argument.
They do have the Seraphon Keyword though. And if we don't add them to Seraphon wouldn't that mean it would prevent you from using Seraphon allegiance in the app? I am not very familiar with the app yet, but as far as I understood it checks such things.

**Comment by alphalas** [comment]
The AoS app does list them as separate races, however, as you pointed out all but the jungle swarms have seraphon keyword. 

As to that last question, it doesn't have allegiance abilities in the app for seraphon, so not really?

**Comment by Aginor404** [comment]
I just tried with the Battlescribe app (most recent version from play store downloaded a few hours ago) and it lets me pick Seraphon allegiance.
I imagine that in the future it will check whether it is allowed to pick that allegiance or not And display a warning, no?

**Comment by alphalas** [comment]
Oh you meant BS - yes BS does check. I thought you were referring to the AoS app from GW

**Comment by Aginor404** [comment]
Yeah sorry that was poorly worded earlier.
So if BS actually checks the keywords and allows units based on those I guess it is fine if they are in Lizardmen.
Not sure why the Jungle Swarms miss the keyword but to me it looks like maybe it is intended to use them in any Order army. No clue if it would break allegiance, I am rather new to AoS.

**Comment by flakpanda** [comment]
Will be added in 2.01 BS update
