### ISSUE TITLE
Tzeentch Mortal/Arcanite Heroes and Artefacts

### ISSUE THREAD

**Issue by Camyron** [BSData/warhammer-age-of-sigmar#998]
Force: Chaos - Tzeentch.cat
Platform: Android

Ogroid Thaumaturges, Magisters, and Fatemasters cannot be given Treasures of the Cults while under the same conditions that Gaunt Summoners and Tzaangor Shamans can.
Curseling, Eye of Tzeentch is not a named character (contrary to WHFB), but cannot be given any artefacts.

**Comment by cartag** [comment]
Fixed in next release.
