### ISSUE TITLE
Chaos - Tzeentch/Everchosen Gaunt Summoners

### ISSUE THREAD

**Issue by Camyron** [BSData/warhammer-age-of-sigmar#999]
Files: Chaos - Tzeentch, Chaos - Everchosen
Platform: Android

All Gaunt Summoners have the Tzeentch and Everchosen keywords, so should be available both in forces of Chaos - Everchosen and Chaos - Tzeentch. Gaunt Summoners on Disc can be taken in Everchosen forces, and Gaunt Summoners with Familiars and basic Gaunt Summoners can be taken in a tzeentch force.

**Comment by cartag** [comment]
Fixed in next release.
